# Generated by Django 4.2.4 on 2025-06-11 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invalmacen',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='invexistencia',
            options={'ordering': ['-id']},
        ),
    ]
