# Generated by Django 4.2.4 on 2025-09-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_invalmacen_options_alter_invexistencia_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='invexistencia',
            name='costo_promedio',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
