# Generated by Django 4.2.4 on 2025-09-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_invexistencia_costo_promedio'),
    ]

    operations = [
        migrations.AddField(
            model_name='invexistencia',
            name='costo_total',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
