# Generated by Django 4.2.4 on 2025-09-30 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_invexistencia_costo_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invexistencia',
            name='costo_promedio',
        ),
        migrations.RemoveField(
            model_name='invexistencia',
            name='costo_total',
        ),
    ]
