# Generated by Django 4.2 on 2023-04-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dominio',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
