# Generated by Django 4.2 on 2023-04-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_dominio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50)),
                ('estado_usado', models.BooleanField(default=True)),
                ('vence', models.DateField(null=True)),
            ],
        ),
    ]
