# Generated by Django 4.2 on 2023-04-25 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_verificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificacion',
            name='codigo_usuario_fk',
            field=models.IntegerField(null=True),
        ),
    ]
