# Generated by Django 4.1.7 on 2023-05-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_verificacion_codigo_usuario_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificacion',
            name='estado_usado',
            field=models.BooleanField(default=False),
        ),
    ]
