# Generated by Django 4.2 on 2023-06-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_verificacion_estado_usado'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificacion',
            name='accion',
            field=models.CharField(default='registro', max_length=10),
        ),
    ]
