# Generated by Django 4.2.4 on 2025-06-08 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumMotivoTerminacion',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'hum_motivo_terminacion',
            },
        ),
        migrations.CreateModel(
            name='HumLiquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('dias', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('cesantia', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('interes', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('prima', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('vacacion', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('deduccion', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('adicion', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('total', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('estado_aprobado', models.BooleanField(default=False)),
                ('estado_generado', models.BooleanField(default=False)),
                ('comentario', models.CharField(max_length=300, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones_contrato_rel', to='humano.humcontrato')),
                ('motivo_terminacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones_motivo_terminacion_rel', to='humano.hummotivoterminacion')),
            ],
            options={
                'db_table': 'hum_liquidacion',
            },
        ),
    ]
