# Generated by Django 4.2.4 on 2024-07-23 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'hum_grupo',
            },
        ),
        migrations.CreateModel(
            name='HumPagoTipo',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('consecutivo', models.IntegerField(default=1)),
                ('aplica_programacion', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'hum_pago_tipo',
            },
        ),
        migrations.CreateModel(
            name='HumProgramacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('fecha_hasta_periodo', models.DateField()),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('dias', models.IntegerField(default=0)),
                ('contratos', models.IntegerField(default=0)),
                ('neto', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('estado_aprobado', models.BooleanField(default=False)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pogramaciones_grupo_rel', to='humano.humpagotipo')),
                ('pago_tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pogramaciones_pago_tipo_rel', to='humano.humpagotipo')),
            ],
            options={
                'db_table': 'hum_programacion',
            },
        ),
    ]
