# Generated by Django 4.2.4 on 2025-06-09 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0002_hummotivoterminacion_humliquidacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='humliquidacion',
            name='motivo_terminacion',
        ),
        migrations.AddField(
            model_name='humcontrato',
            name='motivo_terminacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_motivo_terminacion_rel', to='humano.hummotivoterminacion'),
        ),
    ]
