# Generated by Django 4.2.4 on 2024-07-23 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0002_humgrupo_humpagotipo_humprogramacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humprogramacion',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pogramaciones_grupo_rel', to='humano.humgrupo'),
        ),
    ]
