# Generated by Django 4.2.4 on 2024-07-23 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0091_configuracion_informacion_factura_superior'),
        ('humano', '0003_alter_humprogramacion_grupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumContratoTipo',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'hum_contrato_tipo',
            },
        ),
        migrations.AddField(
            model_name='humcontrato',
            name='contacto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_contacto_rel', to='general.contacto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='humcontrato',
            name='estado_terminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='humcontrato',
            name='contrato_tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_contrato_tipo_rel', to='humano.humcontratotipo'),
            preserve_default=False,
        ),
    ]
