# Generated by Django 4.2.4 on 2025-06-09 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0003_remove_humliquidacion_motivo_terminacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='humliquidacion',
            options={'ordering': ['-id']},
        ),
    ]
