# Generated by Django 4.2.4 on 2024-07-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0004_humcontratotipo_humcontrato_contacto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='humprogramacion',
            name='descuento_adicional_permanente',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='humprogramacion',
            name='descuento_adicional_programacion',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='humprogramacion',
            name='descuento_credito',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='humprogramacion',
            name='descuento_embargo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='humprogramacion',
            name='descuento_fondo_solidaridad',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='humprogramacion',
            name='descuento_pension',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='humprogramacion',
            name='descuento_retencion_fuente',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='humprogramacion',
            name='descuento_salud',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='humprogramacion',
            name='pago_auxilio_transporte',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='humprogramacion',
            name='pago_horas',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='humprogramacion',
            name='pago_incapacidad',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='humprogramacion',
            name='pago_licencia',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='humprogramacion',
            name='pago_vacacion',
            field=models.BooleanField(default=True),
        ),
    ]
