# Generated by Django 4.2.4 on 2025-06-11 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0004_alter_humliquidacion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='humadicional',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='humaporte',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='humaportecontrato',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='humaportedetalle',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='humaporteentidad',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='humcargo',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='humconcepto',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='humconceptocuenta',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='humconceptonomina',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='humconceptotipo',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='humconfiguracionaporte',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='humconfiguracionprovision',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='humcontrato',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='humcontratotipo',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='humcredito',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='humentidad',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='humgrupo',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='hummotivoterminacion',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='humnovedad',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='humnovedadtipo',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='humpagotipo',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='humpension',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='humperiodo',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='humprogramacion',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='humprogramaciondetalle',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='humriesgo',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='humsalud',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='humsubtipocotizante',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='humsucursal',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='humtiempo',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='humtipocosto',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='humtipocotizante',
            options={'ordering': ['-id']},
        ),
    ]
