# Generated by Django 4.2.4 on 2025-06-27 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0005_alter_humadicional_options_alter_humaporte_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='humentidad',
            options={'ordering': ['id']},
        ),
    ]
