# Generated by Django 4.2.4 on 2024-07-29 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0005_humprogramacion_descuento_adicional_permanente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumProgramacionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diurna', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('nocturna', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('festiva_diurna', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('festiva_nocturna', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('extra_diurna', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('extra_nocturna', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('extra_festiva_diurna', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('extra_festiva_nocturna', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('recargo_nocturno', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('recargo_festivo_diurno', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('recargo_festivo_nocturno', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('pago_horas', models.BooleanField(default=True)),
                ('pago_auxilio_transporte', models.BooleanField(default=True)),
                ('pago_incapacidad', models.BooleanField(default=True)),
                ('pago_licencia', models.BooleanField(default=True)),
                ('pago_vacacion', models.BooleanField(default=True)),
                ('descuento_salud', models.BooleanField(default=True)),
                ('descuento_pension', models.BooleanField(default=True)),
                ('descuento_fondo_solidaridad', models.BooleanField(default=True)),
                ('descuento_retencion_fuente', models.BooleanField(default=True)),
                ('descuento_adicional_permanente', models.BooleanField(default=True)),
                ('descuento_adicional_programacion', models.BooleanField(default=True)),
                ('descuento_credito', models.BooleanField(default=True)),
                ('descuento_embargo', models.BooleanField(default=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pogramaciones_detalles_contrato_rel', to='humano.humcontrato')),
                ('programacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pogramaciones_detalles_programacion_rel', to='humano.humprogramacion')),
            ],
            options={
                'db_table': 'hum_programacion_detalle',
            },
        ),
    ]
