# Generated by Django 4.2.4 on 2025-06-27 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0006_alter_humentidad_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='humconcepto',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='humriesgo',
            options={'ordering': ['id']},
        ),
    ]
