# Generated by Django 4.2.4 on 2024-07-29 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0006_humprogramaciondetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='humcontrato',
            name='grupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_grupo_rel', to='humano.humgrupo'),
            preserve_default=False,
        ),
    ]
