# Generated by Django 4.2.4 on 2024-07-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0007_humcontrato_grupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumConcepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('porcentaje', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('ingreso_base_prestacion', models.BooleanField(default=False)),
                ('ingreso_base_cotizacion', models.BooleanField(default=False)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'hum_concepto',
            },
        ),
    ]
