# Generated by Django 4.2.4 on 2025-07-02 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0007_alter_humconcepto_options_alter_humriesgo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='humcontratotipo',
            options={'ordering': ['id']},
        ),
    ]
