# Generated by Django 4.2.4 on 2024-07-29 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0008_humconcepto'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('horas', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('aplica_dia_laborado', models.BooleanField(default=True)),
                ('detalle', models.CharField(max_length=200, null=True)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adicionales_concepto_rel', to='humano.humconcepto')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adicionales_contrato_rel', to='humano.humcontrato')),
                ('programacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adicionales_programacion_rel', to='humano.humprogramacion')),
            ],
            options={
                'db_table': 'hum_adicional',
            },
        ),
    ]
