# Generated by Django 4.2.4 on 2025-07-02 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0008_alter_humcontratotipo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='humpension',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='humsalud',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='humtiempo',
            options={'ordering': ['id']},
        ),
    ]
