# Generated by Django 4.2.4 on 2024-07-29 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0009_humadicional'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumNovedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='novedades_contrato_rel', to='humano.humcontrato')),
            ],
            options={
                'db_table': 'hum_novedad',
            },
        ),
    ]
