# Generated by Django 4.2.4 on 2024-07-29 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0010_humnovedad'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('total', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('cuota', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('cantidad_cuotas', models.IntegerField(default=0)),
                ('validar_cuotas', models.BooleanField(default=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creditos_contrato_rel', to='humano.humcontrato')),
            ],
            options={
                'db_table': 'hum_credito',
            },
        ),
    ]
