# Generated by Django 4.2.4 on 2025-07-03 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0012_alter_humconfiguracionprovision_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='humconfiguracionprovision',
            options={'ordering': ['orden']},
        ),
    ]
