# Generated by Django 4.2.4 on 2025-07-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0013_alter_humconfiguracionprovision_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='humliquidacion',
            name='dias_cesantia',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='humliquidacion',
            name='dias_prima',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='humliquidacion',
            name='dias_vacacion',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
