# Generated by Django 4.2.4 on 2024-08-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0014_humcargo_humsubtipocotizante_humtipocotizante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='humcargo',
            name='codigo',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
