# Generated by Django 4.2.4 on 2025-07-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0014_humliquidacion_dias_cesantia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='humliquidacion',
            name='salario',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
