# Generated by Django 4.2.4 on 2025-07-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0015_humliquidacion_salario'),
    ]

    operations = [
        migrations.AddField(
            model_name='humliquidacion',
            name='fecha_ultimo_pago',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='humliquidacion',
            name='fecha_ultimo_pago_cesantia',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='humliquidacion',
            name='fecha_ultimo_pago_prima',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='humliquidacion',
            name='fecha_ultimo_pago_vacacion',
            field=models.DateField(null=True),
        ),
    ]
