# Generated by Django 4.2.4 on 2025-07-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0016_humliquidacion_fecha_ultimo_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='humnovedad',
            name='detalle',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
