# Generated by Django 4.2.4 on 2024-08-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0016_humcargo_estado_inactivo_alter_humcargo_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='humsubtipocotizante',
            name='codigo',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='humtipocotizante',
            name='codigo',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
