# Generated by Django 4.2.4 on 2025-09-09 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0017_humnovedad_detalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumLiquidacionAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adicional', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('deduccion', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones_adicionales_liquidacion_rel', to='humano.humliquidacion')),
            ],
            options={
                'db_table': 'hum_liquidacion_adicional',
                'ordering': ['-id'],
            },
        ),
    ]
