# Generated by Django 4.2.4 on 2024-08-15 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0017_humsubtipocotizante_codigo_humtipocotizante_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humcontrato',
            name='cargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_cargo_rel', to='humano.humcargo'),
        ),
        migrations.AlterField(
            model_name='humcontrato',
            name='riesgo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_riesgo_rel', to='humano.humriesgo'),
        ),
        migrations.AlterField(
            model_name='humcontrato',
            name='subtipo_cotizante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_subtipo_cotizante_rel', to='humano.humsubtipocotizante'),
        ),
        migrations.AlterField(
            model_name='humcontrato',
            name='tipo_cotizante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_tipo_cotizante_rel', to='humano.humtipocotizante'),
        ),
    ]
