# Generated by Django 4.2.4 on 2025-09-10 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0018_humliquidacionadicional'),
    ]

    operations = [
        migrations.AddField(
            model_name='humliquidacionadicional',
            name='concepto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones_adicionales_concepto_rel', to='humano.humconcepto'),
            preserve_default=False,
        ),
    ]
