# Generated by Django 4.2.4 on 2024-08-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0018_alter_humcontrato_cargo_alter_humcontrato_riesgo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='humprogramaciondetalle',
            name='dias',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='humprogramaciondetalle',
            name='dias_transporte',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='humprogramaciondetalle',
            name='fecha_desde',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='humprogramaciondetalle',
            name='fecha_hasta',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='humprogramaciondetalle',
            name='neto',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='humprogramaciondetalle',
            name='salario',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
