# Generated by Django 4.2.4 on 2024-08-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0019_humprogramaciondetalle_dias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='humcontrato',
            name='fecha_ultimo_pago',
            field=models.DateField(null=True),
        ),
    ]
