# Generated by Django 4.2.4 on 2025-10-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0019_humliquidacionadicional_concepto'),
    ]

    operations = [
        migrations.AddField(
            model_name='humliquidacionadicional',
            name='detalle',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
