# Generated by Django 4.2.4 on 2024-08-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0020_humcontrato_fecha_ultimo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='humprogramaciondetalle',
            name='ingreso',
            field=models.BooleanField(default=False),
        ),
    ]
