# Generated by Django 4.2.4 on 2026-01-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0020_humliquidacionadicional_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='humprogramaciondetalle',
            name='prima_propuesto',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
