# Generated by Django 4.2.4 on 2026-01-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0022_humprogramaciondetalle_cesantia_propuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='humprogramaciondetalle',
            name='base_prestacion',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
