# Generated by Django 4.2.4 on 2026-01-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0023_humprogramaciondetalle_base_prestacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='humprogramacion',
            name='base_prestacion_minimo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='humprogramacion',
            name='base_prestacion_minimo_salario',
            field=models.BooleanField(default=True),
        ),
    ]
