# Generated by Django 4.2.4 on 2024-08-16 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0023_humpension_porcentaje_empleado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumConceptoNomina',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('concepto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conceptos_nomina_concepto_rel', to='humano.humconcepto')),
            ],
            options={
                'db_table': 'hum_concepto_nomina',
            },
        ),
    ]
