# Generated by Django 4.2.4 on 2026-01-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0024_humprogramacion_base_prestacion_minimo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='humprogramaciondetalle',
            name='interes_propuesto',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
