# Generated by Django 4.2.4 on 2024-08-16 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0024_humconceptonomina'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='humconceptonomina',
            options={'ordering': ['id']},
        ),
    ]
