# Generated by Django 4.2.4 on 2024-08-16 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0025_alter_humconceptonomina_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='humadicional',
            name='inactivo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='humadicional',
            name='inactivo_periodo',
            field=models.BooleanField(default=False),
        ),
    ]
