# Generated by Django 4.2.4 on 2024-08-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0026_humadicional_inactivo_humadicional_inactivo_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='humadicional',
            name='permanente',
            field=models.BooleanField(default=False),
        ),
    ]
