# Generated by Django 4.2.4 on 2024-08-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0027_humadicional_permanente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humadicional',
            name='aplica_dia_laborado',
            field=models.BooleanField(default=False),
        ),
    ]
