# Generated by Django 4.2.4 on 2024-08-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0028_alter_humadicional_aplica_dia_laborado'),
    ]

    operations = [
        migrations.AddField(
            model_name='humprogramacion',
            name='estado_generado',
            field=models.BooleanField(default=False),
        ),
    ]
