# Generated by Django 4.2.4 on 2024-08-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0029_humprogramacion_estado_generado'),
    ]

    operations = [
        migrations.AddField(
            model_name='humconcepto',
            name='operacion',
            field=models.BigIntegerField(default=0),
        ),
    ]
