# Generated by Django 4.2.4 on 2024-08-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0030_humconcepto_operacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='humprogramacion',
            name='descuento_adicional_permanente',
        ),
        migrations.RemoveField(
            model_name='humprogramacion',
            name='descuento_adicional_programacion',
        ),
        migrations.RemoveField(
            model_name='humprogramaciondetalle',
            name='descuento_adicional_permanente',
        ),
        migrations.RemoveField(
            model_name='humprogramaciondetalle',
            name='descuento_adicional_programacion',
        ),
        migrations.AddField(
            model_name='humprogramacion',
            name='adicional',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='humprogramaciondetalle',
            name='adicional',
            field=models.BooleanField(default=True),
        ),
    ]
