# Generated by Django 4.2.4 on 2024-08-19 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0031_remove_humprogramacion_descuento_adicional_permanente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='humpension',
            name='concepto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pensiones_concepto_rel', to='humano.humconcepto'),
        ),
        migrations.AddField(
            model_name='humsalud',
            name='concepto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='saludes_concepto_rel', to='humano.humconcepto'),
        ),
    ]
