# Generated by Django 4.2.4 on 2024-08-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0032_humpension_concepto_humsalud_concepto'),
    ]

    operations = [
        migrations.AddField(
            model_name='humsalud',
            name='porcentaje_empleado',
            field=models.DecimalField(decimal_places=3, default=4, max_digits=6),
        ),
    ]
