# Generated by Django 4.2.4 on 2024-08-19 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0035_humcredito_pagado_humcredito_saldo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumConceptoTipo',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'hum_concepto_tipo',
            },
        ),
        migrations.AddField(
            model_name='humconcepto',
            name='concepto_tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conceptos_concepto_tipo_rel', to='humano.humconceptotipo'),
        ),
    ]
