# Generated by Django 4.2.4 on 2024-08-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0038_humcredito_abono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='humprogramaciondetalle',
            name='neto',
        ),
        migrations.AddField(
            model_name='humprogramaciondetalle',
            name='deduccion',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='humprogramaciondetalle',
            name='devengado',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='humprogramaciondetalle',
            name='total',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
