# Generated by Django 4.2.4 on 2024-08-20 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0039_remove_humprogramaciondetalle_neto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='humprogramacion',
            name='neto',
        ),
        migrations.AddField(
            model_name='humprogramacion',
            name='total',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
