# Generated by Django 4.2.4 on 2024-08-20 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0040_remove_humprogramacion_neto_humprogramacion_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='humprogramacion',
            name='deduccion',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='humprogramacion',
            name='devengado',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
