# Generated by Django 4.2.4 on 2024-08-20 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0041_humprogramacion_deduccion_humprogramacion_devengado'),
    ]

    operations = [
        migrations.AddField(
            model_name='humcredito',
            name='cuota_actual',
            field=models.IntegerField(default=0),
        ),
    ]
