# Generated by Django 4.2.4 on 2024-08-20 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0131_gendocumentodetalle_credito'),
        ('humano', '0042_humcredito_cuota_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='humcontrato',
            name='ciudad_contrato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_ciudad_contrato_rel', to='general.genciudad'),
        ),
        migrations.AddField(
            model_name='humcontrato',
            name='ciudad_labora',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_ciudad_labora_rel', to='general.genciudad'),
        ),
    ]
