# Generated by Django 4.2.4 on 2024-08-21 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0043_humcontrato_ciudad_contrato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='humprogramaciondetalle',
            name='retiro',
            field=models.BooleanField(default=False),
        ),
    ]
