# Generated by Django 4.2.4 on 2024-08-22 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0044_humprogramaciondetalle_retiro'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumNovedadTipo',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('novedad_clase_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'hum_novedad_tipo',
            },
        ),
        migrations.AddField(
            model_name='humnovedad',
            name='novedad_tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='novedades_novedad_tipo_rel', to='humano.humnovedadtipo'),
        ),
    ]
