# Generated by Django 4.2.4 on 2024-08-23 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0045_humnovedadtipo_humnovedad_novedad_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='humconcepto',
            name='adicional',
            field=models.BooleanField(default=False),
        ),
    ]
