# Generated by Django 4.2.4 on 2024-08-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0048_humnovedadtipo_concepto'),
    ]

    operations = [
        migrations.AddField(
            model_name='humnovedad',
            name='pago_dia_disfrute',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
