# Generated by Django 4.2.4 on 2024-08-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0049_humnovedad_pago_dia_disfrute'),
    ]

    operations = [
        migrations.AddField(
            model_name='humnovedad',
            name='dias_dinero',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='humnovedad',
            name='dias_disfrutados',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
