# Generated by Django 4.2.4 on 2024-08-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0050_humnovedad_dias_dinero_humnovedad_dias_disfrutados'),
    ]

    operations = [
        migrations.AddField(
            model_name='humnovedad',
            name='fecha_desde_periodo',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='humnovedad',
            name='fecha_hasta_periodo',
            field=models.DateField(null=True),
        ),
    ]
