# Generated by Django 4.2.4 on 2024-08-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0051_humnovedad_fecha_desde_periodo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='humnovedad',
            name='pago_dinero',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='humnovedad',
            name='pago_disfrute',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
