# Generated by Django 4.2.4 on 2024-08-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0052_humnovedad_pago_dinero_humnovedad_pago_disfrute'),
    ]

    operations = [
        migrations.AddField(
            model_name='humnovedad',
            name='dias_disfrutados_reales',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
