# Generated by Django 4.2.4 on 2024-08-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0053_humnovedad_dias_disfrutados_reales'),
    ]

    operations = [
        migrations.AddField(
            model_name='humnovedad',
            name='pago_dia_dinero',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
