# Generated by Django 4.2.4 on 2024-08-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0055_humnovedadtipo_concepto2'),
    ]

    operations = [
        migrations.AddField(
            model_name='humnovedad',
            name='total',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
