# Generated by Django 4.2.4 on 2024-08-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0056_humnovedad_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='humnovedad',
            name='dias',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='humnovedad',
            name='dias_empresa',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='humnovedad',
            name='dias_entidad',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
