# Generated by Django 4.2.4 on 2024-08-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0057_humnovedad_dias_humnovedad_dias_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='humnovedad',
            name='base_cotizacion',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='humnovedad',
            name='base_cotizacion_propuesto',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='humnovedad',
            name='hora_empresa',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='humnovedad',
            name='hora_entidad',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='humnovedad',
            name='pago_empresa',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='humnovedad',
            name='pago_entidad',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
