# Generated by Django 4.2.4 on 2024-08-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0058_humnovedad_base_cotizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='humnovedad',
            name='fecha_desde_empresa',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='humnovedad',
            name='fecha_desde_entidad',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='humnovedad',
            name='fecha_hasta_empresa',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='humnovedad',
            name='fecha_hasta_entidad',
            field=models.DateField(null=True),
        ),
    ]
