# Generated by Django 4.2.4 on 2024-09-18 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0060_humperiodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='humgrupo',
            name='periodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grupos_periodo_rel', to='humano.humperiodo'),
        ),
        migrations.AddField(
            model_name='humperiodo',
            name='dias',
            field=models.IntegerField(default=0),
        ),
    ]
