# Generated by Django 4.2.4 on 2024-09-18 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0061_humgrupo_periodo_humperiodo_dias'),
    ]

    operations = [
        migrations.AddField(
            model_name='humprogramacion',
            name='periodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programaciones_periodo_rel', to='humano.humperiodo'),
        ),
    ]
