# Generated by Django 4.2.4 on 2024-09-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0062_humprogramacion_periodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumEntidad',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20)),
                ('numero_identificacion', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('salud', models.BooleanField(default=False)),
                ('pension', models.BooleanField(default=False)),
                ('cesantias', models.BooleanField(default=False)),
                ('caja', models.BooleanField(default=False)),
                ('riesgo', models.BooleanField(default=False)),
                ('sena', models.BooleanField(default=False)),
                ('icbf', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'hum_entidad',
            },
        ),
    ]
