# Generated by Django 4.2.4 on 2024-09-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0064_humcontrato_entidad_caja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='humentidad',
            name='nombre_extendido',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
