# Generated by Django 4.2.4 on 2024-10-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0065_humentidad_nombre_extendido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humcargo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
