# Generated by Django 4.2.4 on 2024-11-06 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0067_humaporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumAporteContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('dias', models.IntegerField(default=0)),
                ('salario', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('base_cotizacion', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('estado_aprobado', models.BooleanField(default=False)),
                ('estado_generado', models.BooleanField(default=False)),
                ('aporte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aportes_contratos_aporte_rel', to='humano.humaporte')),
            ],
            options={
                'db_table': 'hum_aporte_contrato',
            },
        ),
    ]
