# Generated by Django 4.2.4 on 2024-11-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0068_humaportecontrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humaporte',
            name='fecha_desde',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='humaporte',
            name='fecha_hasta',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='humaporte',
            name='fecha_hasta_periodo',
            field=models.DateField(null=True),
        ),
    ]
