# Generated by Django 4.2.4 on 2024-11-06 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0069_alter_humaporte_fecha_desde_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='humaportecontrato',
            name='contrato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aportes_contratos_contrato_rel', to='humano.humcontrato'),
        ),
    ]
