# Generated by Django 4.2.4 on 2024-11-06 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0070_humaportecontrato_contrato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='humaportecontrato',
            name='estado_aprobado',
        ),
        migrations.RemoveField(
            model_name='humaportecontrato',
            name='estado_generado',
        ),
    ]
