# Generated by Django 4.2.4 on 2024-11-06 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0071_remove_humaportecontrato_estado_aprobado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='humaportecontrato',
            name='cantidad',
        ),
    ]
