# Generated by Django 4.2.4 on 2025-01-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0073_humprogramaciondetalle_salario_promedio'),
    ]

    operations = [
        migrations.AddField(
            model_name='humcredito',
            name='comentario',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
