# Generated by Django 4.2.4 on 2025-01-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0075_humprogramaciondetalle_error_terminacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humadicional',
            name='detalle',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
