# Generated by Django 4.2.4 on 2025-01-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0076_alter_humadicional_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='humaportecontrato',
            name='error_terminacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='humaportecontrato',
            name='fecha_desde',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='humaportecontrato',
            name='fecha_hasta',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='humaportecontrato',
            name='ingreso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='humaportecontrato',
            name='retiro',
            field=models.BooleanField(default=False),
        ),
    ]
