# Generated by Django 4.2.4 on 2025-01-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0078_humaportedetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='humaportedetalle',
            name='ingreso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='retiro',
            field=models.BooleanField(default=False),
        ),
    ]
