# Generated by Django 4.2.4 on 2025-01-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0079_humaportedetalle_ingreso_humaportedetalle_retiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='humaporte',
            name='presentacion',
            field=models.CharField(default='S', max_length=1),
        ),
    ]
