# Generated by Django 4.2.4 on 2025-01-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0081_humaporte_entidad_riesgo'),
    ]

    operations = [
        migrations.AddField(
            model_name='humaporte',
            name='base_cotizacion',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
