# Generated by Django 4.2.4 on 2025-01-29 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0168_genidentificacion_aporte'),
        ('humano', '0082_humaporte_base_cotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='humaportecontrato',
            name='ciudad_labora',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_ciudad_labora_rel', to='general.genciudad'),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='suspension_temporal_contrato',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='variacion_permanente_salario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='variacion_transitoria_salario',
            field=models.BooleanField(default=False),
        ),
    ]
