# Generated by Django 4.2.4 on 2025-01-29 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0168_genidentificacion_aporte'),
        ('humano', '0083_humaportecontrato_ciudad_labora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humaportecontrato',
            name='ciudad_labora',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aportes_contratos_ciudad_labora_rel', to='general.genciudad'),
        ),
    ]
