# Generated by Django 4.2.4 on 2025-01-29 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0084_alter_humaportecontrato_ciudad_labora'),
    ]

    operations = [
        migrations.AddField(
            model_name='humaportecontrato',
            name='entidad_caja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aportes_contratos_entidad_caja_rel', to='humano.humentidad'),
        ),
        migrations.AddField(
            model_name='humaportecontrato',
            name='entidad_pension',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aportes_contratos_entidad_pension_rel', to='humano.humentidad'),
        ),
        migrations.AddField(
            model_name='humaportecontrato',
            name='entidad_salud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aportes_contratos_entidad_salud_rel', to='humano.humentidad'),
        ),
        migrations.AddField(
            model_name='humaportecontrato',
            name='riesgo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_riesgo_rel', to='humano.humriesgo'),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='aporte_solidaridad_solidaridad',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='aporte_solidaridad_subsistencia',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='aporte_voluntario_pension',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='aporte_voluntario_pension_afiliado',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='aporte_voluntario_pension_aportante',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='base_cotizacion_caja',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='base_cotizacion_otros_parafiscales',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='base_cotizacion_pension',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='base_cotizacion_riesgos',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='base_cotizacion_salud',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='cotizacion_caja',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='cotizacion_icbf',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='cotizacion_pension',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='cotizacion_riesgos',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='cotizacion_salud',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='cotizacion_sena',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='dias_caja',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='dias_incapacidad_laboral',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='dias_pension',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='dias_riesgos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='dias_salud',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='fecha_fin_incapacidad_general',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='fecha_fin_incapacidad_laboral',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='fecha_fin_licencia_maternidad',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='fecha_fin_suspension_temporal_contrato',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='fecha_fin_vacaciones',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='fecha_ingreso',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='fecha_inicio_incapacidad_general',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='fecha_inicio_incapacidad_laboral',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='fecha_inicio_licencia_maternidad',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='fecha_inicio_suspension_temporal_contrato',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='fecha_inicio_vacaciones',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='fecha_inicio_variacion_permanente_salario',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='fecha_retiro',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='horas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='incapacidad_general',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='licencia_maternidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='licencia_remunerada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='salario_integral',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='tarifa_caja',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='tarifa_icbf',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='tarifa_pension',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='tarifa_riesgos',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='tarifa_salud',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='tarifa_sena',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='total_cotizacion_pension',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='upc_adicional',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='vacaciones',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='humaportedetalle',
            name='variacion_centro_trabajo',
            field=models.BooleanField(default=False),
        ),
    ]
