# Generated by Django 4.2.4 on 2025-01-29 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0085_humaportecontrato_entidad_caja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humaportecontrato',
            name='riesgo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aportes_contratos_riesgo_rel', to='humano.humriesgo'),
        ),
    ]
