# Generated by Django 4.2.4 on 2025-01-29 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0086_alter_humaportecontrato_riesgo'),
    ]

    operations = [
        migrations.AddField(
            model_name='humaportedetalle',
            name='cotizacion_total',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
