# Generated by Django 4.2.4 on 2025-01-30 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0087_humaportedetalle_cotizacion_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='humaportedetalle',
            old_name='aporte_solidaridad_solidaridad',
            new_name='cotizacion_solidaridad_solidaridad',
        ),
        migrations.RenameField(
            model_name='humaportedetalle',
            old_name='aporte_solidaridad_subsistencia',
            new_name='cotizacion_solidaridad_subsistencia',
        ),
        migrations.RenameField(
            model_name='humaportedetalle',
            old_name='aporte_voluntario_pension_afiliado',
            new_name='cotizacion_voluntario_pension_afiliado',
        ),
        migrations.RenameField(
            model_name='humaportedetalle',
            old_name='aporte_voluntario_pension_aportante',
            new_name='cotizacion_voluntario_pension_aportante',
        ),
    ]
