# Generated by Django 4.2.4 on 2025-01-30 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0088_rename_aporte_solidaridad_solidaridad_humaportedetalle_cotizacion_solidaridad_solidaridad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='humaporte',
            old_name='caja',
            new_name='cotizacion_caja',
        ),
        migrations.RenameField(
            model_name='humaporte',
            old_name='icbf',
            new_name='cotizacion_icbf',
        ),
        migrations.RenameField(
            model_name='humaporte',
            old_name='pension',
            new_name='cotizacion_pension',
        ),
        migrations.RenameField(
            model_name='humaporte',
            old_name='riesgo',
            new_name='cotizacion_riesgos',
        ),
        migrations.RenameField(
            model_name='humaporte',
            old_name='salud',
            new_name='cotizacion_salud',
        ),
        migrations.RenameField(
            model_name='humaporte',
            old_name='sena',
            new_name='cotizacion_sena',
        ),
        migrations.RenameField(
            model_name='humaporte',
            old_name='fondo_solidaridad',
            new_name='cotizacion_solidaridad_solidaridad',
        ),
        migrations.RenameField(
            model_name='humaporte',
            old_name='fondo_subsistencia',
            new_name='cotizacion_solidaridad_subsistencia',
        ),
        migrations.RenameField(
            model_name='humaporte',
            old_name='total',
            new_name='cotizacion_total',
        ),
        migrations.AddField(
            model_name='humaporte',
            name='cotizacion_voluntario_pension_afiliado',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='humaporte',
            name='cotizacion_voluntario_pension_aportante',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
