# Generated by Django 4.2.4 on 2025-01-31 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0089_rename_caja_humaporte_cotizacion_caja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='humsucursal',
            name='codigo',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
