# Generated by Django 4.2.4 on 2025-02-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0091_humcredito_aplica_cesantia_humcredito_aplica_prima'),
    ]

    operations = [
        migrations.AddField(
            model_name='humprogramacion',
            name='pago_cesantia',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='humprogramacion',
            name='pago_interes',
            field=models.BooleanField(default=True),
        ),
    ]
