# Generated by Django 4.2.4 on 2025-02-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0092_humprogramacion_pago_cesantia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='humcontrato',
            name='fecha_ultimo_pago_cesantia',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='humcontrato',
            name='fecha_ultimo_pago_prima',
            field=models.DateField(null=True),
        ),
    ]
