# Generated by Django 4.2.4 on 2025-02-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0093_humcontrato_fecha_ultimo_pago_cesantia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='humprogramacion',
            name='pago_prima',
            field=models.BooleanField(default=True),
        ),
    ]
