# Generated by Django 4.2.4 on 2025-02-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0094_humprogramacion_pago_prima'),
    ]

    operations = [
        migrations.AddField(
            model_name='humnovedad',
            name='dias_acumulados',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
