# Generated by Django 4.2.4 on 2025-02-03 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0095_humnovedad_dias_acumulados'),
    ]

    operations = [
        migrations.AddField(
            model_name='humnovedad',
            name='novedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='novedades_novedad_rel', to='humano.humnovedad'),
        ),
    ]
