# Generated by Django 4.2.4 on 2025-02-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0096_humnovedad_novedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='humnovedad',
            name='prorroga',
            field=models.BooleanField(default=False),
        ),
    ]
