# Generated by Django 4.2.4 on 2025-02-04 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0097_humnovedad_prorroga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='humnovedad',
            name='novedad',
        ),
        migrations.AddField(
            model_name='humnovedad',
            name='novedad_referencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='novedades_novedad_referencia_rel', to='humano.humnovedad'),
        ),
    ]
