# Generated by Django 4.2.4 on 2025-02-04 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0098_remove_humnovedad_novedad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='humaporte',
            name='entidad_icbf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aportes_entidad_icbf_rel', to='humano.humentidad'),
        ),
        migrations.AddField(
            model_name='humaporte',
            name='entidad_sena',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aportes_entidad_sena_rel', to='humano.humentidad'),
        ),
        migrations.AlterField(
            model_name='humaporte',
            name='entidad_riesgo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aportes_entidad_riesgo_rel', to='humano.humentidad'),
        ),
    ]
