# Generated by Django 4.2.4 on 2025-02-04 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0099_humaporte_entidad_icbf_humaporte_entidad_sena_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumAporteEntidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('cotizacion', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('aporte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aportes_entidades_aporte_rel', to='humano.humaporte')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aportes_entidades_entidad_rel', to='humano.humentidad')),
            ],
            options={
                'db_table': 'hum_aporte_entidad',
            },
        ),
    ]
