# Generated by Django 4.2.4 on 2025-02-12 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0101_humtiempo_humcontrato_tiempo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='humtiempo',
            name='factor',
        ),
    ]
