# Generated by Django 4.2.4 on 2025-02-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0102_remove_humtiempo_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='humcontrato',
            name='fecha_ultimo_pago_vacacion',
            field=models.DateField(null=True),
        ),
    ]
