# Generated by Django 4.2.4 on 2025-03-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0103_humcontrato_fecha_ultimo_pago_vacacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='humprogramaciondetalle',
            name='base_cotizacion_acumulado',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='humprogramaciondetalle',
            name='deduccion_fondo_pension_acumulado',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
