# Generated by Django 4.2.4 on 2025-03-06 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0032_alter_conmovimiento_base'),
        ('humano', '0105_humtipocosto_humcontrato_tipo_costo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='humpagotipo',
            name='consecutivo',
        ),
        migrations.AddField(
            model_name='humpagotipo',
            name='cuenta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_tipos_cuenta_rel', to='contabilidad.concuenta'),
        ),
    ]
