# Generated by Django 4.2.4 on 2025-03-06 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0032_alter_conmovimiento_base'),
        ('humano', '0106_remove_humpagotipo_consecutivo_humpagotipo_cuenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumConceptoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conceptos_cuentas_concepto_rel', to='humano.humconcepto')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conceptos_cuentas_cuenta_rel', to='contabilidad.concuenta')),
            ],
            options={
                'db_table': 'hum_concepto_cuenta',
            },
        ),
    ]
