# Generated by Django 4.2.4 on 2025-03-06 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0107_humconceptocuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='humconceptocuenta',
            name='tipo_costo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='conceptos_cuentas_tipo_costo_rel', to='humano.humtipocosto'),
            preserve_default=False,
        ),
    ]
