# Generated by Django 4.2.4 on 2025-03-07 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0108_humconceptocuenta_tipo_costo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='humpagotipo',
            name='cuenta',
        ),
    ]
