# Generated by Django 4.2.4 on 2025-03-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0111_alter_humconfiguracionprovision_cuenta_credito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='humconcepto',
            name='ingreso_base_prestacion_vacacion',
            field=models.BooleanField(default=False),
        ),
    ]
