# Generated by Django 4.2.4 on 2025-03-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0112_humconcepto_ingreso_base_prestacion_vacacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='humaportecontrato',
            name='pension_empleado',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='humaportecontrato',
            name='salud_empleado',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
