# Generated by Django 4.2.4 on 2025-03-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0113_humaportecontrato_pension_empleado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='humaportecontrato',
            name='pension_empresa',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='humaportecontrato',
            name='salud_empresa',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
