# Generated by Django 4.2.4 on 2025-03-08 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0114_humaportecontrato_pension_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='humaportecontrato',
            name='entidad_riesgo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aportes_contratos_entidad_riesgo_rel', to='humano.humentidad'),
        ),
    ]
