# Generated by Django 4.2.4 on 2025-03-08 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0115_humaportecontrato_entidad_riesgo'),
    ]

    operations = [
        migrations.AddField(
            model_name='humaportecontrato',
            name='entidad_icbf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aportes_contratos_entidad_icbf_rel', to='humano.humentidad'),
        ),
        migrations.AddField(
            model_name='humaportecontrato',
            name='entidad_sena',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aportes_contratos_entidad_sena_rel', to='humano.humentidad'),
        ),
    ]
