# Generated by Django 4.2.4 on 2025-03-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0116_humaportecontrato_entidad_icbf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='humaportecontrato',
            name='cotizacion_caja',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='humaportecontrato',
            name='cotizacion_icbf',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='humaportecontrato',
            name='cotizacion_pension',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='humaportecontrato',
            name='cotizacion_riesgos',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='humaportecontrato',
            name='cotizacion_salud',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='humaportecontrato',
            name='cotizacion_sena',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='humaportecontrato',
            name='cotizacion_solidaridad_solidaridad',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='humaportecontrato',
            name='cotizacion_solidaridad_subsistencia',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='humaportecontrato',
            name='cotizacion_total',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='humaportecontrato',
            name='cotizacion_voluntario_pension_afiliado',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='humaportecontrato',
            name='cotizacion_voluntario_pension_aportante',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
