# Generated by Django 4.2.4 on 2025-03-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0118_humaportecontrato_cotizacion_pension_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='humaporte',
            name='cotizacion_pension_total',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
