# Generated by Django 4.2.4 on 2025-03-08 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0032_alter_conmovimiento_base'),
        ('humano', '0119_humaporte_cotizacion_pension_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumConfiguracionAporte',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('cuenta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuraciones_aportes_cuenta_rel', to='contabilidad.concuenta')),
            ],
            options={
                'db_table': 'hum_configuracion_aporte',
            },
        ),
    ]
