# Generated by Django 4.2.4 on 2025-03-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0120_humconfiguracionaporte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='humaportecontrato',
            old_name='pension_empleado',
            new_name='cotizacion_pension_empleado',
        ),
        migrations.RenameField(
            model_name='humaportecontrato',
            old_name='pension_empresa',
            new_name='cotizacion_pension_empresa',
        ),
        migrations.RenameField(
            model_name='humaportecontrato',
            old_name='salud_empleado',
            new_name='cotizacion_salud_empleado',
        ),
        migrations.RenameField(
            model_name='humaportecontrato',
            old_name='salud_empresa',
            new_name='cotizacion_salud_empresa',
        ),
        migrations.AddField(
            model_name='humaporte',
            name='cotizacion_pension_empleado',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='humaporte',
            name='cotizacion_pension_empresa',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='humaporte',
            name='cotizacion_salud_empresa',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
