# Generated by Django 4.2.4 on 2025-03-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0121_rename_pension_empleado_humaportecontrato_cotizacion_pension_empleado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='humaporte',
            name='cotizacion_salud_empleado',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
