# Generated by Django 4.2.4 on 2025-03-10 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0032_alter_conmovimiento_base'),
        ('humano', '0122_humaporte_cotizacion_salud_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='humcontrato',
            name='grupo_contabilidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_grupo_contabilidad_rel', to='contabilidad.congrupo'),
        ),
    ]
