# Generated by Django 4.2.4 on 2025-03-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0123_humcontrato_grupo_contabilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='humprogramacion',
            name='dias_reales',
            field=models.IntegerField(default=0),
        ),
    ]
