# Generated by Django 4.2.4 on 2025-03-26 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0124_humprogramacion_dias_reales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='humadicional',
            name='inactivo_periodo',
        ),
        migrations.RemoveField(
            model_name='humcredito',
            name='inactivo_periodo',
        ),
    ]
