# Generated by Django 4.2 on 2023-07-05 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0015_movimientoimpuesto'),
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='movimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='con_movimientos', to='general.movimiento'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='contacto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='con_movimientos', to='general.contacto'),
        ),
    ]
