# Generated by Django 4.2.4 on 2025-05-30 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(null=True)),
                ('fecha_salida', models.DateTimeField(null=True)),
                ('fecha_ubicacion', models.DateTimeField(null=True)),
                ('peso', models.FloatField(default=0)),
                ('volumen', models.FloatField(default=0)),
                ('tiempo_servicio', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('tiempo_trayecto', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('tiempo', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('visitas', models.FloatField(default=0)),
                ('visitas_entregadas', models.FloatField(default=0)),
                ('visitas_liberadas', models.FloatField(default=0)),
                ('visitas_novedad', models.FloatField(default=0)),
                ('estado_aprobado', models.BooleanField(default=False)),
                ('estado_terminado', models.BooleanField(default=False)),
                ('estado_anulado', models.BooleanField(default=False)),
                ('entrega_id', models.IntegerField(null=True)),
                ('latitud', models.DecimalField(decimal_places=15, max_digits=25, null=True)),
                ('longitud', models.DecimalField(decimal_places=15, max_digits=25, null=True)),
            ],
            options={
                'db_table': 'rut_despacho',
            },
        ),
        migrations.CreateModel(
            name='RutFranja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, null=True)),
                ('nombre', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=8, null=True)),
                ('coordenadas', models.JSONField(null=True)),
            ],
            options={
                'db_table': 'rut_franja',
            },
        ),
        migrations.CreateModel(
            name='RutNovedadTipo',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'rut_novedad_tipo',
            },
        ),
        migrations.CreateModel(
            name='RutVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(null=True)),
                ('guia', models.IntegerField(null=True)),
                ('fecha', models.DateTimeField(null=True)),
                ('fecha_entrega', models.DateTimeField(null=True)),
                ('documento', models.CharField(max_length=30, null=True)),
                ('destinatario', models.CharField(default='Destinatario', max_length=150)),
                ('destinatario_direccion', models.CharField(default='', max_length=150)),
                ('destinatario_direccion_formato', models.CharField(default='', max_length=150, null=True)),
                ('destinatario_telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('destinatario_correo', models.CharField(blank=True, max_length=255, null=True)),
                ('peso', models.FloatField(default=0)),
                ('volumen', models.FloatField(default=0)),
                ('tiempo_servicio', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('tiempo_trayecto', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('tiempo', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('latitud', models.DecimalField(decimal_places=15, max_digits=25, null=True)),
                ('longitud', models.DecimalField(decimal_places=15, max_digits=25, null=True)),
                ('estado_decodificado', models.BooleanField(default=None, null=True)),
                ('estado_decodificado_alerta', models.BooleanField(default=False)),
                ('estado_franja', models.BooleanField(default=None, null=True)),
                ('estado_despacho', models.BooleanField(default=False)),
                ('estado_entregado', models.BooleanField(default=False)),
                ('estado_entregado_complemento', models.BooleanField(default=False)),
                ('estado_novedad', models.BooleanField(default=False)),
                ('estado_devolucion', models.BooleanField(default=False)),
                ('orden', models.IntegerField(default=0)),
                ('distancia', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('resultados', models.JSONField(blank=True, null=True)),
                ('franja_id', models.IntegerField(null=True)),
                ('franja_codigo', models.CharField(max_length=20, null=True)),
                ('ciudad', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visitas_ciudad_rel', to='general.genciudad')),
                ('despacho', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visitas_despacho_rel', to='ruteo.rutdespacho')),
            ],
            options={
                'db_table': 'rut_visita',
            },
        ),
        migrations.CreateModel(
            name='RutVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, null=True)),
                ('capacidad', models.FloatField(default=0)),
                ('tiempo', models.FloatField(default=0)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('estado_activo', models.BooleanField(default=False)),
                ('estado_asignado', models.BooleanField(default=False)),
                ('usuario_app', models.CharField(max_length=255, null=True)),
                ('franjas', models.ManyToManyField(to='ruteo.rutfranja')),
            ],
            options={
                'db_table': 'rut_vehiculo',
            },
        ),
        migrations.CreateModel(
            name='RutUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('latitud', models.DecimalField(decimal_places=15, max_digits=25)),
                ('longitud', models.DecimalField(decimal_places=15, max_digits=25)),
                ('usuario_id', models.IntegerField(null=True)),
                ('detenido', models.IntegerField(default=0)),
                ('despacho', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ubicaciones_despacho_rel', to='ruteo.rutdespacho')),
                ('visita', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ubicaciones_visita_rel', to='ruteo.rutvisita')),
            ],
            options={
                'db_table': 'rut_ubicacion',
            },
        ),
        migrations.CreateModel(
            name='RutNovedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_solucion', models.DateTimeField(null=True)),
                ('descripcion', models.CharField(max_length=255, null=True)),
                ('solucion', models.CharField(max_length=255, null=True)),
                ('estado_solucion', models.BooleanField(default=False)),
                ('novedad_tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='novedades_novedad_tipo_rel', to='ruteo.rutnovedadtipo')),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novedades_visita_rel', to='ruteo.rutvisita')),
            ],
            options={
                'db_table': 'rut_novedad',
            },
        ),
        migrations.CreateModel(
            name='RutFlota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flotas_vehiculo_rel', to='ruteo.rutvehiculo')),
            ],
            options={
                'db_table': 'rut_flota',
            },
        ),
        migrations.AddField(
            model_name='rutdespacho',
            name='vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='despachos_vehiculo_rel', to='ruteo.rutvehiculo'),
        ),
    ]
