# Generated by Django 4.2.4 on 2025-06-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutflota',
            name='prioridad',
        ),
        migrations.AddField(
            model_name='rutvehiculo',
            name='prioridad',
            field=models.IntegerField(null=True),
        ),
    ]
