# Generated by Django 4.2.4 on 2025-06-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0002_rutvehiculo_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutflota',
            name='prioridad',
            field=models.IntegerField(null=True),
        ),
    ]
