# Generated by Django 4.2.4 on 2024-07-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0002_rutguia_guia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutguia',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
