# Generated by Django 4.2.4 on 2025-06-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0003_rutflota_prioridad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rutfranja',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterField(
            model_name='rutvisita',
            name='tiempo',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='rutvisita',
            name='tiempo_servicio',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='rutvisita',
            name='tiempo_trayecto',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
    ]
