# Generated by Django 4.2.4 on 2024-07-08 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0003_alter_rutguia_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rutguia',
            old_name='destinatarioCorreo',
            new_name='destinatario_correo',
        ),
        migrations.RenameField(
            model_name='rutguia',
            old_name='destinatarioDireccion',
            new_name='destinatario_direccion',
        ),
        migrations.RenameField(
            model_name='rutguia',
            old_name='destinatarioTelefono',
            new_name='destinatario_telefono',
        ),
    ]
