# Generated by Django 4.2.4 on 2025-06-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0004_alter_rutfranja_options_alter_rutvisita_tiempo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutdespacho',
            name='tiempo',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='rutdespacho',
            name='tiempo_servicio',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='rutdespacho',
            name='tiempo_trayecto',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
    ]
