# Generated by Django 4.2.4 on 2024-07-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0005_rutvehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutguia',
            name='decodificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rutguia',
            name='decodificado_error',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rutguia',
            name='latitud',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='rutguia',
            name='longitud',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
