# Generated by Django 4.2.4 on 2025-06-11 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0005_alter_rutdespacho_tiempo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rutdespacho',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='rutflota',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='rutnovedad',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='rutnovedadtipo',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='rutubicacion',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='rutvehiculo',
            options={'ordering': ['-id']},
        ),
    ]
