# Generated by Django 4.2.4 on 2025-06-14 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0006_alter_rutdespacho_options_alter_rutflota_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutvisita',
            name='datos_entrega',
            field=models.JSONField(blank=True, default=dict, help_text='Datos de la entrega (nombre, identificación, teléfono, etc.)', null=True),
        ),
    ]
