# Generated by Django 4.2.4 on 2024-07-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0006_rutguia_decodificado_rutguia_decodificado_error_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutFranja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('coordenadas', models.JSONField()),
            ],
            options={
                'db_table': 'rut_franja',
            },
        ),
    ]
