# Generated by Django 4.2.4 on 2025-07-04 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0007_rutvisita_datos_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutnovedad',
            name='nuevo_complemento',
            field=models.BooleanField(default=False),
        ),
    ]
