# Generated by Django 4.2.4 on 2025-07-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0008_rutnovedad_nuevo_complemento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutvisita',
            name='destinatario_direccion',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='rutvisita',
            name='destinatario_direccion_formato',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
