# Generated by Django 4.2.4 on 2025-07-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0008_rutnovedad_nuevo_complemento'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutnovedad',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='rutnovedad',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
