# Generated by Django 4.2.4 on 2025-07-07 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0009_alter_rutvisita_destinatario_direccion_and_more'),
        ('ruteo', '0009_rutnovedad_fecha_registro_alter_rutnovedad_fecha'),
    ]

    operations = [
    ]
