# Generated by Django 4.2.4 on 2024-07-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0009_rutvisita_ciudad_rutvisita_estado_rutvisita_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutvehiculo',
            name='latitud',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='rutvehiculo',
            name='longitud',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
