# Generated by Django 4.2.4 on 2025-07-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0010_merge_20250707_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutvehiculo',
            name='placa',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
