# Generated by Django 4.2.4 on 2024-07-11 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0010_rutvehiculo_latitud_rutvehiculo_longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutvisita',
            name='orden',
            field=models.IntegerField(default=0),
        ),
    ]
