# Generated by Django 4.2.4 on 2025-07-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0011_alter_rutvehiculo_placa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutvisita',
            name='distancia',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
    ]
