# Generated by Django 4.2.4 on 2024-07-11 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0011_rutvisita_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutvisita',
            name='distancia_proxima',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
