# Generated by Django 4.2.4 on 2025-07-24 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0012_alter_rutvisita_distancia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutvisita',
            name='guia',
        ),
        migrations.AddField(
            model_name='rutvisita',
            name='cobro',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
