# Generated by Django 4.2.4 on 2024-07-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0012_rutvisita_distancia_proxima'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutvisita',
            name='distancia_proxima',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, null=True),
        ),
    ]
