# Generated by Django 4.2.4 on 2025-08-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0013_remove_rutvisita_guia_rutvisita_cobro'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutdespacho',
            name='codigo_complemento',
            field=models.IntegerField(null=True),
        ),
    ]
