# Generated by Django 4.2.4 on 2024-07-16 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0013_alter_rutvisita_distancia_proxima'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutvisita',
            name='estado_despacho',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RutDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField(default=0)),
                ('volumen', models.FloatField(default=0)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despachos_vehiculo_rel', to='ruteo.rutvehiculo')),
            ],
            options={
                'db_table': 'rut_despacho',
            },
        ),
    ]
