# Generated by Django 4.2.4 on 2025-08-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0014_rutdespacho_codigo_complemento'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutvisita',
            name='remitente',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='rutvisita',
            name='unidades',
            field=models.FloatField(default=0),
        ),
    ]
