# Generated by Django 4.2.4 on 2024-07-16 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0014_rutvisita_estado_despacho_rutdespacho'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutdespacho',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='rutvisita',
            name='despacho',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visitas_despacho_rel', to='ruteo.rutdespacho'),
        ),
        migrations.AlterField(
            model_name='rutdespacho',
            name='vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='despachos_vehiculo_rel', to='ruteo.rutvehiculo'),
        ),
    ]
