# Generated by Django 4.2.4 on 2025-09-06 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0015_rutvisita_remitente_rutvisita_unidades'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutSeguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.CharField(max_length=500, null=True)),
                ('despacho', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seguimientos_despacho_rel', to='ruteo.rutdespacho')),
            ],
            options={
                'db_table': 'rut_seguimiento',
            },
        ),
    ]
