# Generated by Django 4.2.4 on 2024-07-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0015_rutdespacho_fecha_rutvisita_despacho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutdespacho',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
    ]
