# Generated by Django 4.2.4 on 2025-09-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0016_rutseguimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutseguimiento',
            name='usuario_id',
            field=models.IntegerField(null=True),
        ),
    ]
