# Generated by Django 4.2.4 on 2025-09-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0017_rutseguimiento_usuario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutdespacho',
            name='unidades',
            field=models.FloatField(default=0),
        ),
    ]
