# Generated by Django 4.2.4 on 2026-01-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0018_rutdespacho_unidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutvehiculo',
            name='placa',
            field=models.CharField(error_messages={'unique': 'Ya existe un vehículo registrado con esta placa.'}, max_length=10, unique=True),
        ),
    ]
