# Generated by Django 4.2.4 on 2024-08-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0019_rutvehiculo_estado_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutfranja',
            name='codigo',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
