# Generated by Django 4.2.4 on 2026-01-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0019_alter_rutvehiculo_placa'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutnovedad',
            name='movil_token',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
