# Generated by Django 4.2.4 on 2024-08-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0020_rutfranja_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutvisita',
            name='latitud',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='rutvisita',
            name='longitud',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
    ]
