# Generated by Django 4.2.4 on 2024-08-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0021_alter_rutvisita_latitud_alter_rutvisita_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutvisita',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
    ]
