# Generated by Django 4.2.4 on 2024-08-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0022_alter_rutvisita_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutfranja',
            name='codigo',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rutfranja',
            name='coordenadas',
            field=models.JSONField(null=True),
        ),
    ]
