# Generated by Django 4.2.4 on 2024-08-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0023_alter_rutfranja_codigo_alter_rutfranja_coordenadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutfranja',
            name='color',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
