# Generated by Django 4.2.4 on 2024-08-24 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0024_rutfranja_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutvisita',
            name='franja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visitas_franja_rel', to='ruteo.rutfranja'),
        ),
    ]
