# Generated by Django 4.2.4 on 2024-08-24 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0025_rutvisita_franja'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutvisita',
            name='estado_franja',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
