# Generated by Django 4.2.4 on 2024-08-25 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0135_alter_gencomplemento_datos_json'),
        ('ruteo', '0027_remove_rutvisita_decodificado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutvisita',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='rutvisita',
            name='pais',
        ),
        migrations.AlterField(
            model_name='rutvisita',
            name='ciudad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visitas_ciudad_rel', to='general.genciudad'),
        ),
    ]
