# Generated by Django 4.2.4 on 2024-10-28 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0147_gendocumento_impuesto_operado_and_more'),
        ('ruteo', '0028_remove_rutvisita_estado_remove_rutvisita_pais_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutvisita',
            name='ciudad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='visitas_ciudad_rel', to='general.genciudad'),
        ),
        migrations.AlterField(
            model_name='rutvisita',
            name='destinatario',
            field=models.CharField(default='Destinatario', max_length=150),
        ),
        migrations.AlterField(
            model_name='rutvisita',
            name='destinatario_direccion',
            field=models.CharField(default='', max_length=150),
        ),
    ]
