# Generated by Django 4.2.4 on 2024-11-15 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0151_gendocumentodetalle_tipo_registro'),
        ('ruteo', '0030_rutflota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutvisita',
            name='ciudad',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visitas_ciudad_rel', to='general.genciudad'),
        ),
    ]
