# Generated by Django 4.2.4 on 2024-11-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0031_alter_rutvisita_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutvisita',
            name='destinatario_direccion_formato',
            field=models.CharField(default='', max_length=150, null=True),
        ),
    ]
