# Generated by Django 4.2.4 on 2024-11-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0033_alter_rutvisita_latitud_alter_rutvisita_longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutvisita',
            name='estado_decodificado_alerta',
            field=models.BooleanField(default=False),
        ),
    ]
