# Generated by Django 4.2.4 on 2024-11-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0035_rutvisita_numero_rutvisita_tiempo_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutvisita',
            name='latitud',
            field=models.DecimalField(decimal_places=15, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='rutvisita',
            name='longitud',
            field=models.DecimalField(decimal_places=15, max_digits=25, null=True),
        ),
    ]
