# Generated by Django 4.2.4 on 2024-11-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0037_rutvisita_resultados'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutdespacho',
            name='estado_aprobado',
            field=models.BooleanField(default=False),
        ),
    ]
