# Generated by Django 4.2.4 on 2024-11-29 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0038_rutdespacho_estado_aprobado'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutvehiculo',
            name='franja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos_franja_rel', to='ruteo.rutfranja'),
        ),
    ]
