# Generated by Django 4.2.4 on 2024-12-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0039_rutvehiculo_franja'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutdespacho',
            name='estado_terminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rutdespacho',
            name='visitas_entregadas',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rutvisita',
            name='estado_entregado',
            field=models.BooleanField(default=False),
        ),
    ]
