# Generated by Django 4.2.4 on 2025-03-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0042_rutvisita_franja_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutvehiculo',
            name='tiempo',
            field=models.FloatField(default=0),
        ),
    ]
