# Generated by Django 4.2.4 on 2025-03-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0043_rutvehiculo_tiempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutdespacho',
            name='tiempo',
            field=models.FloatField(default=0),
        ),
    ]
