# Generated by Django 4.2.4 on 2025-03-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0044_rutdespacho_tiempo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rutvisita',
            old_name='distancia_proxima',
            new_name='distancia',
        ),
        migrations.AddField(
            model_name='rutvisita',
            name='tiempo_trayecto',
            field=models.IntegerField(default=0),
        ),
    ]
