# Generated by Django 4.2.4 on 2025-03-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0045_rename_distancia_proxima_rutvisita_distancia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutvisita',
            name='distancia',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='rutvisita',
            name='tiempo_servicio',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='rutvisita',
            name='tiempo_trayecto',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
    ]
