# Generated by Django 4.2.4 on 2025-03-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0046_alter_rutvisita_distancia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutdespacho',
            name='tiempo_servicio',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='rutdespacho',
            name='tiempo_trayecto',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='rutvisita',
            name='tiempo',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='rutdespacho',
            name='tiempo',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
    ]
