# Generated by Django 4.2.4 on 2025-03-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0049_rutvehiculo_usuario_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutdespacho',
            name='entrega_id',
            field=models.IntegerField(null=True),
        ),
    ]
