# Generated by Django 4.2.4 on 2025-03-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0050_rutdespacho_entrega_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutvisita',
            name='fecha_entrega',
            field=models.DateTimeField(null=True),
        ),
    ]
