# Generated by Django 4.2.4 on 2025-03-28 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0051_rutvisita_fecha_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutdespacho',
            name='fecha_ubicacion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='rutdespacho',
            name='latitud',
            field=models.DecimalField(decimal_places=15, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='rutdespacho',
            name='longitud',
            field=models.DecimalField(decimal_places=15, max_digits=25, null=True),
        ),
        migrations.CreateModel(
            name='RutUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(null=True)),
                ('latitud', models.DecimalField(decimal_places=15, max_digits=25, null=True)),
                ('longitud', models.DecimalField(decimal_places=15, max_digits=25, null=True)),
                ('despacho', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ubicaciones_despacho_rel', to='ruteo.rutdespacho')),
            ],
            options={
                'db_table': 'rut_ubicacion',
            },
        ),
    ]
