# Generated by Django 4.2.4 on 2025-03-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0053_alter_rutubicacion_fecha_alter_rutubicacion_latitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutubicacion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
