# Generated by Django 4.2.4 on 2025-03-31 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0054_alter_rutubicacion_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutdespacho',
            name='fecha_salida',
            field=models.DateTimeField(null=True),
        ),
    ]
