# Generated by Django 4.2.4 on 2025-04-01 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0055_rutdespacho_fecha_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutubicacion',
            name='visita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ubicaciones_visita_rel', to='ruteo.rutvisita'),
        ),
    ]
