# Generated by Django 4.2.4 on 2025-04-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0056_rutubicacion_visita'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutubicacion',
            name='usuario_id',
            field=models.IntegerField(null=True),
        ),
    ]
