# Generated by Django 4.2.4 on 2025-04-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0057_rutubicacion_usuario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutubicacion',
            name='detenido',
            field=models.IntegerField(default=0),
        ),
    ]
