# Generated by Django 4.2.4 on 2025-04-23 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0059_rutdespacho_visitas_liberadas'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutNovedadTipo',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'rut_novedad_tipo',
            },
        ),
        migrations.CreateModel(
            name='RutNovedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(null=True)),
                ('fecha_solucion', models.DateTimeField(null=True)),
                ('descripcion', models.CharField(max_length=255, null=True)),
                ('solucion', models.CharField(max_length=255, null=True)),
                ('estado_solucion', models.BooleanField(default=False)),
                ('novedad_tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='novedades_novedad_tipo_rel', to='ruteo.rutnovedadtipo')),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='novedades_visita_rel', to='ruteo.rutvisita')),
            ],
            options={
                'db_table': 'rut_novedad',
            },
        ),
    ]
