# Generated by Django 4.2.4 on 2025-04-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0060_rutnovedadtipo_rutnovedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutvisita',
            name='estado_novedad',
            field=models.BooleanField(default=False),
        ),
    ]
