# Generated by Django 4.2.4 on 2025-04-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0061_rutvisita_estado_novedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutnovedad',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
