# Generated by Django 4.2.4 on 2025-04-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0062_alter_rutnovedad_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutdespacho',
            name='estado_anulado',
            field=models.BooleanField(default=False),
        ),
    ]
