# Generated by Django 4.2.4 on 2025-04-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0063_rutdespacho_estado_anulado'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutvisita',
            name='estado_devolucion',
            field=models.BooleanField(default=False),
        ),
    ]
