# Generated by Django 4.2.4 on 2025-05-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0064_rutvisita_estado_devolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutdespacho',
            name='visitas_novedad',
            field=models.FloatField(default=0),
        ),
    ]
