# Generated by Django 4.2.4 on 2025-05-19 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0065_rutdespacho_visitas_novedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutnovedad',
            name='visita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novedades_visita_rel', to='ruteo.rutvisita'),
        ),
    ]
