# Generated by Django 4.2.4 on 2025-05-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0066_alter_rutnovedad_visita'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutvisita',
            name='estado_entregado_complemento',
            field=models.BooleanField(default=False),
        ),
    ]
