# Generated by Django 4.2.4 on 2025-05-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0067_rutvisita_estado_entregado_complemento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutvisita',
            name='destinatario_correo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rutvisita',
            name='destinatario_telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
