# Generated by Django 4.2.4 on 2025-05-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0068_alter_rutvisita_destinatario_correo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutvehiculo',
            name='franja_codigo',
        ),
        migrations.RemoveField(
            model_name='rutvehiculo',
            name='franja_id',
        ),
        migrations.AddField(
            model_name='rutvehiculo',
            name='franjas',
            field=models.ManyToManyField(to='ruteo.rutfranja'),
        ),
    ]
