# Generated by Django 4.2.4 on 2025-05-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0069_remove_rutvehiculo_franja_codigo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutvehiculo',
            name='franjas',
        ),
        migrations.AddField(
            model_name='rutvehiculo',
            name='franja_codigo',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rutvehiculo',
            name='franja_id',
            field=models.IntegerField(null=True),
        ),
    ]
