# Generated by Django 4.2.4 on 2025-05-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0071_remove_rutvehiculo_franja_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutflota',
            name='prioridad',
            field=models.IntegerField(null=True),
        ),
    ]
