# Generated by Django 4.2.4 on 2025-03-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenedor_id', models.IntegerField()),
                ('usuario_id', models.IntegerField()),
            ],
            options={
                'db_table': 'ver_entrega',
            },
        ),
    ]
