# Generated by Django 4.2.4 on 2025-05-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(null=True)),
                ('peso', models.FloatField(default=0)),
                ('volumen', models.FloatField(default=0)),
                ('tiempo_servicio', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('tiempo_trayecto', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('tiempo', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('visitas', models.FloatField(default=0)),
                ('visitas_entregadas', models.FloatField(default=0)),
                ('despacho_id', models.IntegerField(default=0)),
                ('contenedor_id', models.IntegerField()),
                ('schema_name', models.CharField(max_length=100, null=True)),
                ('usuario_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'ver_entrega',
            },
        ),
    ]
