# Generated by Django 4.2.4 on 2025-06-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verentrega',
            name='tiempo',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='verentrega',
            name='tiempo_servicio',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='verentrega',
            name='tiempo_trayecto',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
    ]
