# Generated by Django 4.2.4 on 2025-03-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verentrega',
            name='desapcho_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verentrega',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='verentrega',
            name='peso',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='verentrega',
            name='tiempo',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='verentrega',
            name='tiempo_servicio',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='verentrega',
            name='tiempo_trayecto',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='verentrega',
            name='visitas',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='verentrega',
            name='visitas_entregadas',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='verentrega',
            name='volumen',
            field=models.FloatField(default=0),
        ),
    ]
