# Generated by Django 4.2.4 on 2025-03-19 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vertical', '0002_verentrega_desapcho_id_verentrega_fecha_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verentrega',
            old_name='desapcho_id',
            new_name='despacho_id',
        ),
    ]
