# Generated by Django 4.2.4 on 2025-06-11 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vertical', '0002_alter_verentrega_tiempo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verentrega',
            options={'ordering': ['-id']},
        ),
    ]
