# Generated by Django 4.2.4 on 2025-08-26 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vertical', '0003_alter_verentrega_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerCarroceria',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'ver_carroceria',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='VerCategoriaLicencia',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'ver_categoria_licencia',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VerCiudad',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('codigo_postal', models.CharField(max_length=10, null=True)),
                ('codigo', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'ver_ciudad',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='VerColor',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'ver_color',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='VerCombustible',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'ver_combustible',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='VerIdentificacion',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('abreviatura', models.CharField(max_length=10, null=True)),
                ('codigo', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'ver_identificacion',
            },
        ),
        migrations.CreateModel(
            name='VerLinea',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'ver_linea',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='VerMarca',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10)),
                ('remolque', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ver_marca',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='VerPais',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('codigo', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'ver_pais',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='VerVehiculoConfiguracion',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'ver_vehiculo_configuracion',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='VerVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('placa', models.CharField(max_length=6)),
                ('modelo', models.IntegerField()),
                ('modelo_repotenciado', models.IntegerField(null=True)),
                ('motor', models.CharField(max_length=50, null=True)),
                ('chasis', models.CharField(max_length=50, null=True)),
                ('ejes', models.IntegerField()),
                ('peso_vacio', models.IntegerField()),
                ('capacidad', models.IntegerField()),
                ('poliza', models.CharField(max_length=30, null=True)),
                ('vence_poliza', models.DateField()),
                ('tecnicomecanica', models.CharField(max_length=30, null=True)),
                ('vence_tecnicomecanica', models.DateField()),
                ('propio', models.BooleanField(default=False)),
                ('remolque', models.BooleanField(default=False)),
                ('carroceria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos_carroceria_rel', to='vertical.vercarroceria')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos_color_rel', to='vertical.vercolor')),
                ('combustible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos_combustible_rel', to='vertical.vercombustible')),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos_vehiculo_configuracion_rel', to='vertical.vervehiculoconfiguracion')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos_linea_rel', to='vertical.verlinea')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos_marca_rel', to='vertical.vermarca')),
            ],
            options={
                'db_table': 'ver_vehiculo',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='verlinea',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lineas_marca_rel', to='vertical.vermarca'),
        ),
        migrations.CreateModel(
            name='VerEstado',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=10, null=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vertical.verpais')),
            ],
            options={
                'db_table': 'ver_estado',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='VerConductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_identificacion', models.CharField(max_length=20)),
                ('digito_verificacion', models.CharField(max_length=1, null=True)),
                ('nombre_corto', models.CharField(max_length=200)),
                ('nombre1', models.CharField(max_length=50, null=True)),
                ('nombre2', models.CharField(max_length=50, null=True)),
                ('apellido1', models.CharField(max_length=50, null=True)),
                ('apellido2', models.CharField(max_length=50, null=True)),
                ('direccion', models.CharField(max_length=100)),
                ('barrio', models.CharField(max_length=200, null=True)),
                ('telefono', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=50, null=True)),
                ('correo', models.CharField(max_length=255)),
                ('numero_licencia', models.CharField(max_length=50, null=True)),
                ('fecha_vence_licencia', models.DateField(null=True)),
                ('categoria_licencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vertical.vercategorialicencia')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vertical.verciudad')),
                ('identificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vertical.veridentificacion')),
            ],
            options={
                'db_table': 'ver_conductor',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='verciudad',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vertical.verestado'),
        ),
    ]
