# Generated by Django 4.2.4 on 2025-03-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertical', '0003_rename_desapcho_id_verentrega_despacho_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='verentrega',
            name='schema_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
