# Generated by Django 4.2.4 on 2025-08-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertical', '0004_vercarroceria_vercategorialicencia_verciudad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
                ('peso', models.FloatField(default=0)),
                ('volumen', models.FloatField(default=0)),
                ('negocio_id', models.IntegerField(default=0)),
                ('contenedor_id', models.IntegerField()),
                ('schema_name', models.CharField(max_length=100, null=True)),
                ('usuario_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'ver_viaje',
                'ordering': ['-id'],
            },
        ),
    ]
