# Generated by Django 4.2.4 on 2025-08-29 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vertical', '0005_verviaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='verviaje',
            name='ciudad_destino',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='viajes_ciudad_destino_rel', to='vertical.verciudad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verviaje',
            name='ciudad_origen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='viajes_ciudad_origen_rel', to='vertical.verciudad'),
            preserve_default=False,
        ),
    ]
