# Generated by Django 4.2.4 on 2025-08-29 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vertical', '0006_verviaje_ciudad_destino_verviaje_ciudad_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='verviaje',
            name='conductor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='viajes_conductor_rel', to='vertical.verconductor'),
        ),
        migrations.AddField(
            model_name='verviaje',
            name='vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='viajes_vehiculo_rel', to='vertical.vervehiculo'),
        ),
    ]
