# Generated by Django 4.2.4 on 2025-08-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertical', '0007_verviaje_conductor_verviaje_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='verconductor',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vervehiculo',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
    ]
