# Generated by Django 4.2.4 on 2025-08-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertical', '0008_verconductor_verificado_vervehiculo_verificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='verviaje',
            name='estado_aceptado',
            field=models.BooleanField(default=False),
        ),
    ]
