# Generated by Django 4.2.4 on 2025-08-29 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertical', '0009_verviaje_estado_aceptado'),
    ]

    operations = [
        migrations.AddField(
            model_name='verviaje',
            name='solicitud_cliente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='verviaje',
            name='unidades',
            field=models.FloatField(default=0),
        ),
    ]
