# Generated by Django 4.2.4 on 2025-08-29 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertical', '0010_verviaje_solicitud_cliente_verviaje_unidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verviaje',
            name='contenedor_id',
            field=models.IntegerField(null=True),
        ),
    ]
