# Generated by Django 4.2.4 on 2025-08-29 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vertical', '0011_alter_verviaje_contenedor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verviaje',
            name='usuario_id',
        ),
        migrations.AddField(
            model_name='verviaje',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='viajes_usuario_rel', to=settings.AUTH_USER_MODEL),
        ),
    ]
