# Generated by Django 4.2.4 on 2025-08-29 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertical', '0012_remove_verviaje_usuario_id_verviaje_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verviaje',
            name='negocio_id',
            field=models.IntegerField(null=True),
        ),
    ]
