# Generated by Django 4.2.4 on 2025-08-30 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertical', '0013_alter_verviaje_negocio_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='verviaje',
            name='contenedor_negocio_id',
            field=models.IntegerField(null=True),
        ),
    ]
