# Generated by Django 4.2.4 on 2025-08-30 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vertical', '0014_verviaje_contenedor_negocio_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerPropuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
                ('precio', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('contenedor_id', models.IntegerField(null=True)),
                ('estado_aceptado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propuestas_usuario_rel', to=settings.AUTH_USER_MODEL)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propuestas_viaje_rel', to='vertical.verviaje')),
            ],
            options={
                'db_table': 'ver_propuesta',
                'ordering': ['-id'],
            },
        ),
    ]
