# Generated by Django 4.2.4 on 2025-08-30 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertical', '0015_verpropuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='verviaje',
            name='flete',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
