# Generated by Django 4.2.4 on 2025-08-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertical', '0016_verviaje_flete'),
    ]

    operations = [
        migrations.AddField(
            model_name='verviaje',
            name='comentario',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
