# Generated by Django 4.2.4 on 2025-08-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertical', '0017_verviaje_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='verviaje',
            name='puntos_entrega',
            field=models.IntegerField(default=0),
        ),
    ]
