# Generated by Django 4.2.4 on 2025-08-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertical', '0018_verviaje_puntos_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='verviaje',
            name='cliente',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
