# Generated by Django 4.2.4 on 2025-08-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertical', '0019_verviaje_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerEmpaque',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'ver_empaque',
                'ordering': ['-id'],
            },
        ),
    ]
