# Generated by Django 4.2.4 on 2025-08-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertical', '0020_verempaque'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerProducto',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'ver_producto',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='VerServicio',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ver_servicio',
                'ordering': ['-id'],
            },
        ),
    ]
