# Generated by Django 4.2.4 on 2025-08-31 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vertical', '0021_verproducto_verservicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='verviaje',
            name='empaque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='viajes_empaque_rel', to='vertical.verempaque'),
        ),
        migrations.AddField(
            model_name='verviaje',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='viajes_producto_rel', to='vertical.verproducto'),
        ),
        migrations.AddField(
            model_name='verviaje',
            name='servicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='viajes_servicio_rel', to='vertical.verservicio'),
        ),
    ]
