# Generated by Django 4.2.4 on 2025-08-31 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertical', '0022_verviaje_empaque_verviaje_producto_verviaje_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='verviaje',
            name='propuestas',
            field=models.IntegerField(default=0),
        ),
    ]
