# Generated by Django 4.2.4 on 2025-08-31 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertical', '0023_verviaje_propuestas'),
    ]

    operations = [
        migrations.AddField(
            model_name='verpropuesta',
            name='empresa',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
