# Generated by Django 4.2.4 on 2025-08-31 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertical', '0024_verpropuesta_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='verviaje',
            name='estado_aceptado_transporte',
            field=models.BooleanField(default=False),
        ),
    ]
