# Generated by Django 4.2.4 on 2025-09-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertical', '0025_verviaje_estado_aceptado_transporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='verviaje',
            name='estado_cancelado',
            field=models.BooleanField(default=False),
        ),
    ]
