# Generated by Django 4.2.4 on 2025-09-03 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertical', '0026_verviaje_estado_cancelado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verviaje',
            old_name='estado_aceptado_transporte',
            new_name='solicitud_transporte',
        ),
        migrations.AddField(
            model_name='verviaje',
            name='pago',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
