# Generated by Django 4.2.4 on 2025-09-03 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertical', '0027_rename_estado_aceptado_transporte_verviaje_solicitud_transporte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verpropuesta',
            name='schema_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
