# Generated by Django 4.2.4 on 2025-09-03 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vertical', '0028_verpropuesta_schema_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verviaje',
            name='contenedor_negocio_id',
        ),
    ]
