# Generated by Django 4.2.4 on 2025-09-03 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vertical', '0029_remove_verviaje_contenedor_negocio_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerPrecioDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=200, null=True)),
                ('contenedor_id', models.IntegerField(null=True)),
                ('tonelada', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('ciudad_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='precios_detalles_ciudad_destino_rel', to='vertical.verciudad')),
                ('ciudad_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='precios_detalle_ciudad_origen_rel', to='vertical.verciudad')),
            ],
            options={
                'db_table': 'ver_precio_detalle',
                'ordering': ['-id'],
            },
        ),
    ]
