# Generated by Django 4.2.4 on 2025-09-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertical', '0030_verpreciodetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='verpreciodetalle',
            name='schema_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
