# Generated by Django 4.2.4 on 2025-09-10 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vertical', '0031_verpreciodetalle_schema_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerVerificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('verificador', models.CharField(max_length=100, null=True)),
                ('conductor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verificaciones_conductor_rel', to='vertical.verconductor')),
                ('vehiculo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verificaciones_vehiculo_rel', to='vertical.vervehiculo')),
            ],
            options={
                'db_table': 'ver_verificacion',
                'ordering': ['-id'],
            },
        ),
    ]
