# Generated by Django 4.2.4 on 2025-09-10 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vertical', '0032_ververificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerVerificacionConcepto',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ver_verificacion_concepto',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='VerVerificacionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verificado', models.BooleanField(default=False)),
                ('verificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verificaciones_detalles_verificacion_rel', to='vertical.ververificacion')),
                ('verificacion_concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verificaciones_detalles_verificacion_concepto_rel', to='vertical.ververificacionconcepto')),
            ],
            options={
                'db_table': 'ver_verificacion_detalle',
                'ordering': ['-id'],
            },
        ),
    ]
