# Generated by Django 4.2.4 on 2025-09-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertical', '0033_ververificacionconcepto_ververificaciondetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='verviaje',
            name='numero_identificacion',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
