# Generated by Django 4.2.4 on 2025-09-11 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vertical', '0034_verviaje_numero_identificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verpropuesta',
            name='viaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propuestas_viaje_rel', to='vertical.verviaje'),
        ),
    ]
