# Generated by Django 4.2.4 on 2025-09-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertical', '0035_alter_verpropuesta_viaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='verpreciodetalle',
            name='tonelada_pago',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
