# Generated by Django 4.2.4 on 2025-09-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertical', '0036_verpreciodetalle_tonelada_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='verpropuesta',
            name='pago',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
