# Generated by Django 4.2.4 on 2025-09-16 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vertical', '0037_verpropuesta_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='verconductor',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='coductores_usuario_rel', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vervehiculo',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos_usuario_rel', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='verconductor',
            name='categoria_licencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coductores_categoria_licencia_rel', to='vertical.vercategorialicencia'),
        ),
        migrations.AlterField(
            model_name='verconductor',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coductores_ciudad_rel', to='vertical.verciudad'),
        ),
        migrations.AlterField(
            model_name='verconductor',
            name='identificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coductores_identificacion_rel', to='vertical.veridentificacion'),
        ),
    ]
