# Generated by Django 4.2.4 on 2025-09-18 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertical', '0038_verconductor_usuario_vervehiculo_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerParametro',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('version_ruteo', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'ver_parametro',
                'ordering': ['-id'],
            },
        ),
    ]
