# Generated by Django 4.2.4 on 2025-09-18 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertical', '0039_verparametro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verparametro',
            name='version_ruteo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
