# Generated by Django 4.2.4 on 2025-09-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertical', '0040_alter_verparametro_version_ruteo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verparametro',
            old_name='version_ruteo',
            new_name='version_ruteo_android',
        ),
        migrations.AddField(
            model_name='verparametro',
            name='version_ruteo_ios',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
