# Generated by Django 4.2.4 on 2025-11-12 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vertical', '0041_rename_version_ruteo_verparametro_version_ruteo_android_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ververificacion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='propuestas_usuario_rel', to=settings.AUTH_USER_MODEL),
        ),
    ]
