# Generated by Django 4.2.4 on 2025-11-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertical', '0043_alter_ververificacion_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='ververificacion',
            name='verificacion_tipo_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
