# Generated by Django 4.2.4 on 2025-11-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertical', '0044_ververificacion_verificacion_tipo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='verconductor',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verconductor',
            name='fecha_verificacion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='verconductor',
            name='fecha_verificacion_vence',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='vervehiculo',
            name='fecha_verificacion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='vervehiculo',
            name='fecha_verificacion_vence',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ververificacion',
            name='fecha_verificacion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ververificacion',
            name='fecha_verificacion_vence',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ververificacion',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
    ]
