# Generated by Django 4.2.4 on 2025-11-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertical', '0045_verconductor_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verconductor',
            name='verificado_proceso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vervehiculo',
            name='verificado_proceso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ververificacion',
            name='estado_proceso',
            field=models.BooleanField(default=False),
        ),
    ]
