# Generated by Django 4.2.4 on 2025-11-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertical', '0046_verconductor_verificado_proceso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ververificacionconcepto',
            name='tipo',
        ),
        migrations.AddField(
            model_name='ververificacionconcepto',
            name='verificacion_tipo_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
