# Generated by Django 4.2.4 on 2025-11-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertical', '0047_remove_ververificacionconcepto_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ververificaciondetalle',
            name='fecha_verificacion',
            field=models.DateTimeField(null=True),
        ),
    ]
