# Generated by Django 4.2.4 on 2023-09-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquilino', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquilino',
            name='empresa_id',
            field=models.IntegerField(null=True),
        ),
    ]
