# Generated by Django 4.2.4 on 2023-09-21 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquilino', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verificacion',
            old_name='empresa_id',
            new_name='inquilino_id',
        ),
    ]
