# Generated by Django 4.2.4 on 2023-09-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquilino', '0003_inquilino_empresa_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquilino',
            name='empresa_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
