# Generated by Django 4.2.4 on 2023-09-22 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inquilino', '0004_alter_inquilino_empresa_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='InquilinoPais',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('codigo', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'inq_pais',
            },
        ),
        migrations.CreateModel(
            name='InquilinoIdentificacion',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('orden', models.BigIntegerField(default=0)),
                ('codigo', models.CharField(max_length=10, null=True)),
                ('pais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inquilino.inquilinopais')),
            ],
            options={
                'db_table': 'inq_identificacion',
            },
        ),
        migrations.CreateModel(
            name='InquilinoEstado',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=10, null=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inquilino.inquilinopais')),
            ],
            options={
                'db_table': 'inq_estado',
            },
        ),
        migrations.CreateModel(
            name='InquilinoCiudad',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('codigo_postal', models.CharField(max_length=10, null=True)),
                ('porcentaje_impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inquilino.inquilinoestado')),
            ],
            options={
                'db_table': 'inq_ciudad',
            },
        ),
    ]
