# Generated by Django 4.2.4 on 2023-09-22 15:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inquilino', '0005_inquilinopais_inquilinoidentificacion_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movimiento',
            new_name='InquilinoMovimiento',
        ),
        migrations.RemoveField(
            model_name='inquilino',
            name='empresa_id',
        ),
    ]
