# Generated by Django 4.2.4 on 2023-09-22 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquilino', '0006_rename_movimiento_inquilinomovimiento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumo',
            old_name='empresa_id',
            new_name='inquilino_id',
        ),
    ]
