# Generated by Django 4.2 on 2023-06-30 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificacion',
            name='codigo_usuario_fk',
        ),
        migrations.AddField(
            model_name='verificacion',
            name='empresa_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='verificacion',
            name='usuario_id',
            field=models.IntegerField(null=True),
        ),
    ]
