# Generated by Django 4.2 on 2023-06-30 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_remove_verificacion_codigo_usuario_fk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificacion',
            name='usuario_invitado_id',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
