# Generated by Django 4.2 on 2023-06-07 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_remove_user_codigo_cliente_fk_usuarioempresa'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuarioempresa',
            table='seguridad_usuario_empresa',
        ),
    ]
