# Generated by Django 4.2 on 2023-06-30 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0003_verificacion_usuario_invitado_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verificacion',
            old_name='usuario_invitado_id',
            new_name='usuario_invitado_username',
        ),
    ]
