# Generated by Django 4.2 on 2023-07-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0004_rename_usuario_invitado_id_verificacion_usuario_invitado_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='correo',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='user',
            name='nombre_corto',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telefono',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
