# Generated by Django 4.2 on 2023-07-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0005_rename_last_name_user_apellido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioempresa',
            name='rol',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
