# Generated by Django 4.2 on 2023-08-08 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(null=True)),
                ('nombre', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'con_cuenta',
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(null=True)),
                ('fecha', models.DateField(null=True)),
                ('debito', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('credito', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('base', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('contacto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='con_movimientos', to='general.contacto')),
                ('cuenta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='con_movimientos', to='contabilidad.cuenta')),
                ('documento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='con_movimientos', to='general.documento')),
            ],
            options={
                'db_table': 'con_movimiento',
            },
        ),
    ]
