# Generated by Django 4.2.4 on 2025-05-30 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100, null=True)),
                ('serie', models.CharField(max_length=100, null=True)),
                ('modelo', models.CharField(max_length=100, null=True)),
                ('fecha_compra', models.DateField()),
                ('fecha_activacion', models.DateField()),
                ('fecha_baja', models.DateField(null=True)),
                ('duracion', models.IntegerField(null=True)),
                ('valor_compra', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('depreciacion_inicial', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('depreciacion_periodo', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('depreciacion_acumulada', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('depreciacion_saldo', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
            ],
            options={
                'db_table': 'con_activo',
            },
        ),
        migrations.CreateModel(
            name='ConActivoGrupo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'con_activo_grupo',
            },
        ),
        migrations.CreateModel(
            name='ConComprobante',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, null=True)),
                ('permite_asiento', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'con_comprobante',
            },
        ),
        migrations.CreateModel(
            name='ConCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='0', max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('exige_base', models.BooleanField(default=False)),
                ('exige_contacto', models.BooleanField(default=False)),
                ('exige_grupo', models.BooleanField(default=False)),
                ('permite_movimiento', models.BooleanField(default=False)),
                ('nivel', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'con_cuenta',
            },
        ),
        migrations.CreateModel(
            name='ConCuentaClase',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'con_cuenta_clase',
            },
        ),
        migrations.CreateModel(
            name='ConCuentaCuenta',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'con_cuenta_cuenta',
            },
        ),
        migrations.CreateModel(
            name='ConCuentaGrupo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'con_cuenta_grupo',
            },
        ),
        migrations.CreateModel(
            name='ConCuentaSubcuenta',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'con_cuenta_subcuenta',
            },
        ),
        migrations.CreateModel(
            name='ConGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(default='0', max_length=20, unique=True)),
            ],
            options={
                'db_table': 'con_grupo',
            },
        ),
        migrations.CreateModel(
            name='ConMetodoDepreciacion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'con_metodo_depreciacion',
            },
        ),
        migrations.CreateModel(
            name='ConPeriodo',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('anio', models.BigIntegerField()),
                ('mes', models.BigIntegerField()),
                ('estado_bloqueado', models.BooleanField(default=False)),
                ('estado_cerrado', models.BooleanField(default=False)),
                ('estado_inconsistencia', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'con_periodo',
            },
        ),
        migrations.CreateModel(
            name='ConMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(null=True)),
                ('fecha', models.DateField()),
                ('debito', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('credito', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('base', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('naturaleza', models.CharField(max_length=1)),
                ('detalle', models.CharField(max_length=150, null=True)),
                ('cierre', models.BooleanField(default=False)),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_comprobante_rel', to='contabilidad.concomprobante')),
            ],
            options={
                'db_table': 'con_movimiento',
            },
        ),
    ]
