# Generated by Django 4.2.4 on 2025-05-30 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabilidad', '0001_initial'),
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conmovimiento',
            name='contacto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_contacto_rel', to='general.gencontacto'),
        ),
        migrations.AddField(
            model_name='conmovimiento',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_cuenta_rel', to='contabilidad.concuenta'),
        ),
        migrations.AddField(
            model_name='conmovimiento',
            name='documento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_documento_rel', to='general.gendocumento'),
        ),
        migrations.AddField(
            model_name='conmovimiento',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_grupo_rel', to='contabilidad.congrupo'),
        ),
        migrations.AddField(
            model_name='conmovimiento',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_periodo_rel', to='contabilidad.conperiodo'),
        ),
        migrations.AddField(
            model_name='concuenta',
            name='cuenta_clase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.concuentaclase'),
        ),
        migrations.AddField(
            model_name='concuenta',
            name='cuenta_cuenta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.concuentacuenta'),
        ),
        migrations.AddField(
            model_name='concuenta',
            name='cuenta_grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.concuentagrupo'),
        ),
        migrations.AddField(
            model_name='concuenta',
            name='cuenta_subcuenta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.concuentasubcuenta'),
        ),
        migrations.AddField(
            model_name='conactivo',
            name='activo_grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos_activo_grupo_rel', to='contabilidad.conactivogrupo'),
        ),
        migrations.AddField(
            model_name='conactivo',
            name='cuenta_depreciacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos_cuenta_depreciacion_rel', to='contabilidad.concuenta'),
        ),
        migrations.AddField(
            model_name='conactivo',
            name='cuenta_gasto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos_cuenta_gasto_rel', to='contabilidad.concuenta'),
        ),
        migrations.AddField(
            model_name='conactivo',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos_grupo_rel', to='contabilidad.congrupo'),
        ),
        migrations.AddField(
            model_name='conactivo',
            name='metodo_depreciacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos_metodo_depreciacion_rel', to='contabilidad.conmetododepreciacion'),
        ),
    ]
