# Generated by Django 4.2.4 on 2024-05-29 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_cuenta_movimiento_cuenta_requiere_centro_costo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaClase',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'con_cuenta_clase',
            },
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='movimiento',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='requiere_centro_costo',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='requiere_tercero',
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='cuenta_clase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.cuentaclase'),
        ),
    ]
