# Generated by Django 4.2.4 on 2025-06-11 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conactivo',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='conactivogrupo',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='concomprobante',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='concuenta',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='concuentaclase',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='concuentacuenta',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='concuentagrupo',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='concuentasubcuenta',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='congrupo',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='conmetododepreciacion',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='conmovimiento',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='conperiodo',
            options={'ordering': ['-id']},
        ),
    ]
