# Generated by Django 4.2.4 on 2025-06-26 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_alter_conactivo_options_alter_conactivogrupo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concuenta',
            options={'ordering': ['codigo']},
        ),
    ]
