# Generated by Django 4.2.4 on 2024-07-31 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0091_configuracion_informacion_factura_superior'),
        ('contabilidad', '0004_rename_cuenta_concuenta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conmovimiento',
            name='contacto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_contacto_rel', to='general.contacto'),
        ),
        migrations.AlterField(
            model_name='conmovimiento',
            name='cuenta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_cuenta_re', to='contabilidad.concuenta'),
        ),
        migrations.AlterField(
            model_name='conmovimiento',
            name='documento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_documento_rel', to='general.documento'),
        ),
    ]
