# Generated by Django 4.2.4 on 2025-07-08 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0004_alter_concuenta_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='congrupo',
            options={'ordering': ['nombre']},
        ),
    ]
