# Generated by Django 4.2.4 on 2025-10-21 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0047_genconfiguracion_gen_item_administracion_and_more'),
        ('contabilidad', '0005_alter_congrupo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConConciliacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('cuenta_banco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conciliaciones_cuenta_banco_rel', to='general.gencuentabanco')),
            ],
            options={
                'db_table': 'con_conciliacion',
                'ordering': ['-id'],
            },
        ),
    ]
