# Generated by Django 4.2.4 on 2024-08-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_alter_conmovimiento_contacto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConComprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'con_comprobante',
            },
        ),
    ]
