# Generated by Django 4.2.4 on 2025-10-21 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0047_genconfiguracion_gen_item_administracion_and_more'),
        ('contabilidad', '0006_conconciliacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConConciliacionSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('debito', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('credito', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('detalle', models.CharField(max_length=150, null=True)),
                ('estado_conciliado', models.BooleanField(default=False)),
                ('conciliacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conciliaciones_soportes_conciliacion_rel', to='contabilidad.conconciliacion')),
            ],
            options={
                'db_table': 'con_conciliacion_soporte',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ConConciliacionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('debito', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('credito', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('detalle', models.CharField(max_length=150, null=True)),
                ('estado_conciliado', models.BooleanField(default=False)),
                ('conciliacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conciliaciones_detalles_conciliacion_rel', to='contabilidad.conconciliacion')),
                ('contacto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conciliaciones_detalles_contacto_rel', to='general.gencontacto')),
                ('cuenta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conciliaciones_detalles_cuenta_rel', to='contabilidad.concuenta')),
                ('documento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conciliaciones_detalles_documento_rel', to='general.gendocumento')),
            ],
            options={
                'db_table': 'con_conciliacion_detalle',
                'ordering': ['-id'],
            },
        ),
    ]
