# Generated by Django 4.2.4 on 2024-08-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0006_concomprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concuenta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
