# Generated by Django 4.2.4 on 2026-05-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0007_conconciliacionsoporte_conconciliaciondetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='conmovimiento',
            name='saldo_inicial',
            field=models.BooleanField(default=False),
        ),
    ]
