# Generated by Django 4.2.4 on 2024-08-09 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0008_concuenta_exige_base_concuenta_exige_tercero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conmovimiento',
            name='comprobante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_comprobante_rel', to='contabilidad.concomprobante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conmovimiento',
            name='naturaleza',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='conmovimiento',
            name='cuenta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_cuenta_rel', to='contabilidad.concuenta'),
            preserve_default=False,
        ),
    ]
