# Generated by Django 4.2.4 on 2024-08-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0009_conmovimiento_comprobante_conmovimiento_naturaleza_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conmovimiento',
            name='fecha',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conmovimiento',
            name='naturaleza',
            field=models.CharField(default='D', max_length=1),
            preserve_default=False,
        ),
    ]
