# Generated by Django 4.2.4 on 2024-08-09 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0010_alter_conmovimiento_fecha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'con_grupo',
            },
        ),
        migrations.AddField(
            model_name='concomprobante',
            name='codigo',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
