# Generated by Django 4.2.4 on 2024-08-09 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0011_congrupo_concomprobante_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='concuenta',
            name='exige_grupo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conmovimiento',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_grupo_rel', to='contabilidad.congrupo'),
        ),
    ]
