# Generated by Django 4.2.4 on 2024-08-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0012_concuenta_exige_grupo_conmovimiento_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='concomprobante',
            name='permite_asiento',
            field=models.BooleanField(default=False),
        ),
    ]
