# Generated by Django 4.2.4 on 2024-08-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0013_concomprobante_permite_asiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='conmovimiento',
            name='detalle',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
