# Generated by Django 4.2.4 on 2024-08-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0014_conmovimiento_detalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConPeriodo',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('anio', models.BigIntegerField()),
                ('mes', models.BigIntegerField()),
            ],
            options={
                'db_table': 'con_periodo',
            },
        ),
    ]
