# Generated by Django 4.2.4 on 2024-08-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0016_conmovimiento_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concuenta',
            name='codigo',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='concuenta',
            name='nombre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
