# Generated by Django 4.2.4 on 2024-09-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0019_concuentasubcuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concuentagrupo',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
