# Generated by Django 4.2.4 on 2024-09-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0020_alter_concuentagrupo_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concuentasubcuenta',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
