# Generated by Django 4.2.4 on 2024-09-23 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0021_alter_concuentasubcuenta_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='concuenta',
            name='cuenta_grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.concuentagrupo'),
        ),
        migrations.AddField(
            model_name='concuenta',
            name='cuenta_subcuenta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.concuentasubcuenta'),
        ),
        migrations.AddField(
            model_name='concuenta',
            name='nivel',
            field=models.IntegerField(null=True),
        ),
    ]
