# Generated by Django 4.2.4 on 2024-09-25 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0022_concuenta_cuenta_grupo_concuenta_cuenta_subcuenta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConCuentaCuenta',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'con_cuenta_cuenta',
            },
        ),
        migrations.AddField(
            model_name='concuenta',
            name='cuenta_cuenta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.concuentacuenta'),
        ),
    ]
