# Generated by Django 4.2.4 on 2024-09-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0023_concuentacuenta_concuenta_cuenta_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='conperiodo',
            name='estado_bloqueado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conperiodo',
            name='estado_cerrado',
            field=models.BooleanField(default=False),
        ),
    ]
