# Generated by Django 4.2.4 on 2024-11-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0024_conperiodo_estado_bloqueado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concomprobante',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
