# Generated by Django 4.2.4 on 2025-01-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0027_alter_concuenta_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concuenta',
            name='codigo',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
