# Generated by Django 4.2.4 on 2025-02-05 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0028_alter_concuenta_codigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concuenta',
            old_name='exige_tercero',
            new_name='exige_contacto',
        ),
    ]
