# Generated by Django 4.2.4 on 2025-02-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0029_rename_exige_tercero_concuenta_exige_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conmovimiento',
            name='credito',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='conmovimiento',
            name='debito',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
