# Generated by Django 4.2.4 on 2025-02-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0030_alter_conmovimiento_credito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conmovimiento',
            name='cierre',
            field=models.BooleanField(default=False),
        ),
    ]
