# Generated by Django 4.2.4 on 2025-03-12 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0032_alter_conmovimiento_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConActivoGrupo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'con_activo_grupo',
            },
        ),
        migrations.CreateModel(
            name='ConMetodoDepreciacion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'con_metodo_depreciacion',
            },
        ),
        migrations.CreateModel(
            name='ConActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100, null=True)),
                ('serie', models.CharField(max_length=100, null=True)),
                ('modelo', models.IntegerField(null=True)),
                ('fecha_compra', models.DateField()),
                ('fecha_activacion', models.DateField()),
                ('fecha_baja', models.DateField(null=True)),
                ('duracion', models.IntegerField(null=True)),
                ('valor_compra', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('depreciacion_inicial', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('activo_grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos_activo_grupo_rel', to='contabilidad.conactivogrupo')),
                ('cuenta_depreciacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos_cuenta_depreciacion_rel', to='contabilidad.concuenta')),
                ('cuenta_gasto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos_cuenta_gasto_rel', to='contabilidad.concuenta')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos_grupo_rel', to='contabilidad.congrupo')),
            ],
            options={
                'db_table': 'con_activo',
            },
        ),
    ]
