# Generated by Django 4.2.4 on 2025-03-12 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0033_conactivogrupo_conmetododepreciacion_conactivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='conactivo',
            name='metodo_depreciacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='activos_metodo_depreciacion_rel', to='contabilidad.conmetododepreciacion'),
            preserve_default=False,
        ),
    ]
