# Generated by Django 4.2.4 on 2025-03-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0035_conactivo_depreciacion_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='conactivo',
            name='depreciacion_acumulada',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='conactivo',
            name='depreciacion_saldo',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
