# Generated by Django 4.2.4 on 2025-03-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0036_conactivo_depreciacion_acumulada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conactivo',
            name='modelo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
