# Generated by Django 4.2.4 on 2025-03-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0037_alter_conactivo_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='conperiodo',
            name='estado_inconsistencia',
            field=models.BooleanField(default=False),
        ),
    ]
