# Generated by Django 4.2 on 2023-06-13 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('codigo_postal', models.CharField(max_length=10, null=True)),
                ('porcentaje_impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'db_table': 'gen_ciudad',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=100, null=True)),
                ('referencia', models.CharField(max_length=50, null=True)),
                ('costo', models.FloatField(default=0)),
                ('precio', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'gen_item',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('codigo', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'gen_pais',
            },
        ),
        migrations.CreateModel(
            name='Regimen',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'gen_regimen',
            },
        ),
        migrations.CreateModel(
            name='TipoPersona',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'gen_tipo_persona',
            },
        ),
        migrations.CreateModel(
            name='Identificacion',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('orden', models.BigIntegerField(default=0)),
                ('codigo', models.CharField(max_length=10, null=True)),
                ('pais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='general.pais')),
            ],
            options={
                'db_table': 'gen_identificacion',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=10, null=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.pais')),
            ],
            options={
                'db_table': 'gen_estado',
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_identificacion', models.CharField(max_length=20)),
                ('digito_verificacion', models.CharField(max_length=1, null=True)),
                ('nombre_corto', models.CharField(max_length=200)),
                ('nombre1', models.CharField(max_length=50, null=True)),
                ('nombre2', models.CharField(max_length=50, null=True)),
                ('apellido1', models.CharField(max_length=50, null=True)),
                ('apellido2', models.CharField(max_length=50, null=True)),
                ('direccion', models.CharField(max_length=50)),
                ('codigo_postal', models.CharField(max_length=20, null=True)),
                ('telefono', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=255)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.ciudad')),
                ('identificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.identificacion')),
                ('regimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.regimen')),
                ('tipo_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.tipopersona')),
            ],
            options={
                'db_table': 'gen_contacto',
            },
        ),
        migrations.AddField(
            model_name='ciudad',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.estado'),
        ),
    ]
