# Generated by Django 4.2 on 2023-04-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo_general', models.CharField(max_length=100, null=True)),
                ('referencia', models.CharField(max_length=50, null=True)),
                ('costo_predeterminado', models.FloatField(default=0)),
                ('precio_predeterminado', models.FloatField(default=0)),
                ('codigo_impuesto_compra_fkm', models.IntegerField(null=True)),
                ('codigo_impuesto_venta_fkm', models.IntegerField(null=True)),
                ('codigo_cuenta_venta_fk', models.IntegerField(null=True)),
                ('codigo_cuenta_costo_venta_fk', models.IntegerField(null=True)),
                ('codigo_cuenta_inventario_fk', models.IntegerField(null=True)),
                ('codigo_marca_fk', models.IntegerField(null=True)),
                ('codigo_medida_fkm', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'gen_item',
            },
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='codigo_empresa_fkm',
        ),
    ]
