# Generated by Django 4.2 on 2023-06-09 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='identificacion',
            name='orden',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='identificacion',
            name='pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='general.pais'),
        ),
        migrations.AlterField(
            model_name='identificacion',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='identificacion',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
