# Generated by Django 4.2 on 2023-06-15 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_movimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('nombre_extendido', models.CharField(max_length=100)),
                ('porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('venta', models.BooleanField()),
                ('compra', models.BooleanField()),
            ],
            options={
                'db_table': 'gen_impuesto',
            },
        ),
        migrations.CreateModel(
            name='ItemImpuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('impuesto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='general.impuesto')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemImpuestos', to='general.item')),
            ],
            options={
                'db_table': 'gen_item_impuesto',
                'unique_together': {('item', 'impuesto')},
            },
        ),
    ]
