# Generated by Django 4.2 on 2023-06-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_identificacion_orden_identificacion_pais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='codigo',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pais',
            name='id',
            field=models.CharField(max_length=2, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pais',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
