# Generated by Django 4.2 on 2023-06-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_pais_codigo_alter_pais_id_alter_pais_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='identificacion',
            name='codigo',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
