# Generated by Django 4.2 on 2023-06-20 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_detalle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detalle',
            new_name='MovimientoDetalle',
        ),
        migrations.AlterModelTable(
            name='movimientodetalle',
            table='gen_movimiento_detalle',
        ),
    ]
