# Generated by Django 4.2 on 2023-06-09 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_identificacion_codigo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departamento',
            new_name='Estado',
        ),
        migrations.RenameField(
            model_name='ciudad',
            old_name='departamento',
            new_name='estado',
        ),
        migrations.AlterModelTable(
            name='estado',
            table='gen_estado',
        ),
    ]
