# Generated by Django 4.2 on 2023-06-20 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_rename_detalle_movimientodetalle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'gen_movimiento_clase',
            },
        ),
        migrations.AddField(
            model_name='movimiento',
            name='movimiento_clase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='general.movimientoclase'),
        ),
    ]
