# Generated by Django 4.2 on 2023-06-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_rename_departamento_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='codigo',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
