# Generated by Django 4.2 on 2023-06-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_estado_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='codigo_postal',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='estado',
            name='latitud',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='estado',
            name='longitud',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='estado',
            name='porcentaje_impuesto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
