# Generated by Django 4.2 on 2023-06-20 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_movimientoclase_movimiento_movimiento_clase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='movimiento_clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='general.movimientoclase'),
        ),
    ]
