# Generated by Django 4.2 on 2023-06-20 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_alter_movimiento_movimiento_clase'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('movimiento_clase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_tipos', to='general.movimientoclase')),
            ],
            options={
                'db_table': 'gen_movimiento_tipo',
            },
        ),
        migrations.AddField(
            model_name='movimiento',
            name='movimiento_tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='general.movimientotipo'),
        ),
    ]
