# Generated by Django 4.2 on 2023-06-20 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_movimientotipo_movimiento_movimiento_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='movimiento_clase',
        ),
    ]
