# Generated by Django 4.2 on 2023-06-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_remove_estado_codigo_postal_remove_estado_latitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regimen',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipopersona',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
