# Generated by Django 4.2 on 2023-06-20 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0009_remove_movimiento_movimiento_clase'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='base_impuesto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='contacto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='general.contacto'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='fecha_contable',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='fecha_vence',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='impuesto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='numero',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='total_bruto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='movimientodetalle',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='movimientodetalle',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='general.item'),
        ),
        migrations.AddField(
            model_name='movimientodetalle',
            name='porcentaje_descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='movimientodetalle',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='movimientodetalle',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='movimientodetalle',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='movimientodetalle',
            name='total_bruto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='itemimpuesto',
            name='impuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.impuesto'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='movimiento_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='general.movimientotipo'),
        ),
        migrations.AlterField(
            model_name='movimientodetalle',
            name='cantidad',
            field=models.FloatField(default=0),
        ),
    ]
