# Generated by Django 4.2 on 2023-06-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0009_alter_regimen_id_alter_tipopersona_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='correo',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
