# Generated by Django 4.2 on 2023-06-13 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0010_alter_contacto_correo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='codigo_general',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='costo_predeterminado',
            new_name='costo',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='precio_predeterminado',
            new_name='precio',
        ),
        migrations.RemoveField(
            model_name='item',
            name='codigo_cuenta_costo_venta_fk',
        ),
        migrations.RemoveField(
            model_name='item',
            name='codigo_cuenta_inventario_fk',
        ),
        migrations.RemoveField(
            model_name='item',
            name='codigo_cuenta_venta_fk',
        ),
        migrations.RemoveField(
            model_name='item',
            name='codigo_impuesto_compra_fkm',
        ),
        migrations.RemoveField(
            model_name='item',
            name='codigo_impuesto_venta_fkm',
        ),
        migrations.RemoveField(
            model_name='item',
            name='codigo_marca_fk',
        ),
        migrations.RemoveField(
            model_name='item',
            name='codigo_medida_fkm',
        ),
    ]
