# Generated by Django 4.2 on 2023-06-20 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0010_movimiento_base_impuesto_movimiento_contacto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemimpuesto',
            name='nombre',
        ),
    ]
