# Generated by Django 4.2 on 2023-06-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0011_remove_itemimpuesto_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impuesto',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
