# Generated by Django 4.2 on 2023-06-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0012_alter_impuesto_porcentaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impuesto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
