# Generated by Django 4.2 on 2023-06-22 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0013_alter_impuesto_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientodetalle',
            options={'ordering': ['id', 'movimiento', 'item', 'cantidad']},
        ),
    ]
