# Generated by Django 4.2 on 2023-06-23 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0014_alter_movimientodetalle_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoImpuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('impuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.impuesto')),
                ('movimiento_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.movimientodetalle')),
            ],
            options={
                'db_table': 'gen_movimiento_impuesto',
            },
        ),
    ]
