# Generated by Django 4.2 on 2023-07-05 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0015_movimientoimpuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='estado_aprobado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='contacto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gen_movimientos', to='general.contacto'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='movimiento_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gen_movimientos', to='general.movimientotipo'),
        ),
    ]
