# Generated by Django 4.2 on 2023-08-08 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('codigo_postal', models.CharField(max_length=10, null=True)),
                ('porcentaje_impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'db_table': 'gen_ciudad',
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_identificacion', models.CharField(max_length=20)),
                ('digito_verificacion', models.CharField(max_length=1, null=True)),
                ('nombre_corto', models.CharField(max_length=200)),
                ('nombre1', models.CharField(max_length=50, null=True)),
                ('nombre2', models.CharField(max_length=50, null=True)),
                ('apellido1', models.CharField(max_length=50, null=True)),
                ('apellido2', models.CharField(max_length=50, null=True)),
                ('direccion', models.CharField(max_length=50)),
                ('codigo_postal', models.CharField(max_length=20, null=True)),
                ('telefono', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=255)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.ciudad')),
            ],
            options={
                'db_table': 'gen_contacto',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(null=True)),
                ('fecha', models.DateField(null=True)),
                ('fecha_contable', models.DateField(null=True)),
                ('fecha_vence', models.DateField(null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('base_impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado_aprobado', models.BooleanField(default=False)),
                ('contacto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gen_documentos', to='general.contacto')),
            ],
            options={
                'db_table': 'gen_documento',
            },
        ),
        migrations.CreateModel(
            name='DocumentoClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'gen_documento_clase',
            },
        ),
        migrations.CreateModel(
            name='DocumentoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=0)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='general.documento')),
            ],
            options={
                'db_table': 'gen_documento_detalle',
                'ordering': ['id', 'documento', 'item', 'cantidad'],
            },
        ),
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('nombre_extendido', models.CharField(max_length=100)),
                ('porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('venta', models.BooleanField()),
                ('compra', models.BooleanField()),
            ],
            options={
                'db_table': 'gen_impuesto',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=100, null=True)),
                ('referencia', models.CharField(max_length=50, null=True)),
                ('costo', models.FloatField(default=0)),
                ('precio', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'gen_item',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('codigo', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'gen_pais',
            },
        ),
        migrations.CreateModel(
            name='Regimen',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'gen_regimen',
            },
        ),
        migrations.CreateModel(
            name='TipoPersona',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'gen_tipo_persona',
            },
        ),
        migrations.CreateModel(
            name='Identificacion',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('orden', models.BigIntegerField(default=0)),
                ('codigo', models.CharField(max_length=10, null=True)),
                ('pais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='general.pais')),
            ],
            options={
                'db_table': 'gen_identificacion',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=10, null=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.pais')),
            ],
            options={
                'db_table': 'gen_estado',
            },
        ),
        migrations.CreateModel(
            name='DocumentoTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('documento_clase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_tipos', to='general.documentoclase')),
            ],
            options={
                'db_table': 'gen_documento_tipo',
            },
        ),
        migrations.CreateModel(
            name='DocumentoImpuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('documento_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.documentodetalle')),
                ('impuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.impuesto')),
            ],
            options={
                'db_table': 'gen_documento_impuesto',
            },
        ),
        migrations.AddField(
            model_name='documentodetalle',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='general.item'),
        ),
        migrations.AddField(
            model_name='documento',
            name='documento_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gen_documentos', to='general.documentotipo'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='identificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.identificacion'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='regimen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.regimen'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='tipo_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.tipopersona'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.estado'),
        ),
        migrations.CreateModel(
            name='ItemImpuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.impuesto')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemImpuestos', to='general.item')),
            ],
            options={
                'db_table': 'gen_item_impuesto',
                'unique_together': {('item', 'impuesto')},
            },
        ),
    ]
