# Generated by Django 4.2.4 on 2025-05-30 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_tipo_id', models.IntegerField(default=1)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=500)),
                ('tipo', models.CharField(max_length=100)),
                ('tamano', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('almacenamiento_id', models.CharField(max_length=255)),
                ('uuid', models.CharField(max_length=100, null=True)),
                ('codigo', models.IntegerField(null=True)),
                ('modelo', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'gen_archivo',
            },
        ),
        migrations.CreateModel(
            name='GenAsesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_corto', models.CharField(max_length=200)),
                ('celular', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=255)),
            ],
            options={
                'db_table': 'gen_asesor',
            },
        ),
        migrations.CreateModel(
            name='GenBanco',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'gen_banco',
            },
        ),
        migrations.CreateModel(
            name='GenCiudad',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('latitud', models.CharField(max_length=20, null=True)),
                ('longitud', models.CharField(max_length=20, null=True)),
                ('codigo_postal', models.CharField(max_length=10, null=True)),
                ('porcentaje_impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('codigo', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'gen_ciudad',
            },
        ),
        migrations.CreateModel(
            name='GenComplemento',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('instalado', models.BooleanField(default=False)),
                ('estructura_json', models.JSONField(null=True)),
                ('datos_json', models.JSONField(null=True)),
            ],
            options={
                'db_table': 'gen_complemento',
            },
        ),
        migrations.CreateModel(
            name='GenConfiguracion',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('informacion_factura', models.TextField(null=True)),
                ('informacion_factura_superior', models.TextField(null=True)),
                ('gen_uvt', models.DecimalField(decimal_places=6, default=49799, max_digits=20)),
                ('gen_emitir_automaticamente', models.BooleanField(default=False)),
                ('hum_factor', models.DecimalField(decimal_places=3, default=7.666, max_digits=6)),
                ('hum_salario_minimo', models.DecimalField(decimal_places=6, default=1423500, max_digits=20)),
                ('hum_auxilio_transporte', models.DecimalField(decimal_places=6, default=200000, max_digits=20)),
                ('rut_sincronizar_complemento', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'gen_configuracion',
            },
        ),
        migrations.CreateModel(
            name='GenConfiguracionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'gen_configuracion_usuario',
            },
        ),
        migrations.CreateModel(
            name='GenContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_identificacion', models.CharField(max_length=20)),
                ('digito_verificacion', models.CharField(max_length=1, null=True)),
                ('nombre_corto', models.CharField(max_length=200)),
                ('nombre1', models.CharField(max_length=50, null=True)),
                ('nombre2', models.CharField(max_length=50, null=True)),
                ('apellido1', models.CharField(max_length=50, null=True)),
                ('apellido2', models.CharField(max_length=50, null=True)),
                ('direccion', models.CharField(max_length=100)),
                ('barrio', models.CharField(max_length=200, null=True)),
                ('codigo_ciuu', models.CharField(max_length=200, null=True)),
                ('codigo_postal', models.CharField(max_length=20, null=True)),
                ('telefono', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=50, null=True)),
                ('correo', models.CharField(max_length=255)),
                ('correo_facturacion_electronica', models.CharField(max_length=255, null=True)),
                ('cliente', models.BooleanField(default=False)),
                ('proveedor', models.BooleanField(default=False)),
                ('empleado', models.BooleanField(default=False)),
                ('numero_cuenta', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'gen_contacto',
            },
        ),
        migrations.CreateModel(
            name='GenCuentaBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero_cuenta', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'gen_cuenta_banco',
            },
        ),
        migrations.CreateModel(
            name='GenCuentaBancoClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'gen_cuenta_banco_clase',
            },
        ),
        migrations.CreateModel(
            name='GenCuentaBancoTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'gen_cuenta_banco_tipo',
            },
        ),
        migrations.CreateModel(
            name='GenDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(null=True)),
                ('fecha', models.DateField(null=True)),
                ('fecha_contable', models.DateField(null=True)),
                ('fecha_vence', models.DateField(null=True)),
                ('fecha_validacion', models.DateTimeField(null=True)),
                ('fecha_hasta', models.DateField(null=True)),
                ('subtotal', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('total', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('total_bruto', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('base_impuesto', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('descuento', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('impuesto', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('impuesto_retencion', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('impuesto_operado', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('afectado', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('pendiente', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('dias', models.BigIntegerField(default=0)),
                ('salario', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('devengado', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('deduccion', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('provision_cesantia', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('provision_interes', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('provision_prima', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('provision_vacacion', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('base_cotizacion', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('base_prestacion', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('base_prestacion_vacacion', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('evento_documento', models.CharField(default='PE', max_length=2)),
                ('evento_recepcion', models.CharField(default='PE', max_length=2)),
                ('evento_aceptacion', models.CharField(default='PE', max_length=2)),
                ('estado_aprobado', models.BooleanField(default=False)),
                ('estado_anulado', models.BooleanField(default=False)),
                ('estado_contabilizado', models.BooleanField(default=False)),
                ('estado_electronico', models.BooleanField(default=False)),
                ('estado_electronico_enviado', models.BooleanField(default=False)),
                ('estado_electronico_notificado', models.BooleanField(default=False)),
                ('estado_electronico_evento', models.BooleanField(default=False)),
                ('estado_electronico_descartado', models.BooleanField(default=False)),
                ('soporte', models.CharField(max_length=100, null=True)),
                ('orden_compra', models.CharField(max_length=50, null=True)),
                ('remision', models.CharField(max_length=50, null=True)),
                ('cue', models.CharField(max_length=150, null=True)),
                ('comentario', models.CharField(max_length=500, null=True)),
                ('qr', models.CharField(max_length=500, null=True)),
                ('electronico_id', models.IntegerField(null=True)),
                ('referencia_cue', models.CharField(max_length=150, null=True)),
                ('referencia_numero', models.IntegerField(null=True)),
                ('referencia_prefijo', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'gen_documento',
            },
        ),
        migrations.CreateModel(
            name='GenDocumentoClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('grupo', models.IntegerField(null=True)),
                ('codigo_dian', models.CharField(default='01', max_length=2)),
            ],
            options={
                'db_table': 'gen_documento_clase',
            },
        ),
        migrations.CreateModel(
            name='GenDocumentoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_registro', models.CharField(default='I', max_length=1)),
                ('cantidad', models.FloatField(default=0)),
                ('cantidad_operada', models.FloatField(default=0)),
                ('precio', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('pago', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('pago_operado', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('subtotal', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('descuento', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('total_bruto', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('base', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('base_impuesto', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('impuesto', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('impuesto_retencion', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('impuesto_operado', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('total', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('hora', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('dias', models.BigIntegerField(default=0)),
                ('base_cotizacion', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('base_prestacion', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('base_prestacion_vacacion', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('porcentaje', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('devengado', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('deduccion', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('naturaleza', models.CharField(max_length=1, null=True)),
                ('operacion', models.BigIntegerField(default=0)),
                ('operacion_inventario', models.BigIntegerField(default=0)),
                ('detalle', models.CharField(max_length=150, null=True)),
                ('numero', models.IntegerField(null=True)),
                ('activo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_detalles_activo_rel', to='contabilidad.conactivo')),
            ],
            options={
                'db_table': 'gen_documento_detalle',
                'ordering': ['id', 'documento', 'item', 'cantidad'],
            },
        ),
        migrations.CreateModel(
            name='GenImpuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('nombre_extendido', models.CharField(max_length=100)),
                ('porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('porcentaje_base', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('operacion', models.IntegerField(default=1)),
                ('venta', models.BooleanField()),
                ('compra', models.BooleanField()),
                ('cuenta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='impuestos_cuenta_rel', to='contabilidad.concuenta')),
            ],
            options={
                'db_table': 'gen_impuesto',
            },
        ),
        migrations.CreateModel(
            name='GenImpuestoTipo',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'gen_impuesto_tipo',
            },
        ),
        migrations.CreateModel(
            name='GenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=100, null=True)),
                ('referencia', models.CharField(max_length=50, null=True)),
                ('costo', models.FloatField(default=0)),
                ('precio', models.FloatField(default=0)),
                ('producto', models.BooleanField(default=False)),
                ('servicio', models.BooleanField(default=False)),
                ('inventario', models.BooleanField(default=False)),
                ('negativo', models.BooleanField(default=False)),
                ('favorito', models.BooleanField(default=False)),
                ('venta', models.BooleanField(default=True)),
                ('inactivo', models.BooleanField(default=False)),
                ('existencia', models.FloatField(default=0)),
                ('remision', models.FloatField(default=0)),
                ('disponible', models.FloatField(default=0)),
                ('imagen', models.TextField(null=True)),
                ('cuenta_compra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itemes_cuenta_compra_rel', to='contabilidad.concuenta')),
                ('cuenta_venta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itemes_cuenta_venta_rel', to='contabilidad.concuenta')),
            ],
            options={
                'db_table': 'gen_item',
            },
        ),
        migrations.CreateModel(
            name='GenMetodoPago',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'gen_metodo_pago',
            },
        ),
        migrations.CreateModel(
            name='GenPais',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('codigo', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'gen_pais',
            },
        ),
        migrations.CreateModel(
            name='GenParametros',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('uvt', models.DecimalField(decimal_places=6, default=47065, max_digits=20)),
                ('factor', models.DecimalField(decimal_places=3, default=7.666, max_digits=6)),
                ('salario_minimo', models.DecimalField(decimal_places=6, default=1300000, max_digits=20)),
                ('auxilio_transporte', models.DecimalField(decimal_places=6, default=162000, max_digits=20)),
            ],
            options={
                'db_table': 'gen_parametros',
            },
        ),
        migrations.CreateModel(
            name='GenPlazoPago',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('dias', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'gen_plazo_pago',
            },
        ),
        migrations.CreateModel(
            name='GenPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=1)),
                ('fecha_vence', models.DateField()),
            ],
            options={
                'db_table': 'gen_precio',
            },
        ),
        migrations.CreateModel(
            name='GenRegimen',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('codigo_interface', models.CharField(max_length=2, null=True)),
            ],
            options={
                'db_table': 'gen_regimen',
            },
        ),
        migrations.CreateModel(
            name='GenResolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefijo', models.CharField(max_length=50, null=True)),
                ('numero', models.CharField(max_length=50, null=True)),
                ('clave_tecnica', models.CharField(max_length=500, null=True)),
                ('set_prueba', models.CharField(max_length=500, null=True)),
                ('consecutivo_desde', models.IntegerField()),
                ('consecutivo_hasta', models.IntegerField()),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('venta', models.BooleanField(default=False)),
                ('compra', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'gen_resolucion',
            },
        ),
        migrations.CreateModel(
            name='GenTipoPersona',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'gen_tipo_persona',
            },
        ),
        migrations.CreateModel(
            name='GenSede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('grupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedes_grupo_rel', to='contabilidad.congrupo')),
            ],
            options={
                'db_table': 'gen_sede',
            },
        ),
        migrations.CreateModel(
            name='GenPrecioDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vr_precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='general.genitem')),
                ('precio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='general.genprecio')),
            ],
            options={
                'db_table': 'gen_precio_detalle',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GenItemImpuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.genimpuesto')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itemImpuestos', to='general.genitem')),
            ],
            options={
                'db_table': 'gen_item_impuesto',
            },
        ),
        migrations.AddField(
            model_name='genimpuesto',
            name='impuesto_tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='impuestos_impuesto_tipo_rel', to='general.genimpuestotipo'),
        ),
        migrations.CreateModel(
            name='GenIdentificacion',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('abreviatura', models.CharField(max_length=10, null=True)),
                ('orden', models.BigIntegerField(default=0)),
                ('codigo', models.CharField(max_length=10, null=True)),
                ('aporte', models.CharField(max_length=10, null=True)),
                ('pais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='general.genpais')),
                ('tipo_persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='general.gentipopersona')),
            ],
            options={
                'db_table': 'gen_identificacion',
            },
        ),
        migrations.CreateModel(
            name='GenFormaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cuenta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formas_pagos_cuenta_rel', to='contabilidad.concuenta')),
            ],
            options={
                'db_table': 'gen_forma_pago',
            },
        ),
        migrations.CreateModel(
            name='GenEstado',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=10, null=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.genpais')),
            ],
            options={
                'db_table': 'gen_estado',
            },
        ),
        migrations.CreateModel(
            name='GenEmpresa',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('numero_identificacion', models.CharField(max_length=20, null=True)),
                ('digito_verificacion', models.CharField(max_length=1, null=True)),
                ('nombre_corto', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=50, null=True)),
                ('telefono', models.CharField(max_length=50, null=True)),
                ('correo', models.EmailField(max_length=255)),
                ('imagen', models.TextField(null=True)),
                ('contenedor_id', models.IntegerField()),
                ('rededoc_id', models.IntegerField(null=True)),
                ('subdominio', models.CharField(default='demo', max_length=100)),
                ('asistente_electronico', models.BooleanField(default=False)),
                ('asistente_predeterminado', models.BooleanField(default=False)),
                ('ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='general.genciudad')),
                ('identificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='general.genidentificacion')),
                ('regimen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='general.genregimen')),
                ('tipo_persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='general.gentipopersona')),
            ],
            options={
                'db_table': 'gen_empresa',
            },
        ),
        migrations.CreateModel(
            name='GenDocumentoTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('consecutivo', models.IntegerField(default=1)),
                ('venta', models.BooleanField(default=False)),
                ('compra', models.BooleanField(default=False)),
                ('cobrar', models.BooleanField(default=False)),
                ('pagar', models.BooleanField(default=False)),
                ('electronico', models.BooleanField(default=False)),
                ('contabilidad', models.BooleanField(default=False)),
                ('inventario', models.BooleanField(default=False)),
                ('operacion', models.BigIntegerField(default=0)),
                ('operacion_inventario', models.BigIntegerField(default=0)),
                ('comprobante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_tipos_comprobante_rel', to='contabilidad.concomprobante')),
                ('cuenta_cobrar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_tipos_cuenta_cobrar', to='contabilidad.concuenta')),
                ('cuenta_pagar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_tipos_cuenta_pagar', to='contabilidad.concuenta')),
                ('documento_clase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_tipos_documento_clase', to='general.gendocumentoclase')),
                ('resolucion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_tipos_resolucion', to='general.genresolucion')),
            ],
            options={
                'db_table': 'gen_documento_tipo',
            },
        ),
        migrations.CreateModel(
            name='GenDocumentoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('cuenta_banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_pagos_cuenta_banco', to='general.gencuentabanco')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_pagos_documento', to='general.gendocumento')),
            ],
            options={
                'db_table': 'gen_documento_pago',
            },
        ),
        migrations.CreateModel(
            name='GenDocumentoImpuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('porcentaje', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('porcentaje_base', models.DecimalField(decimal_places=6, default=100, max_digits=20)),
                ('total', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('total_operado', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('documento_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.gendocumentodetalle')),
                ('impuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.genimpuesto')),
            ],
            options={
                'db_table': 'gen_documento_impuesto',
            },
        ),
    ]
