# Generated by Django 4.2.4 on 2023-09-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='correo',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='direccion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='numero_identificacion',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
