# Generated by Django 4.2.4 on 2023-10-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='barrio',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='codigo_ciuu',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='documentoclase',
            name='codigo_dian',
            field=models.CharField(default='01', max_length=2),
        ),
        migrations.AddField(
            model_name='empresa',
            name='suscriptor',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
