# Generated by Django 4.2.4 on 2025-05-30 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
        ('inventario', '0001_initial'),
        ('contabilidad', '0002_initial'),
        ('humano', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='almacen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_detalles_almacen_rel', to='inventario.invalmacen'),
        ),
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='concepto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_detalles_concepto_rel', to='humano.humconcepto'),
        ),
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='contacto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_detalles_contacto_rel', to='general.gencontacto'),
        ),
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='contrato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_detalles_contrato_rel', to='humano.humcontrato'),
        ),
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='credito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_detalles_credito_rel', to='humano.humcredito'),
        ),
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='cuenta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_detalles_cuenta_rel', to='contabilidad.concuenta'),
        ),
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_detalles_documento_rel', to='general.gendocumento'),
        ),
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='documento_afectado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_detalles_documento_afectado_rel', to='general.gendocumento'),
        ),
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_detalles_grupo_rel', to='contabilidad.congrupo'),
        ),
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_detalles_item_rel', to='general.genitem'),
        ),
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='novedad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_detalles_novedad_rel', to='humano.humnovedad'),
        ),
        migrations.AddField(
            model_name='gendocumento',
            name='almacen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_almacen_rel', to='inventario.invalmacen'),
        ),
        migrations.AddField(
            model_name='gendocumento',
            name='aporte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_aporte_rel', to='humano.humaporte'),
        ),
        migrations.AddField(
            model_name='gendocumento',
            name='asesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_asesor_rel', to='general.genasesor'),
        ),
        migrations.AddField(
            model_name='gendocumento',
            name='comprobante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_comprobante_rel', to='contabilidad.concomprobante'),
        ),
        migrations.AddField(
            model_name='gendocumento',
            name='contacto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contactos_rel', to='general.gencontacto'),
        ),
        migrations.AddField(
            model_name='gendocumento',
            name='contrato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_contrato_rel', to='humano.humcontrato'),
        ),
        migrations.AddField(
            model_name='gendocumento',
            name='cuenta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_cuenta_rel', to='contabilidad.concuenta'),
        ),
        migrations.AddField(
            model_name='gendocumento',
            name='cuenta_banco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_cuenta_banco_rel', to='general.gencuentabanco'),
        ),
        migrations.AddField(
            model_name='gendocumento',
            name='documento_referencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gen_documentos', to='general.gendocumento'),
        ),
        migrations.AddField(
            model_name='gendocumento',
            name='documento_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_documento_tipo_rel', to='general.gendocumentotipo'),
        ),
        migrations.AddField(
            model_name='gendocumento',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gen_documentos', to='general.genempresa'),
        ),
        migrations.AddField(
            model_name='gendocumento',
            name='forma_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gen_documentos_forma_pago_rel', to='general.genformapago'),
        ),
        migrations.AddField(
            model_name='gendocumento',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_grupo_rel', to='humano.humgrupo'),
        ),
        migrations.AddField(
            model_name='gendocumento',
            name='grupo_contabilidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_grupo_contabilidad_rel', to='contabilidad.congrupo'),
        ),
        migrations.AddField(
            model_name='gendocumento',
            name='metodo_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gen_documentos_metodo_pago_rel', to='general.genmetodopago'),
        ),
        migrations.AddField(
            model_name='gendocumento',
            name='periodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_periodo_rel', to='humano.humperiodo'),
        ),
        migrations.AddField(
            model_name='gendocumento',
            name='plazo_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gen_documentos_plazo_pago_rel', to='general.genplazopago'),
        ),
        migrations.AddField(
            model_name='gendocumento',
            name='programacion_detalle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_programacion_detalle_rel', to='humano.humprogramaciondetalle'),
        ),
        migrations.AddField(
            model_name='gendocumento',
            name='resolucion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gen_documentos', to='general.genresolucion'),
        ),
        migrations.AddField(
            model_name='gendocumento',
            name='sede',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_sede_rel', to='general.gensede'),
        ),
    ]
