# Generated by Django 4.2.4 on 2025-05-30 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contabilidad', '0002_initial'),
        ('general', '0002_initial'),
        ('humano', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumento',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_usuario_rel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gencuentabanco',
            name='cuenta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_bancos_cuenta_rel', to='contabilidad.concuenta'),
        ),
        migrations.AddField(
            model_name='gencuentabanco',
            name='cuenta_banco_clase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_bancos_cuenta_banco_clase', to='general.gencuentabancoclase'),
        ),
        migrations.AddField(
            model_name='gencuentabanco',
            name='cuenta_banco_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_bancos_cuenta_banco_tipo', to='general.gencuentabancotipo'),
        ),
        migrations.AddField(
            model_name='gencontacto',
            name='asesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='general.genasesor'),
        ),
        migrations.AddField(
            model_name='gencontacto',
            name='banco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='general.genbanco'),
        ),
        migrations.AddField(
            model_name='gencontacto',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.genciudad'),
        ),
        migrations.AddField(
            model_name='gencontacto',
            name='cuenta_banco_clase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='general.gencuentabancoclase'),
        ),
        migrations.AddField(
            model_name='gencontacto',
            name='identificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.genidentificacion'),
        ),
        migrations.AddField(
            model_name='gencontacto',
            name='plazo_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contactos_plazo_pago', to='general.genplazopago'),
        ),
        migrations.AddField(
            model_name='gencontacto',
            name='plazo_pago_proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contactos_plazo_pago_proveedor', to='general.genplazopago'),
        ),
        migrations.AddField(
            model_name='gencontacto',
            name='precio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='general.genprecio'),
        ),
        migrations.AddField(
            model_name='gencontacto',
            name='regimen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.genregimen'),
        ),
        migrations.AddField(
            model_name='gencontacto',
            name='tipo_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.gentipopersona'),
        ),
        migrations.AddField(
            model_name='genconfiguracionusuario',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='general.genempresa'),
        ),
        migrations.AddField(
            model_name='genconfiguracionusuario',
            name='sede',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuraciones_usuarios_sede_rel', to='general.gensede'),
        ),
        migrations.AddField(
            model_name='genconfiguracionusuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='genconfiguracion',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='general.genempresa'),
        ),
        migrations.AddField(
            model_name='genconfiguracion',
            name='hum_entidad_riesgo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='humano.humentidad'),
        ),
        migrations.AddField(
            model_name='genconfiguracion',
            name='pos_documento_tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='general.gendocumentotipo'),
        ),
        migrations.AddField(
            model_name='genciudad',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.genestado'),
        ),
        migrations.AddField(
            model_name='genarchivo',
            name='documento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archivos_documento_rel', to='general.gendocumento'),
        ),
        migrations.AlterUniqueTogether(
            name='genitemimpuesto',
            unique_together={('item', 'impuesto')},
        ),
    ]
