# Generated by Django 4.2.4 on 2023-09-21 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_alter_empresa_correo_alter_empresa_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.ciudad'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='correo',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='digito_verificacion',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='direccion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='identificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.identificacion'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='numero_identificacion',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='regimen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.regimen'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefono',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='tipo_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.tipopersona'),
        ),
    ]
