# Generated by Django 4.2.4 on 2023-11-09 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_contacto_barrio_contacto_codigo_ciuu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resolucion',
            old_name='fechaDesde',
            new_name='fecha_desde',
        ),
        migrations.RenameField(
            model_name='resolucion',
            old_name='fechaHasta',
            new_name='fecha_hasta',
        ),
    ]
