# Generated by Django 4.2.4 on 2023-09-02 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_formapago_metodopago'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='metodo_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gen_documentos', to='general.metodopago'),
        ),
    ]
