# Generated by Django 4.2.4 on 2023-09-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_alter_empresa_ciudad_alter_empresa_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
