# Generated by Django 4.2.4 on 2025-05-31 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genconfiguracion',
            name='rut_rutear_franja',
        ),
    ]
