# Generated by Django 4.2.4 on 2025-05-31 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genconfiguracion',
            name='rut_rutear_franja',
            field=models.BooleanField(default=False),
        ),
    ]
