# Generated by Django 4.2.4 on 2024-03-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_resolucion_ambiente_resolucion_clave_tecnica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=1)),
                ('fecha_vence', models.DateField()),
            ],
            options={
                'db_table': 'gen_precio',
            },
        ),
    ]
