# Generated by Django 4.2.4 on 2025-06-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_genconfiguracion_rut_rutear_franja'),
    ]

    operations = [
        migrations.AddField(
            model_name='genconfiguracion',
            name='rut_direccion_origen',
            field=models.TextField(null=True),
        ),
    ]
