# Generated by Django 4.2.4 on 2024-03-08 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrPrecio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='general.item')),
                ('precio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='general.precio')),
            ],
            options={
                'db_table': 'gen_precio_detalle',
                'ordering': ['id'],
            },
        ),
    ]
