# Generated by Django 4.2.4 on 2025-06-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_genconfiguracion_rut_direccion_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='genconfiguracion',
            name='rut_latitud',
            field=models.DecimalField(decimal_places=15, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='genconfiguracion',
            name='rut_longitud',
            field=models.DecimalField(decimal_places=15, max_digits=25, null=True),
        ),
    ]
