# Generated by Django 4.2.4 on 2025-06-07 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_genconfiguracion_rut_latitud_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenRh',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'gen_rh',
            },
        ),
    ]
