# Generated by Django 4.2.4 on 2024-03-08 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_preciodetalle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preciodetalle',
            old_name='vrPrecio',
            new_name='vr_precio',
        ),
    ]
