# Generated by Django 4.2.4 on 2025-06-08 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_genrh'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gendocumento',
            options={'ordering': ['-id']},
        ),
    ]
