# Generated by Django 4.2.4 on 2024-03-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_rename_vrprecio_preciodetalle_vr_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
    ]
