# Generated by Django 4.2.4 on 2024-03-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_alter_item_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='apellido1',
            field=models.CharField(max_length=50, null=True, verbose_name='Apellido1'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='apellido2',
            field=models.CharField(max_length=50, null=True, verbose_name='Apellido2'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='barrio',
            field=models.CharField(max_length=200, null=True, verbose_name='Barrio'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='celular',
            field=models.CharField(max_length=50, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='codigo_ciuu',
            field=models.CharField(max_length=200, null=True, verbose_name='CIUU'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='codigo_postal',
            field=models.CharField(max_length=20, null=True, verbose_name='C_Postal'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='correo',
            field=models.EmailField(max_length=255, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='digito_verificacion',
            field=models.CharField(max_length=1, null=True, verbose_name='DV'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='direccion',
            field=models.CharField(max_length=50, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombre1',
            field=models.CharField(max_length=50, null=True, verbose_name='Nombre1'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombre2',
            field=models.CharField(max_length=50, null=True, verbose_name='Nombre2'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombre_corto',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='numero_identificacion',
            field=models.CharField(max_length=20, verbose_name='NIT'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(max_length=50, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='item',
            name='codigo',
            field=models.CharField(max_length=100, null=True, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='item',
            name='costo',
            field=models.FloatField(default=0, verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='item',
            name='precio',
            field=models.FloatField(default=0, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='item',
            name='referencia',
            field=models.CharField(max_length=50, null=True, verbose_name='Referencia'),
        ),
    ]
