# Generated by Django 4.2.4 on 2025-06-10 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_alter_gendocumento_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gendocumentodetalle',
            options={'ordering': ['-id']},
        ),
    ]
