# Generated by Django 4.2.4 on 2024-03-08 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0009_alter_contacto_apellido1_alter_contacto_apellido2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='cobrar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='documento',
            name='cobrar_afectado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='documento',
            name='cobrar_pendiente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='documentodetalle',
            name='documentoAfectado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_afectado', to='general.documento'),
        ),
    ]
