# Generated by Django 4.2.4 on 2025-06-11 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0010_alter_gencontacto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genarchivo',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='genasesor',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='genbanco',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='genciudad',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='gencomplemento',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='genconfiguracion',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='genconfiguracionusuario',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='gencuentabanco',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='gencuentabancoclase',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='gencuentabancotipo',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='gendocumentoclase',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='gendocumentoimpuesto',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='gendocumentopago',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='gendocumentotipo',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='genempresa',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='genestado',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='genformapago',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='genidentificacion',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='genimpuesto',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='genimpuestotipo',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='genitem',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='genitemimpuesto',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='genmetodopago',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='genpais',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='genparametros',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='genplazopago',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='genprecio',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='genpreciodetalle',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='genregimen',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='genresolucion',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='genrh',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='gensede',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='gentipopersona',
            options={'ordering': ['-id']},
        ),
    ]
