# Generated by Django 4.2.4 on 2025-06-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0011_alter_genarchivo_options_alter_genasesor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumentotipo',
            name='pos',
            field=models.BooleanField(default=False),
        ),
    ]
