# Generated by Django 4.2.4 on 2025-06-14 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0012_gendocumentotipo_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='genarchivo',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
