# Generated by Django 4.2.4 on 2024-03-11 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0013_respuestaelectronica'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentodetalle',
            old_name='documento_fectado',
            new_name='documento_afectado',
        ),
    ]
