# Generated by Django 4.2.4 on 2025-06-24 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0013_genarchivo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genitemimpuesto',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemImpuestos', to='general.genitem'),
        ),
    ]
