# Generated by Django 4.2.4 on 2024-03-11 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0014_rename_documento_fectado_documentodetalle_documento_afectado'),
    ]

    operations = [
        migrations.AddField(
            model_name='identificacion',
            name='abreviatura',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
