# Generated by Django 4.2.4 on 2025-06-25 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0015_alter_genciudad_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genasesor',
            options={'ordering': ['nombre_corto']},
        ),
        migrations.AlterModelOptions(
            name='genbanco',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='gencuentabancoclase',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='genidentificacion',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='genplazopago',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='genregimen',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='gentipopersona',
            options={'ordering': ['nombre']},
        ),
    ]
