# Generated by Django 4.2.4 on 2024-03-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0015_identificacion_abreviatura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='suscriptor',
        ),
        migrations.AddField(
            model_name='empresa',
            name='reddoc_id',
            field=models.IntegerField(null=True),
        ),
    ]
