# Generated by Django 4.2.4 on 2025-06-26 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0016_alter_genasesor_options_alter_genbanco_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genformapago',
            options={'ordering': ['id']},
        ),
    ]
