# Generated by Django 4.2.4 on 2024-03-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0016_remove_empresa_suscriptor_empresa_reddoc_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_corto', models.CharField(max_length=200, verbose_name='Nombre')),
                ('celular', models.CharField(max_length=50, verbose_name='Celular')),
                ('correo', models.EmailField(max_length=255, verbose_name='Correo')),
            ],
            options={
                'db_table': 'gen_asesor',
            },
        ),
    ]
