# Generated by Django 4.2.4 on 2025-06-26 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0017_alter_genformapago_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genidentificacion',
            options={'ordering': ['orden']},
        ),
    ]
