# Generated by Django 4.2.4 on 2025-06-26 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0018_alter_genidentificacion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genimpuesto',
            options={'ordering': ['id', 'impuesto_tipo_id']},
        ),
    ]
