# Generated by Django 4.2.4 on 2025-07-08 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0019_alter_genimpuesto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gencuentabanco',
            options={'ordering': ['nombre']},
        ),
    ]
