# Generated by Django 4.2.4 on 2025-07-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0020_alter_gencuentabanco_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumento',
            name='fecha_desde',
            field=models.DateField(null=True),
        ),
    ]
