# Generated by Django 4.2.4 on 2025-07-13 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0014_humliquidacion_dias_cesantia_and_more'),
        ('general', '0021_gendocumento_fecha_desde'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumento',
            name='liquidacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_liquidacion_rel', to='humano.humliquidacion'),
        ),
    ]
