# Generated by Django 4.2.4 on 2024-03-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0021_contacto_plazo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='disponible',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='existencia',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='inventario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='producto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='servicio',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='codigo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='costo',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='precio',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='referencia',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
