# Generated by Django 4.2.4 on 2024-03-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0022_item_disponible_item_existencia_item_inventario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='codigo',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
