# Generated by Django 4.2.4 on 2025-08-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0022_gendocumento_liquidacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='gencontacto',
            name='categoria_licencia',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='gencontacto',
            name='fecha_vence_licencia',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='gencontacto',
            name='numero_licencia',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
