# Generated by Django 4.2.4 on 2025-08-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0023_gencontacto_categoria_licencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gencontacto',
            name='conductor',
            field=models.BooleanField(default=False),
        ),
    ]
