# Generated by Django 4.2.4 on 2025-08-15 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0024_gencontacto_conductor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gensede',
            options={'ordering': ['id']},
        ),
    ]
