# Generated by Django 4.2.4 on 2024-03-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0024_alter_contacto_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='latitud',
            field=models.DecimalField(decimal_places=9, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='longitud',
            field=models.DecimalField(decimal_places=9, max_digits=9, null=True),
        ),
    ]
