# Generated by Django 4.2.4 on 2025-08-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0025_alter_gensede_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumento',
            name='pago',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
