# Generated by Django 4.2.4 on 2025-08-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0026_gendocumento_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumentopago',
            name='estado_anulado',
            field=models.BooleanField(default=False),
        ),
    ]
