# Generated by Django 4.2.4 on 2024-03-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0027_alter_ciudad_latitud_alter_ciudad_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='latitud',
            field=models.DecimalField(decimal_places=10, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='longitud',
            field=models.DecimalField(decimal_places=10, max_digits=10, null=True),
        ),
    ]
