# Generated by Django 4.2.4 on 2025-08-22 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0017_alter_ttecategorialicencia_options'),
        ('general', '0027_gendocumentopago_estado_anulado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gencontacto',
            name='categoria_licencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='transporte.ttecategorialicencia'),
        ),
    ]
