# Generated by Django 4.2.4 on 2024-03-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0028_alter_ciudad_latitud_alter_ciudad_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='latitud',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='longitud',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
