# Generated by Django 4.2.4 on 2025-08-22 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0017_alter_ttecategorialicencia_options'),
        ('general', '0028_alter_gencontacto_categoria_licencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenDocumentoGuia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flete', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('manejo', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_guias_documento_rel', to='general.gendocumento')),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_guias_guia_rel', to='transporte.tteguia')),
            ],
            options={
                'db_table': 'gen_documento_guia',
                'ordering': ['-id'],
            },
        ),
    ]
