# Generated by Django 4.2.4 on 2024-03-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0029_alter_ciudad_latitud_alter_ciudad_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='apellido1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='apellido2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='barrio',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='celular',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='codigo_ciuu',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='codigo_postal',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='correo',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='digito_verificacion',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombre1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombre2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombre_corto',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='numero_identificacion',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(max_length=50),
        ),
    ]
