# Generated by Django 4.2.4 on 2025-09-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0029_gendocumentoguia'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumento',
            name='guias',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gendocumentoguia',
            name='cobro_entrega',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='gendocumentoguia',
            name='costo',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='gendocumentoguia',
            name='declara',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='gendocumentoguia',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='gendocumentoguia',
            name='peso',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gendocumentoguia',
            name='peso_facturado',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gendocumentoguia',
            name='recaudo',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='gendocumentoguia',
            name='unidades',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gendocumentoguia',
            name='volumen',
            field=models.FloatField(default=0),
        ),
    ]
