# Generated by Django 4.2.4 on 2025-09-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0030_gendocumento_guias_gendocumentoguia_cobro_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumentoguia',
            name='total',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
