# Generated by Django 4.2.4 on 2024-03-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0030_alter_contacto_apellido1_alter_contacto_apellido2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='comentario',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='cue',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='estado_anulado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documento',
            name='estado_electronico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documento',
            name='soporte',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
