# Generated by Django 4.2.4 on 2025-09-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0031_gendocumentoguia_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='genregimen',
            name='inactivo',
            field=models.BooleanField(default=False),
        ),
    ]
