# Generated by Django 4.2.4 on 2025-09-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0032_genregimen_inactivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='genitem',
            name='costo_promedio',
            field=models.FloatField(default=0),
        ),
    ]
