# Generated by Django 4.2.4 on 2024-03-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0032_alter_documento_base_impuesto_alter_documento_cobrar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoimpuesto',
            name='base',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='documentoimpuesto',
            name='porcentaje',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='documentoimpuesto',
            name='total',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
    ]
