# Generated by Django 4.2.4 on 2024-03-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0033_alter_documentoimpuesto_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentodetalle',
            name='porcentaje_descuento',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
    ]
