# Generated by Django 4.2.4 on 2025-09-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0033_genitem_costo_promedio'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='costo',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
