# Generated by Django 4.2.4 on 2025-09-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0034_gendocumentodetalle_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genitem',
            name='costo',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='genitem',
            name='costo_promedio',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='genitem',
            name='precio',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
