# Generated by Django 4.2.4 on 2025-09-29 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_alter_congrupo_options'),
        ('general', '0035_alter_genitem_costo_alter_genitem_costo_promedio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genitem',
            name='cuenta_costo_venta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itemes_cuenta_costo_venta_rel', to='contabilidad.concuenta'),
        ),
    ]
