# Generated by Django 4.2.4 on 2025-09-30 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_alter_congrupo_options'),
        ('general', '0036_genitem_cuenta_costo_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='genitem',
            name='cuenta_inventario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itemes_cuenta_inventario_rel', to='contabilidad.concuenta'),
        ),
    ]
