# Generated by Django 4.2.4 on 2025-09-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0037_genitem_cuenta_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='genitem',
            name='costo_total',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
