# Generated by Django 4.2.4 on 2025-10-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0038_genitem_costo_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumentotipo',
            name='operacion_remision',
            field=models.BigIntegerField(default=0),
        ),
    ]
