# Generated by Django 4.2.4 on 2025-10-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0039_gendocumentotipo_operacion_remision'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='cantidad_afectada',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='cantidad_pendiente',
            field=models.FloatField(default=0),
        ),
    ]
