# Generated by Django 4.2.4 on 2025-10-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0040_gendocumentodetalle_cantidad_afectada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumentotipo',
            name='afecta_cantidad',
            field=models.BooleanField(default=False),
        ),
    ]
