# Generated by Django 4.2.4 on 2025-10-02 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0041_gendocumentotipo_afecta_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='documento_detalle_afectado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_detalles_documento_afectado_rel', to='general.gendocumentodetalle'),
        ),
        migrations.AlterField(
            model_name='gendocumento',
            name='documento_referencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_documento_referencia_rel', to='general.gendocumento'),
        ),
        migrations.AlterField(
            model_name='gendocumentodetalle',
            name='documento_afectado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_detalles_documento_detalle_afectado_rel', to='general.gendocumento'),
        ),
    ]
