# Generated by Django 4.2.4 on 2025-10-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0042_gendocumentodetalle_documento_detalle_afectado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='operacion_remision',
            field=models.BigIntegerField(default=0),
        ),
    ]
