# Generated by Django 4.2.4 on 2024-04-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0042_documentotipo_resolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='regimen',
            name='codigo_interface',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
