# Generated by Django 4.2.4 on 2024-04-03 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0043_regimen_codigo_interface'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resolucion',
            name='ambiente',
        ),
    ]
