# Generated by Django 4.2.4 on 2025-10-03 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0043_gendocumentodetalle_operacion_remision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gendocumentodetalle',
            name='documento_afectado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_detalles_documento_afectado_rel', to='general.gendocumento'),
        ),
        migrations.AlterField(
            model_name='gendocumentodetalle',
            name='documento_detalle_afectado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_detalles_documento_detalle_afectado_rel', to='general.gendocumentodetalle'),
        ),
    ]
