# Generated by Django 4.2.4 on 2025-10-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0044_alter_gendocumentodetalle_documento_afectado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genconfiguracion',
            name='tte_clave_rndc',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='genconfiguracion',
            name='tte_fecha_vence_poliza',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='genconfiguracion',
            name='tte_numero_identificacion_aseguradora',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='genconfiguracion',
            name='tte_numero_poliza',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='genconfiguracion',
            name='tte_usuario_rndc',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
