# Generated by Django 4.2.4 on 2025-10-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0045_genconfiguracion_tte_clave_rndc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genprecio',
            name='tipo',
        ),
        migrations.AddField(
            model_name='genprecio',
            name='compra',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='genprecio',
            name='venta',
            field=models.BooleanField(default=False),
        ),
    ]
