# Generated by Django 4.2.4 on 2024-04-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0045_documento_electronico_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='fecha_validacion',
            field=models.DateTimeField(null=True),
        ),
    ]
