# Generated by Django 4.2.4 on 2025-10-15 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0046_remove_genprecio_tipo_genprecio_compra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genconfiguracion',
            name='gen_item_administracion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuraciones_item_administracion_rel', to='general.genitem'),
        ),
        migrations.AddField(
            model_name='genconfiguracion',
            name='gen_item_imprevisto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuraciones_item_imprevisto_rel', to='general.genitem'),
        ),
        migrations.AddField(
            model_name='genconfiguracion',
            name='gen_item_utilidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuraciones_item_utilidad_rel', to='general.genitem'),
        ),
    ]
