# Generated by Django 4.2.4 on 2025-11-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0047_genconfiguracion_gen_item_administracion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genconfiguracion',
            name='rut_decodificar_direcciones',
            field=models.BooleanField(default=True),
        ),
    ]
