# Generated by Django 4.2.4 on 2024-04-12 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0047_empresa_subdominio'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='documento_referencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gen_documentos', to='general.documento'),
        ),
    ]
