# Generated by Django 4.2.4 on 2026-08-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0048_genconfiguracion_rut_decodificar_direcciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genconfiguracion',
            name='hum_factor',
            field=models.DecimalField(decimal_places=3, default=7, max_digits=6),
        ),
    ]
