# Generated by Django 4.2.4 on 2024-04-12 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0048_documento_documento_referencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('formato_factura', models.CharField(default='F', max_length=2)),
                ('empresa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='general.empresa')),
            ],
            options={
                'db_table': 'gen_configuracion',
            },
        ),
    ]
