# Generated by Django 4.2.4 on 2024-04-14 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0049_configuracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='base_impuesto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='documento',
            name='cobrar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='documento',
            name='cobrar_afectado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='documento',
            name='cobrar_pendiente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='documento',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='documento',
            name='impuesto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='documento',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='documento',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='documento',
            name='total_bruto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
