# Generated by Django 4.2.4 on 2026-08-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0049_alter_genconfiguracion_hum_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='genconfiguracion',
            name='hum_licencia_no_remunerada_afecta_pension',
            field=models.BooleanField(default=False),
        ),
    ]
