# Generated by Django 4.2.4 on 2024-04-14 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0050_alter_documento_base_impuesto_alter_documento_cobrar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentodetalle',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='documentodetalle',
            name='porcentaje_descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='documentodetalle',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='documentodetalle',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='documentodetalle',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='documentodetalle',
            name='total_bruto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
