# Generated by Django 4.2.4 on 2024-04-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0051_alter_documentodetalle_descuento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='orden_compra',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefono',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
