# Generated by Django 4.2.4 on 2024-04-19 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0052_documento_orden_compra_alter_empresa_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='plazo_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gen_documentos', to='general.plazopago'),
        ),
    ]
