# Generated by Django 4.2.4 on 2024-04-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0053_documento_plazo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='correo',
            field=models.CharField(max_length=255),
        ),
    ]
