# Generated by Django 4.2.4 on 2024-04-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0056_alter_documentotipo_consecutivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentotipo',
            name='consecutivo',
            field=models.IntegerField(default=1),
        ),
    ]
