# Generated by Django 4.2.4 on 2024-05-01 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0057_alter_documentotipo_consecutivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.estado'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='general.empresa'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='asesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='general.asesor'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.ciudad'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='identificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.identificacion'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='plazo_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='general.plazopago'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='precio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='general.precio'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='regimen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.regimen'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='tipo_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.tipopersona'),
        ),
        migrations.AlterField(
            model_name='cuentabanco',
            name='cuenta_banco_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_bancos', to='general.cuentabancotipo'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='contacto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contactos_rel', to='general.contacto'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='documento_referencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gen_documentos', to='general.documento'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='documento_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gen_documentos', to='general.documentotipo'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gen_documentos', to='general.empresa'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='metodo_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gen_documentos', to='general.metodopago'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='plazo_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gen_documentos', to='general.plazopago'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='resolucion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gen_documentos', to='general.resolucion'),
        ),
        migrations.AlterField(
            model_name='documentodetalle',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='general.documento'),
        ),
        migrations.AlterField(
            model_name='documentodetalle',
            name='documento_afectado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_afectado', to='general.documento'),
        ),
        migrations.AlterField(
            model_name='documentodetalle',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itemes_rel', to='general.item'),
        ),
        migrations.AlterField(
            model_name='documentoimpuesto',
            name='documento_detalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.documentodetalle'),
        ),
        migrations.AlterField(
            model_name='documentoimpuesto',
            name='impuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.impuesto'),
        ),
        migrations.AlterField(
            model_name='documentotipo',
            name='documento_clase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_tipos', to='general.documentoclase'),
        ),
        migrations.AlterField(
            model_name='documentotipo',
            name='resolucion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_tipos', to='general.resolucion'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.ciudad'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='identificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.identificacion'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='regimen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.regimen'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='tipo_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.tipopersona'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.pais'),
        ),
        migrations.AlterField(
            model_name='identificacion',
            name='pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='general.pais'),
        ),
        migrations.AlterField(
            model_name='itemimpuesto',
            name='impuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.impuesto'),
        ),
        migrations.AlterField(
            model_name='itemimpuesto',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itemImpuestos', to='general.item'),
        ),
        migrations.AlterField(
            model_name='preciodetalle',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='general.item'),
        ),
        migrations.AlterField(
            model_name='preciodetalle',
            name='precio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='general.precio'),
        ),
    ]
