# Generated by Django 4.2.4 on 2024-05-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0058_alter_ciudad_estado_alter_configuracion_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentodetalle',
            name='base_impuesto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='documentodetalle',
            name='impuesto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
