# Generated by Django 4.2.4 on 2024-05-07 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0059_documentodetalle_base_impuesto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoimpuesto',
            name='documento_detalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.documentodetalle'),
        ),
    ]
