# Generated by Django 4.2.4 on 2024-05-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0060_alter_documentoimpuesto_documento_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='informacion_factura',
            field=models.TextField(null=True),
        ),
    ]
