# Generated by Django 4.2.4 on 2024-05-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0062_documentodetalle_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoclase',
            name='grupo',
            field=models.IntegerField(null=True),
        ),
    ]
