# Generated by Django 4.2.4 on 2024-05-30 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_cuentaclase_remove_cuenta_movimiento_and_more'),
        ('general', '0064_rename_cobrar_documento_afectado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentodetalle',
            name='cuenta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas', to='contabilidad.cuenta'),
        ),
        migrations.AlterField(
            model_name='documentodetalle',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itemes', to='general.item'),
        ),
    ]
