# Generated by Django 4.2.4 on 2024-05-31 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_cuentaclase_remove_cuenta_movimiento_and_more'),
        ('general', '0066_documentodetalle_naturaleza'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentotipo',
            name='cuenta_cobrar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_tipos', to='contabilidad.cuenta'),
        ),
    ]
