# Generated by Django 4.2.4 on 2024-06-05 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_cuentaclase_remove_cuenta_movimiento_and_more'),
        ('general', '0068_contacto_cliente_contacto_plazo_pago_proveedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentotipo',
            name='cuenta_pagar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_tipos_cuenta_pagar', to='contabilidad.cuenta'),
        ),
        migrations.AlterField(
            model_name='documentotipo',
            name='cuenta_cobrar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_tipos_cuenta_cobrar', to='contabilidad.cuenta'),
        ),
        migrations.AlterField(
            model_name='documentotipo',
            name='documento_clase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_tipos_documento_clase', to='general.documentoclase'),
        ),
        migrations.AlterField(
            model_name='documentotipo',
            name='resolucion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_tipos_resolucion', to='general.resolucion'),
        ),
    ]
