# Generated by Django 4.2.4 on 2024-06-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0069_documentotipo_cuenta_pagar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='empleado',
            field=models.BooleanField(default=False),
        ),
    ]
