# Generated by Django 4.2.4 on 2024-06-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0070_contacto_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='venta_asesor',
            field=models.BooleanField(default=False),
        ),
    ]
