# Generated by Django 4.2.4 on 2024-06-17 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0071_configuracion_venta_asesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'gen_sede',
            },
        ),
        migrations.AddField(
            model_name='configuracion',
            name='venta_sede',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documento',
            name='asesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_asesor_rel', to='general.asesor'),
        ),
        migrations.AddField(
            model_name='documento',
            name='sede',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_sede_rel', to='general.sede'),
        ),
    ]
