# Generated by Django 4.2.4 on 2024-06-17 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0072_sede_configuracion_venta_sede_documento_asesor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='general.empresa')),
                ('sede', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuraciones_usuarios_sede_rel', to='general.sede')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gen_configuracion_usuario',
            },
        ),
    ]
