# Generated by Django 4.2.4 on 2024-06-17 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0073_configuracionusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_usuario_rel', to=settings.AUTH_USER_MODEL),
        ),
    ]
