# Generated by Django 4.2.4 on 2024-06-19 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0074_documento_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='ciudad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='general.ciudad'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='digito_verificacion',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='direccion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='identificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='general.identificacion'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='numero_identificacion',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='regimen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='general.regimen'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='tipo_persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='general.tipopersona'),
        ),
    ]
