# Generated by Django 4.2.4 on 2024-06-21 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0077_alter_impuesto_porcentaje_base'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impuesto',
            name='porcentaje_base',
        ),
    ]
