# Generated by Django 4.2.4 on 2024-06-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0079_impuesto_porcentaje_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoimpuesto',
            name='porcentaje_base',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
