# Generated by Django 4.2.4 on 2024-06-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0085_alter_documento_afectado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolucion',
            name='compra',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resolucion',
            name='venta',
            field=models.BooleanField(default=False),
        ),
    ]
