# Generated by Django 4.2.4 on 2024-06-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0086_resolucion_compra_resolucion_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentotipo',
            name='compra',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentotipo',
            name='venta',
            field=models.BooleanField(default=False),
        ),
    ]
