# Generated by Django 4.2.4 on 2024-06-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0087_documentotipo_compra_documentotipo_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentotipo',
            name='electronico',
            field=models.BooleanField(default=False),
        ),
    ]
