# Generated by Django 4.2.4 on 2024-06-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0088_documentotipo_electronico'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='asistente_electronico',
            field=models.BooleanField(default=False),
        ),
    ]
