# Generated by Django 4.2.4 on 2024-07-05 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0089_empresa_asistente_electronico'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('cuenta_banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_pagos_cuenta_banco', to='general.cuentabanco')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_pagos_documento', to='general.documento')),
            ],
            options={
                'db_table': 'gen_documento_pago',
            },
        ),
    ]
