# Generated by Django 4.2.4 on 2024-07-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0090_documentopago'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='informacion_factura_superior',
            field=models.TextField(null=True),
        ),
    ]
