# Generated by Django 4.2.4 on 2024-08-01 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0091_configuracion_informacion_factura_superior'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormaPago',
        ),
    ]
