# Generated by Django 4.2.4 on 2024-08-01 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0092_delete_formapago'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Asesor',
            new_name='GenAsesor',
        ),
    ]
