# Generated by Django 4.2.4 on 2024-08-01 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0093_rename_asesor_genasesor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ciudad',
            new_name='GenCiudad',
        ),
    ]
