# Generated by Django 4.2.4 on 2024-08-01 22:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0094_rename_ciudad_genciudad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConfiguracionUsuario',
            new_name='GenConfiguracionUsuario',
        ),
    ]
