# Generated by Django 4.2.4 on 2024-08-01 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0011_humcredito'),
        ('contabilidad', '0006_concomprobante'),
        ('general', '0096_rename_configuracion_genconfiguracion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacto',
            new_name='GenContacto',
        ),
    ]
