# Generated by Django 4.2.4 on 2024-08-01 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0097_rename_contacto_gencontacto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CuentaBancoTipo',
            new_name='GenCuentaBancoTipo',
        ),
    ]
