# Generated by Django 4.2.4 on 2024-08-01 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0098_rename_cuentabancotipo_gencuentabancotipo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CuentaBanco',
            new_name='GenCuentaBanco',
        ),
    ]
