# Generated by Django 4.2.4 on 2024-08-01 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0099_rename_cuentabanco_gencuentabanco'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocumentoClase',
            new_name='GenDocumentoClase',
        ),
    ]
