# Generated by Django 4.2.4 on 2024-08-01 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0101_rename_documentodetalle_gendocumentodetalle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocumentoImpuesto',
            new_name='GenDocumentoImpuesto',
        ),
    ]
