# Generated by Django 4.2.4 on 2024-08-01 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0102_rename_documentoimpuesto_gendocumentoimpuesto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocumentoPago',
            new_name='GenDocumentoPago',
        ),
    ]
