# Generated by Django 4.2.4 on 2024-08-01 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0006_concomprobante'),
        ('general', '0103_rename_documentopago_gendocumentopago'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocumentoTipo',
            new_name='GenDocumentoTipo',
        ),
    ]
