# Generated by Django 4.2.4 on 2024-08-01 23:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contabilidad', '0006_concomprobante'),
        ('general', '0104_rename_documentotipo_gendocumentotipo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documento',
            new_name='GenDocumento',
        ),
    ]
