# Generated by Django 4.2.4 on 2024-08-01 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0105_rename_documento_gendocumento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empresa',
            new_name='GenEmpresa',
        ),
    ]
