# Generated by Django 4.2.4 on 2024-08-01 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0106_rename_empresa_genempresa'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estado',
            new_name='GenEstado',
        ),
    ]
