# Generated by Django 4.2.4 on 2024-08-01 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0109_rename_impuesto_genimpuesto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemImpuesto',
            new_name='GenItemImpuesto',
        ),
    ]
