# Generated by Django 4.2.4 on 2024-08-01 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0114_rename_plazopago_genplazopago'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrecioDetalle',
            new_name='GenPrecioDetalle',
        ),
    ]
