# Generated by Django 4.2.4 on 2024-08-01 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0115_rename_preciodetalle_genpreciodetalle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Precio',
            new_name='GenPrecio',
        ),
    ]
