# Generated by Django 4.2.4 on 2024-08-01 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0116_rename_precio_genprecio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Regimen',
            new_name='GenRegimen',
        ),
    ]
