# Generated by Django 4.2.4 on 2024-08-01 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0119_rename_sede_gensede'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoPersona',
            new_name='GenTipoPersona',
        ),
    ]
