# Generated by Django 4.2.4 on 2024-08-02 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0006_concomprobante'),
        ('general', '0120_rename_tipopersona_gentipopersona'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='contacto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_detalles_contacto_rel', to='general.gencontacto'),
        ),
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='detalle',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='numero',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gendocumentodetalle',
            name='cuenta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_detalles_cuenta_rel', to='contabilidad.concuenta'),
        ),
        migrations.AlterField(
            model_name='gendocumentodetalle',
            name='documento_afectado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_detalles_documento_afectado_rel', to='general.gendocumento'),
        ),
        migrations.AlterField(
            model_name='gendocumentodetalle',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_detalles_item_rel', to='general.genitem'),
        ),
    ]
