# Generated by Django 4.2.4 on 2024-08-15 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0023_humpension_porcentaje_empleado_and_more'),
        ('general', '0122_genconfiguracion_gen_uvt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumento',
            name='programacion_detalle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_programacion_detalle_rel', to='humano.humprogramaciondetalle'),
        ),
    ]
