# Generated by Django 4.2.4 on 2024-08-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0123_gendocumento_programacion_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumento',
            name='fecha_hasta',
            field=models.DateTimeField(null=True),
        ),
    ]
