# Generated by Django 4.2.4 on 2024-08-15 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0023_humpension_porcentaje_empleado_and_more'),
        ('general', '0124_gendocumento_fecha_hasta'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumento',
            name='contrato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_contrato_rel', to='humano.humcontrato'),
        ),
        migrations.AddField(
            model_name='gendocumento',
            name='deduccion',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='gendocumento',
            name='devengado',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='gendocumento',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_grupo_rel', to='humano.humgrupo'),
        ),
        migrations.AddField(
            model_name='gendocumento',
            name='salario',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
