# Generated by Django 4.2.4 on 2024-08-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0126_alter_gendocumento_fecha_hasta'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='hora',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='porcentaje',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
