# Generated by Django 4.2.4 on 2024-08-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0128_gendocumentodetalle_concepto'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumento',
            name='base_cotizacion',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='gendocumento',
            name='base_prestacion',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='base_cotizacion',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='base_prestacion',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
