# Generated by Django 4.2.4 on 2024-08-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0129_gendocumento_base_cotizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='deduccion',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='devengado',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='operacion',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='pago_operado',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
