# Generated by Django 4.2.4 on 2024-08-20 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0041_humprogramacion_deduccion_humprogramacion_devengado'),
        ('general', '0130_gendocumentodetalle_deduccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='credito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_detalles_credito_rel', to='humano.humcredito'),
        ),
    ]
