# Generated by Django 4.2.4 on 2024-08-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0131_gendocumentodetalle_credito'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='dias',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
