# Generated by Django 4.2.4 on 2024-08-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0132_gendocumentodetalle_dias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gendocumentodetalle',
            name='dias',
            field=models.BigIntegerField(default=0),
        ),
    ]
