# Generated by Django 4.2.4 on 2024-08-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0133_alter_gendocumentodetalle_dias'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenComplemento',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('instalado', models.BooleanField(default=False)),
                ('datos_json', models.JSONField()),
            ],
            options={
                'db_table': 'gen_complemento',
            },
        ),
    ]
