# Generated by Django 4.2.4 on 2024-08-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0135_alter_gencomplemento_datos_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='gencomplemento',
            name='estructura_json',
            field=models.JSONField(null=True),
        ),
    ]
