# Generated by Django 4.2.4 on 2024-09-13 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0136_gencomplemento_estructura_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenBanco',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'gen_banco',
            },
        ),
        migrations.AddField(
            model_name='gencontacto',
            name='numero_cuenta',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gencontacto',
            name='banco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='general.genbanco'),
        ),
    ]
