# Generated by Django 4.2.4 on 2024-09-18 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0062_humprogramacion_periodo'),
        ('general', '0137_genbanco_gencontacto_numero_cuenta_gencontacto_banco'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumento',
            name='periodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_periodo_rel', to='humano.humperiodo'),
        ),
    ]
