# Generated by Django 4.2.4 on 2024-09-27 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0138_gendocumento_periodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenImpuestoTipo',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'gen_impuesto_tipo',
            },
        ),
        migrations.AddField(
            model_name='genimpuesto',
            name='operacion',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='genimpuesto',
            name='impuesto_tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='impuestos_impuesto_tipo_rel', to='general.genimpuestotipo'),
        ),
    ]
