# Generated by Django 4.2.4 on 2024-09-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0139_genimpuestotipo_genimpuesto_operacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumentoimpuesto',
            name='total_operado',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
