# Generated by Django 4.2.4 on 2024-09-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0140_gendocumentoimpuesto_total_operado'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='impuesto_operado',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
