# Generated by Django 4.2.4 on 2024-10-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0141_gendocumentodetalle_impuesto_operado'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumentotipo',
            name='cobrar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gendocumentotipo',
            name='pagar',
            field=models.BooleanField(default=False),
        ),
    ]
