# Generated by Django 4.2.4 on 2024-10-14 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0142_gendocumentotipo_cobrar_gendocumentotipo_pagar'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumento',
            name='cuenta_banco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_cuenta_banco_rel', to='general.gencuentabanco'),
        ),
    ]
