# Generated by Django 4.2.4 on 2024-10-14 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0143_gendocumento_cuenta_banco'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenCuentaBancoClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'gen_cuenta_banco_clase',
            },
        ),
        migrations.AlterField(
            model_name='gencuentabanco',
            name='cuenta_banco_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_bancos_cuenta_banco_tipo', to='general.gencuentabancotipo'),
        ),
        migrations.AddField(
            model_name='gencuentabanco',
            name='cuenta_banco_clase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_bancos_cuenta_banco_clase', to='general.gencuentabancoclase'),
        ),
    ]
