# Generated by Django 4.2.4 on 2024-10-14 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0144_gencuentabancoclase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gencontacto',
            name='cuenta_banco_clase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='general.gencuentabancoclase'),
        ),
    ]
