# Generated by Django 4.2.4 on 2024-10-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0145_gencontacto_cuenta_banco_clase'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumento',
            name='dias',
            field=models.BigIntegerField(default=0),
        ),
    ]
