# Generated by Django 4.2.4 on 2024-10-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0146_gendocumento_dias'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumento',
            name='impuesto_operado',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='gendocumento',
            name='impuesto_retencion',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='impuesto_retencion',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
