# Generated by Django 4.2.4 on 2024-10-30 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0147_gendocumento_impuesto_operado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genconfiguracion',
            name='formato_factura',
        ),
    ]
