# Generated by Django 4.2.4 on 2024-10-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0148_remove_genconfiguracion_formato_factura'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenParametros',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('uvt', models.DecimalField(decimal_places=6, default=47065, max_digits=20)),
                ('factor', models.DecimalField(decimal_places=3, default=7.666, max_digits=6)),
                ('salario_minimo', models.DecimalField(decimal_places=6, default=1300000, max_digits=20)),
                ('auxilio_transporte', models.DecimalField(decimal_places=6, default=162000, max_digits=20)),
            ],
            options={
                'db_table': 'gen_parametros',
            },
        ),
    ]
