# Generated by Django 4.2.4 on 2024-11-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0150_gendocumento_evento_aceptacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='tipo_registro',
            field=models.CharField(default='I', max_length=1),
        ),
    ]
