# Generated by Django 4.2.4 on 2024-11-15 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0025_alter_concomprobante_id'),
        ('general', '0152_gendocumento_comprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumento',
            name='grupo_contabilidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_grupo_contabilidad_rel', to='contabilidad.congrupo'),
        ),
    ]
