# Generated by Django 4.2.4 on 2024-11-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0153_gendocumento_grupo_contabilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumento',
            name='referencia_cue',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='gendocumento',
            name='referencia_numero',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gendocumento',
            name='referencia_prefijo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
