# Generated by Django 4.2.4 on 2024-11-25 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0154_gendocumento_referencia_cue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gendocumento',
            name='documento_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_documento_tipo_rel', to='general.gendocumentotipo'),
        ),
    ]
