# Generated by Django 4.2.4 on 2024-11-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0155_alter_gendocumento_documento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumento',
            name='estado_electronico_evento',
            field=models.BooleanField(default=False),
        ),
    ]
