# Generated by Django 4.2.4 on 2025-01-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0156_gendocumento_estado_electronico_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='gencontacto',
            name='correo_facturacion_electronica',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
