# Generated by Django 4.2.4 on 2025-01-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0157_gencontacto_correo_facturacion_electronica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genconfiguracion',
            name='gen_uvt',
            field=models.DecimalField(decimal_places=6, default=49799, max_digits=20),
        ),
        migrations.AlterField(
            model_name='genconfiguracion',
            name='hum_auxilio_transporte',
            field=models.DecimalField(decimal_places=6, default=200000, max_digits=20),
        ),
        migrations.AlterField(
            model_name='genconfiguracion',
            name='hum_salario_minimo',
            field=models.DecimalField(decimal_places=6, default=1423500, max_digits=20),
        ),
    ]
