# Generated by Django 4.2.4 on 2025-01-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0158_alter_genconfiguracion_gen_uvt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genconfiguracion',
            name='hum_factor',
            field=models.DecimalField(decimal_places=3, default=7.666, max_digits=6),
        ),
    ]
