# Generated by Django 4.2.4 on 2025-01-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0159_alter_genconfiguracion_hum_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumentotipo',
            name='operacion',
            field=models.IntegerField(default=0),
        ),
    ]
