# Generated by Django 4.2.4 on 2025-01-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0160_gendocumentotipo_operacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumento',
            name='estado_electronico_descartado',
            field=models.BooleanField(default=False),
        ),
    ]
