# Generated by Django 4.2.4 on 2025-01-21 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0161_gendocumento_estado_electronico_descartado'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=500)),
                ('extension', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=100)),
                ('tamano', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('almacenamiento_id', models.CharField(max_length=255)),
                ('documento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archivos_documento_rel', to='general.gendocumento')),
            ],
            options={
                'db_table': 'gen_archivo',
            },
        ),
    ]
