# Generated by Django 4.2.4 on 2025-01-22 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0162_genarchivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genarchivo',
            name='extension',
        ),
    ]
