# Generated by Django 4.2.4 on 2025-01-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0163_remove_genarchivo_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genregimen',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
    ]
