# Generated by Django 4.2.4 on 2025-01-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0164_alter_genregimen_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='genarchivo',
            name='hash',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
