# Generated by Django 4.2.4 on 2025-01-28 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0165_genarchivo_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genarchivo',
            old_name='hash',
            new_name='uuid',
        ),
    ]
