# Generated by Django 4.2.4 on 2025-01-29 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0080_humaporte_presentacion'),
        ('general', '0166_rename_hash_genarchivo_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='genconfiguracion',
            name='hum_entidad_riesgo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='humano.humentidad'),
        ),
    ]
