# Generated by Django 4.2.4 on 2025-01-31 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0089_rename_caja_humaporte_cotizacion_caja_and_more'),
        ('general', '0168_genidentificacion_aporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='novedad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_detalles_novedad_rel', to='humano.humnovedad'),
        ),
    ]
