# Generated by Django 4.2.4 on 2025-02-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0170_genidentificacion_tipo_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumentotipo',
            name='contabilidad',
            field=models.BooleanField(default=False),
        ),
    ]
