# Generated by Django 4.2.4 on 2025-02-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0171_gendocumentotipo_contabilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumento',
            name='estado_contabilizado',
            field=models.BooleanField(default=False),
        ),
    ]
