# Generated by Django 4.2.4 on 2025-02-05 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0028_alter_concuenta_codigo'),
        ('general', '0172_gendocumento_estado_contabilizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumentotipo',
            name='comprobante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_tipos_comprobante_rel', to='contabilidad.concomprobante'),
        ),
    ]
