# Generated by Django 4.2.4 on 2025-02-06 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0030_alter_conmovimiento_credito_and_more'),
        ('general', '0173_gendocumentotipo_comprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='genitem',
            name='cuenta_venta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itemes_cuenta_venta_rel', to='contabilidad.concuenta'),
        ),
    ]
