# Generated by Django 4.2.4 on 2025-02-07 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0030_alter_conmovimiento_credito_and_more'),
        ('general', '0174_genitem_cuenta_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='genimpuesto',
            name='cuenta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='impuestos_cuenta_rel', to='contabilidad.concuenta'),
        ),
    ]
