# Generated by Django 4.2.4 on 2025-02-08 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0176_genempresa_asistente_predetrminado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genempresa',
            old_name='asistente_predetrminado',
            new_name='asistente_predeterminado',
        ),
    ]
