# Generated by Django 4.2.4 on 2025-02-10 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0030_alter_conmovimiento_credito_and_more'),
        ('general', '0177_rename_asistente_predetrminado_genempresa_asistente_predeterminado'),
    ]

    operations = [
        migrations.AddField(
            model_name='gencuentabanco',
            name='cuenta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_bancos_cuenta_rel', to='contabilidad.concuenta'),
        ),
    ]
