# Generated by Django 4.2.4 on 2025-02-12 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0030_alter_conmovimiento_credito_and_more'),
        ('general', '0179_genitem_cuenta_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gendocumento',
            name='metodo_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gen_documentos_metodo_pago_rel', to='general.genmetodopago'),
        ),
        migrations.AlterField(
            model_name='gendocumento',
            name='plazo_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gen_documentos_plazo_pago_rel', to='general.genplazopago'),
        ),
        migrations.CreateModel(
            name='GenFormaPago',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('cuenta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='impuestos_cuenta_rel', to='contabilidad.concuenta')),
            ],
            options={
                'db_table': 'gen_forma_pago',
            },
        ),
        migrations.AddField(
            model_name='gendocumento',
            name='forma_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gen_documentos_forma_pago_rel', to='general.genformapago'),
        ),
    ]
