# Generated by Django 4.2.4 on 2025-02-12 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0030_alter_conmovimiento_credito_and_more'),
        ('general', '0180_alter_gendocumento_metodo_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genformapago',
            name='cuenta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formas_pagos_cuenta_rel', to='contabilidad.concuenta'),
        ),
    ]
