# Generated by Django 4.2.4 on 2025-02-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0181_alter_genformapago_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genformapago',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
