# Generated by Django 4.2.4 on 2025-02-21 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0031_conmovimiento_cierre'),
        ('general', '0182_alter_genformapago_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_detalles_grupo_rel', to='contabilidad.congrupo'),
        ),
    ]
