# Generated by Django 4.2.4 on 2025-02-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0183_gendocumentodetalle_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='genitem',
            name='negativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='genitem',
            name='remision',
            field=models.FloatField(default=0),
        ),
    ]
