# Generated by Django 4.2.4 on 2025-02-25 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('general', '0184_genitem_negativo_genitem_remision'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumento',
            name='almacen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_almacen_rel', to='inventario.invalmacen'),
        ),
    ]
