# Generated by Django 4.2.4 on 2025-02-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0186_gendocumentodetalle_almacen'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumentotipo',
            name='inventario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gendocumentotipo',
            name='operacion_inventario',
            field=models.IntegerField(default=0),
        ),
    ]
