# Generated by Django 4.2.4 on 2025-02-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0187_gendocumentotipo_inventario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='operacion_inventario',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gendocumentotipo',
            name='operacion',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gendocumentotipo',
            name='operacion_inventario',
            field=models.BigIntegerField(default=0),
        ),
    ]
