# Generated by Django 4.2.4 on 2025-02-28 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0189_gendocumentodetalle_cantidad_operada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genconfiguracion',
            name='venta_asesor',
        ),
        migrations.RemoveField(
            model_name='genconfiguracion',
            name='venta_sede',
        ),
    ]
