# Generated by Django 4.2.4 on 2025-03-03 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0104_humprogramaciondetalle_base_cotizacion_acumulado_and_more'),
        ('general', '0191_gendocumentodetalle_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumento',
            name='aporte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_aporte_rel', to='humano.humaporte'),
        ),
    ]
