# Generated by Django 4.2.4 on 2025-03-05 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0032_alter_conmovimiento_base'),
        ('general', '0192_gendocumento_aporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='gensede',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedes_grupo_rel', to='contabilidad.congrupo'),
        ),
    ]
