# Generated by Django 4.2.4 on 2025-03-05 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0032_alter_conmovimiento_base'),
        ('general', '0193_gensede_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumento',
            name='cuenta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_cuenta_rel', to='contabilidad.concuenta'),
        ),
    ]
