# Generated by Django 4.2.4 on 2025-03-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0194_gendocumento_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumento',
            name='provision_cesantia',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='gendocumento',
            name='provision_interes',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='gendocumento',
            name='provision_prima',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='gendocumento',
            name='provision_vacacion',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
