# Generated by Django 4.2.4 on 2025-03-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0195_gendocumento_provision_cesantia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumento',
            name='base_prestacion_vacacion',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='base_prestacion_vacacion',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
