# Generated by Django 4.2.4 on 2025-03-08 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0119_humaporte_cotizacion_pension_total'),
        ('general', '0196_gendocumento_base_prestacion_vacacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='contrato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_detalles_contrato_rel', to='humano.humcontrato'),
        ),
    ]
