# Generated by Django 4.2.4 on 2025-03-13 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0036_conactivo_depreciacion_acumulada_and_more'),
        ('general', '0197_gendocumentodetalle_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='activo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_detalles_activo_rel', to='contabilidad.conactivo'),
        ),
    ]
