# Generated by Django 4.2.4 on 2025-03-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0198_gendocumentodetalle_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='genitem',
            name='favorito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='genitem',
            name='venta',
            field=models.BooleanField(default=True),
        ),
    ]
