# Generated by Django 4.2.4 on 2025-03-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0199_genitem_favorito_genitem_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='genitem',
            name='inactivo',
            field=models.BooleanField(default=False),
        ),
    ]
