# Generated by Django 4.2.4 on 2025-03-17 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0200_genitem_inactivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='genconfiguracion',
            name='pos_documento_tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='general.gendocumentotipo'),
        ),
    ]
