# Generated by Django 4.2.4 on 2025-03-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0201_genconfiguracion_pos_documento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='genarchivo',
            name='archivo_tipo_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='genarchivo',
            name='codigo',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='genarchivo',
            name='modelo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
