# Generated by Django 4.2.4 on 2025-03-23 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0203_genitem_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gendocumentodetalle',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_detalles_documento_rel', to='general.gendocumento'),
        ),
    ]
