# Generated by Django 4.2.4 on 2025-05-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0204_alter_gendocumentodetalle_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumento',
            name='remision',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
