# Generated by Django 4.2.4 on 2025-05-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0205_gendocumento_remision'),
    ]

    operations = [
        migrations.AddField(
            model_name='genconfiguracion',
            name='gen_emitir_automaticamente',
            field=models.BooleanField(default=False),
        ),
    ]
