# Generated by Django 4.2.4 on 2025-05-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0206_genconfiguracion_gen_emitir_automaticamente'),
    ]

    operations = [
        migrations.AddField(
            model_name='genconfiguracion',
            name='rut_sincronizar_complemento',
            field=models.BooleanField(default=False),
        ),
    ]
