# Generated by Django 4.2.4 on 2025-05-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0207_genconfiguracion_rut_sincronizar_complemento'),
    ]

    operations = [
        migrations.AddField(
            model_name='genconfiguracion',
            name='rut_rutear_franja',
            field=models.BooleanField(default=False),
        ),
    ]
