# Generated by Django 4.2.4 on 2025-07-03 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vr_credito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
