# Generated by Django 4.2.4 on 2025-07-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0003_user_vr_abono'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imagen_thumbnail',
            field=models.TextField(null=True),
        ),
    ]
