# Generated by Django 4.2.4 on 2025-08-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0004_user_imagen_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='operacion_cargo_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='operacion_id',
            field=models.IntegerField(null=True),
        ),
    ]
