# Generated by Django 4.2.4 on 2024-07-26 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0004_user_cortesia'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='es_socio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='socio_id',
            field=models.IntegerField(null=True),
        ),
    ]
