# Generated by Django 4.2.4 on 2025-08-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0005_user_operacion_cargo_id_user_operacion_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='es_administrador',
            field=models.BooleanField(default=False),
        ),
    ]
