# Generated by Django 4.2.4 on 2025-01-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0005_user_es_socio_user_socio_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='numero_identificacion',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
