# Generated by Django 4.2.4 on 2025-08-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0006_user_es_administrador'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aplicacion',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
