# Generated by Django 4.2.4 on 2025-09-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0007_user_aplicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='empresa_nombre',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='empresa_numero_identificacion',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
