# Generated by Django 4.2 on 2023-06-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquilino', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
