# Generated by Django 4.2 on 2023-06-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquilino', '0002_empresa_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='imagen',
            field=models.TextField(null=True),
        ),
    ]
