# Generated by Django 4.2 on 2023-07-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquilino', '0003_empresa_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'inq_plan',
            },
        ),
        migrations.AlterModelTable(
            name='empresa',
            table='inq_empresa',
        ),
    ]
