# Generated by Django 4.2 on 2023-07-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquilino', '0004_plan_alter_empresa_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
