# Generated by Django 4.2 on 2023-07-11 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquilino', '0006_empresa_plan'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dominio',
            table='inq_dominio',
        ),
    ]
