# Generated by Django 4.2 on 2023-07-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquilino', '0008_plan_limite_electronicos_plan_limite_ingresos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
