# Generated by Django 4.2 on 2023-07-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquilino', '0009_alter_plan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='limite_electronicos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='plan',
            name='limite_ingresos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='plan',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='plan',
            name='precio_usuario_adicional',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
