# Generated by Django 4.2 on 2023-07-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquilino', '0010_alter_plan_limite_electronicos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='usuario_id',
            field=models.IntegerField(null=True),
        ),
    ]
