# Generated by Django 4.2 on 2023-07-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquilino', '0011_empresa_usuario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='usuarios',
            field=models.IntegerField(default=1),
        ),
    ]
