# Generated by Django 4.2.4 on 2025-07-02 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0019_alter_genimpuesto_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('vence', models.DateField()),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presupuestos_contacto_rel', to='general.gencontacto')),
            ],
            options={
                'db_table': 'crm_presupuesto',
                'ordering': ['-id'],
            },
        ),
    ]
