# Generated by Django 4.2.4 on 2025-05-30 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contenedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=200, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_conexion', models.DateTimeField(auto_now_add=True, null=True)),
                ('imagen', models.TextField(null=True)),
                ('usuarios', models.IntegerField(default=1)),
                ('reddoc', models.BooleanField(default=False)),
                ('ruteo', models.BooleanField(default=False)),
                ('cortesia', models.BooleanField(default=False)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
            ],
            options={
                'db_table': 'cnt_contenedor',
            },
        ),
        migrations.CreateModel(
            name='CtnCiudad',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('codigo_postal', models.CharField(max_length=10, null=True)),
                ('porcentaje_impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'db_table': 'cnt_ciudad',
            },
        ),
        migrations.CreateModel(
            name='CtnConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True)),
                ('contenedor_id', models.IntegerField(null=True)),
                ('contenedor', models.CharField(max_length=200, null=True)),
                ('subdominio', models.CharField(max_length=100, null=True)),
                ('usuarios', models.IntegerField(default=0)),
                ('vr_plan', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('vr_usuario_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('vr_total', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('cortesia', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cnt_consumo',
            },
        ),
        migrations.CreateModel(
            name='CtnConsumoPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'cnt_consumo_periodo',
            },
        ),
        migrations.CreateModel(
            name='CtnDireccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('direccion', models.CharField(max_length=150)),
                ('direccion_formato', models.CharField(max_length=150)),
                ('latitud', models.DecimalField(decimal_places=15, max_digits=25, null=True)),
                ('longitud', models.DecimalField(decimal_places=15, max_digits=25, null=True)),
                ('cantidad_resultados', models.IntegerField(default=0)),
                ('resultados', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cnt_direccion',
            },
        ),
        migrations.CreateModel(
            name='CtnEstado',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'cnt_estado',
            },
        ),
        migrations.CreateModel(
            name='CtnEventoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('evento', models.CharField(max_length=50, null=True)),
                ('entorno', models.CharField(max_length=10, null=True)),
                ('transaccion', models.CharField(max_length=50, null=True)),
                ('metodo_pago', models.CharField(max_length=50, null=True)),
                ('referencia', models.CharField(max_length=50, null=True)),
                ('correo', models.CharField(max_length=250, null=True)),
                ('estado', models.CharField(max_length=50, null=True)),
                ('fecha_transaccion', models.DateTimeField(null=True)),
                ('estado_aplicado', models.BooleanField(default=False)),
                ('vr_original', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('vr_aplicar', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
            ],
            options={
                'db_table': 'cnt_evento_pago',
            },
        ),
        migrations.CreateModel(
            name='CtnIdentificacion',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('orden', models.BigIntegerField(default=0)),
                ('codigo', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'cnt_identificacion',
            },
        ),
        migrations.CreateModel(
            name='CtnInformacionFacturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_identificacion', models.CharField(max_length=20, null=True)),
                ('digito_verificacion', models.CharField(max_length=1, null=True)),
                ('nombre_corto', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=50, null=True)),
                ('telefono', models.CharField(max_length=50, null=True)),
                ('correo', models.EmailField(max_length=255)),
            ],
            options={
                'db_table': 'cnt_informacion_facturacion',
            },
        ),
        migrations.CreateModel(
            name='CtnMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20, null=True)),
                ('fecha', models.DateTimeField(null=True)),
                ('fecha_vence', models.DateField(null=True)),
                ('vr_total', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('vr_afectado', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('vr_saldo', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('contenedor_movimiento_id', models.IntegerField(null=True)),
                ('documento_fisico', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cnt_movimiento',
            },
        ),
        migrations.CreateModel(
            name='CtnPais',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('codigo', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'cnt_pais',
            },
        ),
        migrations.CreateModel(
            name='CtnPlan',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('limite_usuarios', models.IntegerField(default=0)),
                ('usuarios_base', models.IntegerField(default=0)),
                ('limite_ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('precio_usuario_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('limite_electronicos', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('plan_tipo_id', models.CharField(max_length=1, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('compra', models.BooleanField(default=False)),
                ('tesoreria', models.BooleanField(default=False)),
                ('venta', models.BooleanField(default=False)),
                ('cartera', models.BooleanField(default=False)),
                ('inventario', models.BooleanField(default=False)),
                ('humano', models.BooleanField(default=False)),
                ('contabilidad', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cnt_plan',
            },
        ),
        migrations.CreateModel(
            name='CtnRegimen',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cnt_regimen',
            },
        ),
        migrations.CreateModel(
            name='CtnSocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cnt_socio',
            },
        ),
        migrations.CreateModel(
            name='CtnTipoPersona',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cnt_tipo_persona',
            },
        ),
        migrations.CreateModel(
            name='CtnVerificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.IntegerField(null=True)),
                ('contenedor_id', models.IntegerField(null=True)),
                ('token', models.CharField(max_length=50)),
                ('estado_usado', models.BooleanField(default=False)),
                ('vence', models.DateField(null=True)),
                ('accion', models.CharField(default='registro', max_length=10)),
                ('usuario_invitado_username', models.EmailField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'cnt_verificacion',
            },
        ),
        migrations.CreateModel(
            name='Dominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'cnt_dominio',
            },
        ),
        migrations.CreateModel(
            name='UsuarioContenedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=20, null=True)),
                ('contenedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenedor.contenedor')),
            ],
            options={
                'db_table': 'cnt_usuario_contenedor',
            },
        ),
    ]
