# Generated by Django 4.2.4 on 2023-09-22 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True)),
                ('contenedor_id', models.IntegerField(null=True)),
                ('contenedor', models.CharField(max_length=200, null=True)),
                ('usuarios', models.IntegerField(default=0)),
                ('vr_plan', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('vr_usuario_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('vr_total', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
            ],
            options={
                'db_table': 'cnt_consumo',
            },
        ),
        migrations.CreateModel(
            name='Contenedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=200, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.TextField(null=True)),
                ('usuario_id', models.IntegerField(null=True)),
                ('usuarios', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'cnt_contenedor',
            },
        ),
        migrations.CreateModel(
            name='ContenedorCiudad',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('codigo_postal', models.CharField(max_length=10, null=True)),
                ('porcentaje_impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'db_table': 'cnt_ciudad',
            },
        ),
        migrations.CreateModel(
            name='ContenedorEstado',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'cnt_estado',
            },
        ),
        migrations.CreateModel(
            name='ContenedorIdentificacion',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('orden', models.BigIntegerField(default=0)),
                ('codigo', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'cnt_identificacion',
            },
        ),
        migrations.CreateModel(
            name='ContenedorMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20, null=True)),
                ('fecha', models.DateField(null=True)),
                ('vr_total', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('vr_afectado', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('vr_saldo', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
            ],
            options={
                'db_table': 'cnt_movimiento',
            },
        ),
        migrations.CreateModel(
            name='ContenedorPais',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('codigo', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'cnt_pais',
            },
        ),
        migrations.CreateModel(
            name='Dominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'cnt_dominio',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('limite_usuarios', models.IntegerField(default=0)),
                ('usuarios_base', models.IntegerField(default=0)),
                ('limite_ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('precio_usuario_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('limite_electronicos', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
            ],
            options={
                'db_table': 'cnt_plan',
            },
        ),
        migrations.CreateModel(
            name='Verificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.IntegerField(null=True)),
                ('contenedor_id', models.IntegerField(null=True)),
                ('token', models.CharField(max_length=50)),
                ('estado_usado', models.BooleanField(default=False)),
                ('vence', models.DateField(null=True)),
                ('accion', models.CharField(default='registro', max_length=10)),
                ('usuario_invitado_username', models.EmailField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'cnt_verificacion',
            },
        ),
        migrations.CreateModel(
            name='UsuarioContenedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=20, null=True)),
                ('contenedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenedor.contenedor')),
            ],
            options={
                'db_table': 'cnt_usuario_contenedor',
            },
        ),
    ]
