# Generated by Django 4.2.4 on 2025-05-30 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenedor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocontenedor',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dominio',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='contenedor.contenedor'),
        ),
        migrations.AddField(
            model_name='ctnmovimiento',
            name='socio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenedor.ctnsocio'),
        ),
        migrations.AddField(
            model_name='ctnmovimiento',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ctninformacionfacturacion',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenedor.ctnciudad'),
        ),
        migrations.AddField(
            model_name='ctninformacionfacturacion',
            name='identificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenedor.ctnidentificacion'),
        ),
        migrations.AddField(
            model_name='ctninformacionfacturacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ctnidentificacion',
            name='pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenedor.ctnpais'),
        ),
        migrations.AddField(
            model_name='ctnestado',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenedor.ctnpais'),
        ),
        migrations.AddField(
            model_name='ctndireccion',
            name='ciudad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contenedor.ctnciudad'),
        ),
        migrations.AddField(
            model_name='ctnconsumo',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenedor.ctnplan'),
        ),
        migrations.AddField(
            model_name='ctnconsumo',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ctnciudad',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenedor.ctnestado'),
        ),
        migrations.AddField(
            model_name='contenedor',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenedor.ctnplan'),
        ),
        migrations.AddField(
            model_name='contenedor',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='usuariocontenedor',
            unique_together={('usuario', 'contenedor')},
        ),
    ]
