# Generated by Django 4.2.4 on 2025-06-14 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ctnplan',
            options={'ordering': ['-id']},
        ),
    ]
