# Generated by Django 4.2.4 on 2024-06-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0004_consumoperiodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumo',
            name='subdominio',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
