# Generated by Django 4.2.4 on 2025-07-04 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0004_ctnsocio_porcentaje_comision'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ctnmovimiento',
            options={'ordering': ['-fecha']},
        ),
    ]
