# Generated by Django 4.2.4 on 2025-07-07 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0006_ctnmovimiento_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctnmovimiento',
            name='movimiento_referencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contenedor.ctnmovimiento'),
        ),
    ]
