# Generated by Django 4.2.4 on 2025-07-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0007_ctnmovimiento_movimiento_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctndireccion',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ctndireccion',
            name='direccion_formato',
            field=models.CharField(max_length=200),
        ),
    ]
