# Generated by Django 4.2.4 on 2024-06-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0007_eventopago'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventopago',
            name='metodo_pago',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eventopago',
            name='transaccion',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
