# Generated by Django 4.2.4 on 2024-06-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0008_eventopago_metodo_pago_eventopago_transaccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventopago',
            name='correo',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='eventopago',
            name='estado',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eventopago',
            name='fecha_transaccion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='eventopago',
            name='referencia',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
