# Generated by Django 4.2.4 on 2025-07-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0009_ctneventopago_datos_alter_ctneventopago_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctnmovimiento',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ctnmovimiento',
            name='fecha_vence',
            field=models.DateField(auto_now_add=True),
        ),
    ]
