# Generated by Django 4.2.4 on 2024-06-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0010_alter_eventopago_fecha_transaccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenedormovimiento',
            name='contenedor_movimiento_id',
            field=models.IntegerField(null=True),
        ),
    ]
