# Generated by Django 4.2.4 on 2025-07-24 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0010_alter_ctnmovimiento_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctnmovimiento',
            name='vr_total_operado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
