# Generated by Django 4.2.4 on 2025-07-24 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0011_ctnmovimiento_vr_total_operado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctnmovimiento',
            name='fecha_vence',
        ),
    ]
