# Generated by Django 4.2.4 on 2024-07-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0012_contenedor_reddoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenedormovimiento',
            name='documento_fisico',
            field=models.BooleanField(default=False),
        ),
    ]
