# Generated by Django 4.2.4 on 2025-07-24 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenedor', '0012_remove_ctnmovimiento_fecha_vence'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctnsocio',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
