# Generated by Django 4.2.4 on 2025-07-24 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0013_ctnsocio_usuario'),
    ]
