# Generated by Django 4.2.4 on 2024-07-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0013_contenedormovimiento_documento_fisico'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenedor',
            name='ruteo',
            field=models.BooleanField(default=False),
        ),
    ]
