# Generated by Django 4.2.4 on 2024-07-22 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenedor', '0014_contenedor_ruteo'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacionFacturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_identificacion', models.CharField(max_length=20, null=True)),
                ('digito_verificacion', models.CharField(max_length=1, null=True)),
                ('nombre_corto', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=50, null=True)),
                ('telefono', models.CharField(max_length=50, null=True)),
                ('correo', models.EmailField(max_length=255)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenedor.contenedorciudad')),
                ('identificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenedor.contenedoridentificacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cnt_informacion_facturacion',
            },
        ),
    ]
