# Generated by Django 4.2.4 on 2025-07-24 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0014_alter_ctnmovimiento_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctnmovimiento',
            name='lote',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
