# Generated by Django 4.2.4 on 2025-07-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0015_ctnmovimiento_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctnmovimiento',
            name='factura_id',
            field=models.IntegerField(null=True),
        ),
    ]
