# Generated by Django 4.2.4 on 2024-07-26 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0015_informacionfacturacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CtnSocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cnt_socio',
            },
        ),
    ]
