# Generated by Django 4.2.4 on 2025-07-26 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0016_ctnmovimiento_factura_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctnmovimiento',
            name='contenedor_movimiento_id',
        ),
    ]
