# Generated by Django 4.2.4 on 2024-07-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0016_ctnsocio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenedormovimiento',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
    ]
