# Generated by Django 4.2.4 on 2025-07-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0017_remove_ctnmovimiento_contenedor_movimiento_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctnmovimiento',
            name='genera_factura',
            field=models.BooleanField(default=False),
        ),
    ]
