# Generated by Django 4.2.4 on 2024-07-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0018_alter_eventopago_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventopago',
            name='estado_aplicado',
            field=models.BooleanField(default=False),
        ),
    ]
