# Generated by Django 4.2.4 on 2025-07-29 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0018_ctnmovimiento_genera_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctnmovimiento',
            name='informacion_facturacion_id',
            field=models.IntegerField(null=True),
        ),
    ]
