# Generated by Django 4.2.4 on 2024-07-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0019_eventopago_estado_aplicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventopago',
            name='vr_aplicar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='eventopago',
            name='vr_original',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
