# Generated by Django 4.2.4 on 2025-10-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0019_ctnmovimiento_informacion_facturacion_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctnmovimiento',
            name='fecha_desde_consumo',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ctnmovimiento',
            name='fecha_hasta_consumo',
            field=models.DateField(null=True),
        ),
    ]
