# Generated by Django 4.2.4 on 2025-10-06 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenedor', '0020_ctnmovimiento_fecha_desde_consumo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CtnInvitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario_invitado', models.EmailField(max_length=255, null=True)),
                ('contenedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenedor.contenedor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cnt_invitacion',
                'ordering': ['-id'],
            },
        ),
    ]
