# Generated by Django 4.2.4 on 2024-07-27 17:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenedor', '0020_eventopago_vr_aplicar_eventopago_vr_original'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InformacionFacturacion',
            new_name='CtnInformacionFacturacion',
        ),
    ]
