# Generated by Django 4.2.4 on 2026-01-08 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0021_ctninvitacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenedor',
            name='numero_identificacion',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
