# Generated by Django 4.2.4 on 2026-01-08 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0022_contenedor_numero_identificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenedor',
            name='numero_identificacion',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
