# Generated by Django 4.2.4 on 2024-07-27 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0023_rename_contenedormovimiento_ctnmovimiento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Verificacion',
            new_name='CtnVerificacion',
        ),
    ]
