# Generated by Django 4.2.4 on 2024-07-27 18:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenedor', '0024_rename_verificacion_ctnverificacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Consumo',
            new_name='CtnConsumo',
        ),
    ]
