# Generated by Django 4.2.4 on 2026-01-27 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0024_alter_contenedor_numero_identificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenedor',
            name='fecha_hasta_plan',
            field=models.DateTimeField(null=True),
        ),
    ]
