# Generated by Django 4.2.4 on 2024-07-27 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0025_rename_consumo_ctnconsumo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConsumoPeriodo',
            new_name='CtnConsumoPeriodo',
        ),
    ]
