# Generated by Django 4.2.4 on 2026-01-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0025_contenedor_fecha_hasta_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctnconsumo',
            name='cortesia',
        ),
        migrations.RemoveField(
            model_name='ctnconsumo',
            name='vr_usuario_adicional',
        ),
        migrations.AddField(
            model_name='ctnconsumo',
            name='vr_dia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
