# Generated by Django 4.2.4 on 2026-01-28 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0026_remove_ctnconsumo_cortesia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenedor',
            name='fecha_hasta_plan',
            field=models.DateField(null=True),
        ),
    ]
