# Generated by Django 4.2.4 on 2024-07-27 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0026_rename_consumoperiodo_ctnconsumoperiodo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plan',
            new_name='CtnPlan',
        ),
    ]
