# Generated by Django 4.2.4 on 2026-01-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0027_alter_contenedor_fecha_hasta_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenedor',
            name='notificacion_eliminacion',
            field=models.BooleanField(default=False),
        ),
    ]
