# Generated by Django 4.2.4 on 2024-07-27 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0029_rename_contenedortipopersona_ctntipopersona'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContenedorRegimen',
            new_name='CtnRegimen',
        ),
    ]
