# Generated by Django 4.2.4 on 2024-07-27 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0033_rename_contenedorpais_ctnpais'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctnmovimiento',
            name='socio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenedor.ctnsocio'),
        ),
    ]
