# Generated by Django 4.2.4 on 2024-08-15 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenedor', '0034_ctnmovimiento_socio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenedor',
            name='usuario_id',
        ),
        migrations.AddField(
            model_name='contenedor',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
