# Generated by Django 4.2.4 on 2024-11-15 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0035_remove_contenedor_usuario_id_contenedor_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='CtnDireccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('direccion', models.CharField(max_length=150)),
                ('direccion_formato', models.CharField(max_length=150)),
                ('latitud', models.DecimalField(decimal_places=10, max_digits=20, null=True)),
                ('longitud', models.DecimalField(decimal_places=10, max_digits=20, null=True)),
                ('ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contenedor.ctnciudad')),
            ],
            options={
                'db_table': 'cnt_direccion',
            },
        ),
    ]
