# Generated by Django 4.2.4 on 2024-11-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0036_ctndireccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctndireccion',
            name='latitud',
            field=models.DecimalField(decimal_places=12, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='ctndireccion',
            name='longitud',
            field=models.DecimalField(decimal_places=12, max_digits=20, null=True),
        ),
    ]
