# Generated by Django 4.2.4 on 2024-11-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0037_alter_ctndireccion_latitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctndireccion',
            name='latitud',
            field=models.DecimalField(decimal_places=15, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='ctndireccion',
            name='longitud',
            field=models.DecimalField(decimal_places=15, max_digits=25, null=True),
        ),
    ]
