# Generated by Django 4.2.4 on 2024-11-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0038_alter_ctndireccion_latitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctndireccion',
            name='resultado',
            field=models.IntegerField(default=0),
        ),
    ]
