# Generated by Django 4.2.4 on 2024-11-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0040_rename_resultado_ctndireccion_cantidad_resultados'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctndireccion',
            name='resultados',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
