# Generated by Django 4.2.4 on 2025-01-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0041_ctndireccion_resultados'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenedor',
            name='fecha_ultima_conexion',
            field=models.DateTimeField(null=True),
        ),
    ]
