# Generated by Django 4.2.4 on 2025-01-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0042_contenedor_fecha_ultima_conexion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenedor',
            name='fecha_ultima_conexion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
