# Generated by Django 4.2.4 on 2025-03-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0044_ctnplan_plan_tipo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenedor',
            name='cortesia',
            field=models.BooleanField(default=False),
        ),
    ]
