# Generated by Django 4.2.4 on 2025-04-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0046_ctnconsumo_cortesia'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenedor',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
