# Generated by Django 4.2.4 on 2025-04-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0047_contenedor_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctnplan',
            name='orden',
            field=models.IntegerField(default=0),
        ),
    ]
