# Generated by Django 4.2.4 on 2025-04-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0048_ctnplan_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctnplan',
            name='cartera',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ctnplan',
            name='compra',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ctnplan',
            name='contabilidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ctnplan',
            name='humano',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ctnplan',
            name='inventario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ctnplan',
            name='tesoreria',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ctnplan',
            name='venta',
            field=models.BooleanField(default=False),
        ),
    ]
