# Generated by Django 4.2.4 on 2024-05-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('fechaRecogida', models.DateField(null=True)),
                ('fechaIngreso', models.DateField(null=True)),
                ('fechaDespacho', models.DateField(null=True)),
                ('fechaEntrega', models.DateField(null=True)),
                ('fechaSoporte', models.DateField(null=True)),
                ('documento', models.CharField(max_length=30, null=True)),
                ('destinatario', models.CharField(max_length=150, null=True)),
                ('destinatarioDireccion', models.CharField(max_length=150, null=True)),
                ('destinatarioTelefono', models.CharField(max_length=50, null=True)),
                ('destinatarioCorreo', models.CharField(max_length=255, null=True)),
                ('peso', models.FloatField(default=0)),
                ('volumen', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'tte_guia',
            },
        ),
    ]
