# Generated by Django 4.2.4 on 2025-06-07 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_genrh'),
        ('transporte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TteCarroceria',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tte_carroceria',
            },
        ),
        migrations.CreateModel(
            name='TteColor',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tte_color',
            },
        ),
        migrations.CreateModel(
            name='TteCombustible',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tte_combustible',
            },
        ),
        migrations.CreateModel(
            name='TteConductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_nacimiento', models.DateField()),
                ('numero_identificacion', models.CharField(max_length=20)),
                ('digito_verificacion', models.CharField(max_length=1, null=True)),
                ('nombre_corto', models.CharField(max_length=200)),
                ('nombre1', models.CharField(max_length=50, null=True)),
                ('nombre2', models.CharField(max_length=50, null=True)),
                ('apellido1', models.CharField(max_length=50, null=True)),
                ('apellido2', models.CharField(max_length=50, null=True)),
                ('direccion', models.CharField(max_length=100)),
                ('barrio', models.CharField(max_length=200, null=True)),
                ('telefono', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=50, null=True)),
                ('correo', models.CharField(max_length=255)),
                ('numero_licencia', models.CharField(max_length=50)),
                ('categoria_licencia', models.CharField(max_length=2)),
                ('fecha_vence_licencia', models.DateField()),
                ('fecha_expedicion_licencia', models.DateField()),
                ('fecha_ingreso', models.DateField(null=True)),
                ('fecha_retiro', models.DateField(null=True)),
                ('propio', models.BooleanField(default=False)),
                ('estado_inactivo', models.BooleanField(default=False)),
                ('estado_revisado', models.BooleanField(default=False)),
                ('comentario', models.CharField(max_length=500, null=True)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conductores_ciudad_rel', to='general.genciudad')),
                ('identificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conductores_identificacion_rel', to='general.genidentificacion')),
                ('rh', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conductores_rh_rel', to='general.genrh')),
            ],
            options={
                'db_table': 'tte_conductor',
            },
        ),
        migrations.CreateModel(
            name='TteDespachoTipo',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tte_despacho_tipo',
            },
        ),
        migrations.CreateModel(
            name='TteEmpaque',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tte_empaque',
            },
        ),
        migrations.CreateModel(
            name='TteLinea',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tte_linea',
            },
        ),
        migrations.CreateModel(
            name='TteMarca',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10)),
                ('remolque', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tte_marca',
            },
        ),
        migrations.CreateModel(
            name='TteOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tte_operacion',
            },
        ),
        migrations.CreateModel(
            name='TteProducto',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tte_producto',
            },
        ),
        migrations.CreateModel(
            name='TteRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tte_ruta',
            },
        ),
        migrations.CreateModel(
            name='TteServicio',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tte_servicio',
            },
        ),
        migrations.CreateModel(
            name='TteVehiculoConfiguracion',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tte_vehiculo_configuracion',
            },
        ),
        migrations.CreateModel(
            name='TteZona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tte_zona',
            },
        ),
        migrations.RenameField(
            model_name='tteguia',
            old_name='destinatarioCorreo',
            new_name='destinatario_correo',
        ),
        migrations.RenameField(
            model_name='tteguia',
            old_name='destinatarioTelefono',
            new_name='destinatario_telefono',
        ),
        migrations.RenameField(
            model_name='tteguia',
            old_name='fechaDespacho',
            new_name='fecha_despacho',
        ),
        migrations.RenameField(
            model_name='tteguia',
            old_name='fechaEntrega',
            new_name='fecha_entrega',
        ),
        migrations.RenameField(
            model_name='tteguia',
            old_name='fechaIngreso',
            new_name='fecha_ingreso',
        ),
        migrations.RenameField(
            model_name='tteguia',
            old_name='fechaRecogida',
            new_name='fecha_recogida',
        ),
        migrations.RenameField(
            model_name='tteguia',
            old_name='fechaSoporte',
            new_name='fecha_soporte',
        ),
        migrations.RemoveField(
            model_name='tteguia',
            name='destinatarioDireccion',
        ),
        migrations.AddField(
            model_name='tteguia',
            name='ciudad_destino',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='guias_ciudad_destino_rel', to='general.genciudad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tteguia',
            name='ciudad_origen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='guias_ciudad_origen_rel', to='general.genciudad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tteguia',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='guias_cliente_rel', to='general.gencontacto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tteguia',
            name='cobro_entrega',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='tteguia',
            name='comentario',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tteguia',
            name='contacto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='guias_contacto_rel', to='general.gencontacto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tteguia',
            name='contenido_verificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tteguia',
            name='declara',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='tteguia',
            name='destinatario_direccion',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tteguia',
            name='destinatario_nombre',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tteguia',
            name='estado_despachado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tteguia',
            name='estado_embarcado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tteguia',
            name='estado_entregado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tteguia',
            name='estado_ingreso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tteguia',
            name='estado_novedad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tteguia',
            name='estado_novedad_solucionada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tteguia',
            name='estado_recogido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tteguia',
            name='estado_rndc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tteguia',
            name='estado_soporte',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tteguia',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tteguia',
            name='flete',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='tteguia',
            name='liquidacion',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tteguia',
            name='manejo',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='tteguia',
            name='mercancia_peligrosa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tteguia',
            name='numero_rndc',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tteguia',
            name='peso_facturado',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tteguia',
            name='recaudo',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='tteguia',
            name='remitente_nombre',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tteguia',
            name='requiere_cita',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tteguia',
            name='unidades',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tteguia',
            name='destinatario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='guias_destinatario_rel', to='general.gencontacto'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TteVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('placa', models.CharField(max_length=6)),
                ('modelo', models.IntegerField()),
                ('modelo_repotenciado', models.IntegerField(null=True)),
                ('motor', models.CharField(max_length=50, null=True)),
                ('chasis', models.CharField(max_length=50, null=True)),
                ('ejes', models.IntegerField()),
                ('peso_vacio', models.IntegerField()),
                ('capacidad', models.IntegerField()),
                ('celular', models.CharField(max_length=50, null=True)),
                ('poliza', models.CharField(max_length=30, null=True)),
                ('vence_poliza', models.DateField()),
                ('tecnicomecanica', models.CharField(max_length=30, null=True)),
                ('vence_tecnicomecanica', models.DateField()),
                ('propio', models.BooleanField(default=False)),
                ('remolque', models.BooleanField(default=False)),
                ('estado_inactivo', models.BooleanField(default=False)),
                ('estado_revisado', models.BooleanField(default=False)),
                ('comentario', models.CharField(max_length=500, null=True)),
                ('aseguradora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos_aeguradora_rel', to='general.gencontacto')),
                ('carroceria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos_carroceria_rel', to='transporte.ttecarroceria')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos_color_rel', to='transporte.ttecolor')),
                ('combustible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos_combustible_rel', to='transporte.ttecombustible')),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos_vehiculo_configuracion_rel', to='transporte.ttevehiculoconfiguracion')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos_linea_rel', to='transporte.ttelinea')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos_marca_rel', to='transporte.ttemarca')),
                ('poseedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos_poseedor_rel', to='general.gencontacto')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos_propietario_rel', to='general.gencontacto')),
            ],
            options={
                'db_table': 'tte_vehiculo',
            },
        ),
        migrations.AddField(
            model_name='ttelinea',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lineas_marca_rel', to='transporte.ttemarca'),
        ),
        migrations.CreateModel(
            name='TteDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha', models.DateField()),
                ('numero', models.IntegerField(null=True)),
                ('numero_rndc', models.IntegerField(null=True)),
                ('fecha_salida', models.DateTimeField(null=True)),
                ('fecha_llegada', models.DateTimeField(null=True)),
                ('fecha_entrega', models.DateTimeField(null=True)),
                ('fecha_soporte', models.DateTimeField(null=True)),
                ('pago', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('precinto', models.CharField(max_length=30, null=True)),
                ('guias', models.FloatField(default=0)),
                ('unidades', models.FloatField(default=0)),
                ('peso', models.FloatField(default=0)),
                ('volumen', models.FloatField(default=0)),
                ('declara', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('flete', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('manejo', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('recaudo', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('cobro_entrega', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('comentario', models.CharField(max_length=500, null=True)),
                ('estado_rndc', models.BooleanField(default=False)),
                ('estado_entregado', models.BooleanField(default=False)),
                ('estado_soporte', models.BooleanField(default=False)),
                ('ciudad_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despachos_ciudad_destino_rel', to='general.genciudad')),
                ('ciudad_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despachos_ciudad_origen_rel', to='general.genciudad')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despachos_conductor_rel', to='transporte.tteconductor')),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despachos_contacto_rel', to='general.gencontacto')),
                ('despacho_tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despachos_despacho_tipo_rel', to='transporte.ttedespachotipo')),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despachos_operacion_rel', to='transporte.tteoperacion')),
                ('remolque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despachos_remolque_rel', to='transporte.ttevehiculo')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despachos_ruta_rel', to='transporte.tteruta')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despachos_vehiculo_rel', to='transporte.ttevehiculo')),
            ],
            options={
                'db_table': 'tte_despacho',
            },
        ),
        migrations.AddField(
            model_name='tteguia',
            name='despacho',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guias_despacho_rel', to='transporte.ttedespacho'),
        ),
        migrations.AddField(
            model_name='tteguia',
            name='empaque',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='guias_empaque_rel', to='transporte.tteempaque'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tteguia',
            name='operacion_cargo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='guias_operacion_cargo_rel', to='transporte.tteoperacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tteguia',
            name='operacion_ingeso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='guias_operacion_ingreso_rel', to='transporte.tteoperacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tteguia',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='guias_producto_rel', to='transporte.tteproducto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tteguia',
            name='ruta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guias_ruta_rel', to='transporte.tteruta'),
        ),
        migrations.AddField(
            model_name='tteguia',
            name='servicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='guias_servicio_rel', to='transporte.tteservicio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tteguia',
            name='zona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guias_zona_rel', to='transporte.ttezona'),
        ),
    ]
