# Generated by Django 4.2.4 on 2024-08-12 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guia',
            new_name='TteGuia',
        ),
    ]
