# Generated by Django 4.2.4 on 2025-06-11 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0002_ttecarroceria_ttecolor_ttecombustible_tteconductor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ttecarroceria',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='ttecolor',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='ttecombustible',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='tteconductor',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='ttedespacho',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='ttedespachotipo',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='tteempaque',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='tteguia',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='ttelinea',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='ttemarca',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='tteoperacion',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='tteproducto',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='tteruta',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='tteservicio',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='ttevehiculo',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='ttevehiculoconfiguracion',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='ttezona',
            options={'ordering': ['-id']},
        ),
    ]
