# Generated by Django 4.2.4 on 2025-07-17 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0003_alter_ttecarroceria_options_alter_ttecolor_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tteguia',
            old_name='operacion_ingeso',
            new_name='operacion_ingreso',
        ),
    ]
