# Generated by Django 4.2.4 on 2025-08-06 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0022_gendocumento_liquidacion'),
        ('transporte', '0004_rename_operacion_ingeso_tteguia_operacion_ingreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='TteNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('unidades', models.FloatField(default=0)),
                ('peso', models.FloatField(default=0)),
                ('volumen', models.FloatField(default=0)),
                ('declara', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('pago', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('flete', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('manejo', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('comentario', models.CharField(max_length=500, null=True)),
                ('ciudad_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='negocios_ciudad_destino_rel', to='general.genciudad')),
                ('ciudad_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='negocios_ciudad_origen_rel', to='general.genciudad')),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='negocios_contacto_rel', to='general.gencontacto')),
            ],
            options={
                'db_table': 'tte_negocio',
                'ordering': ['-id'],
            },
        ),
    ]
