# Generated by Django 4.2.4 on 2025-08-08 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0022_gendocumento_liquidacion'),
        ('transporte', '0005_ttenegocio'),
    ]

    operations = [
        migrations.AddField(
            model_name='tteoperacion',
            name='ciudad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_ciudad_rel', to='general.genciudad'),
            preserve_default=False,
        ),
    ]
