# Generated by Django 4.2.4 on 2025-08-09 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0006_tteoperacion_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='tteguia',
            name='costo',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
