# Generated by Django 4.2.4 on 2025-08-11 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0007_tteguia_costo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ttedespacho',
            name='conductor',
        ),
    ]
