# Generated by Django 4.2.4 on 2025-08-11 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0008_remove_ttedespacho_conductor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TteConductor',
        ),
    ]
