# Generated by Django 4.2.4 on 2025-08-11 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0022_gendocumento_liquidacion'),
        ('transporte', '0009_delete_tteconductor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttedespacho',
            name='conductor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='despachos_conductor_rel', to='general.gencontacto'),
            preserve_default=False,
        ),
    ]
