# Generated by Django 4.2.4 on 2025-08-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0010_ttedespacho_conductor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttedespacho',
            name='estado_aprobado',
            field=models.BooleanField(default=False),
        ),
    ]
