# Generated by Django 4.2.4 on 2025-08-11 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0011_ttedespacho_estado_aprobado'),
    ]

    operations = [
        migrations.CreateModel(
            name='TteDespachoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('unidades', models.FloatField(default=0)),
                ('peso', models.FloatField(default=0)),
                ('volumen', models.FloatField(default=0)),
                ('peso_facturado', models.FloatField(default=0)),
                ('costo', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('declara', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('flete', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('manejo', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('recaudo', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('cobro_entrega', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('despacho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despachos_detalles_despacho_rel', to='transporte.ttedespacho')),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despachos_detalles_guia_rel', to='transporte.tteguia')),
            ],
            options={
                'db_table': 'tte_despacho_detalle',
                'ordering': ['-id'],
            },
        ),
    ]
