# Generated by Django 4.2.4 on 2025-08-22 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0012_ttedespachodetalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttedespacho',
            name='remolque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='despachos_remolque_rel', to='transporte.ttevehiculo'),
        ),
    ]
