# Generated by Django 4.2.4 on 2025-08-22 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0013_alter_ttedespacho_remolque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttedespacho',
            name='ruta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='despachos_ruta_rel', to='transporte.tteruta'),
        ),
    ]
