# Generated by Django 4.2.4 on 2025-08-22 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0014_alter_ttedespacho_ruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttedespacho',
            name='servicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='despachos_servicio_rel', to='transporte.tteservicio'),
            preserve_default=False,
        ),
    ]
