# Generated by Django 4.2.4 on 2025-08-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0015_ttedespacho_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='TteCategoriaLicencia',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tte_categoria_licencia',
                'ordering': ['-id'],
            },
        ),
    ]
