# Generated by Django 4.2.4 on 2025-08-22 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0016_ttecategorialicencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ttecategorialicencia',
            options={'ordering': ['id']},
        ),
    ]
