# Generated by Django 4.2.4 on 2025-08-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0017_alter_ttecategorialicencia_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttenegocio',
            name='estado_aprobado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ttenegocio',
            name='publicar',
            field=models.BooleanField(default=False),
        ),
    ]
