# Generated by Django 4.2.4 on 2025-08-29 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0018_ttenegocio_estado_aprobado_ttenegocio_publicar'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttenegocio',
            name='empaque',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='negocios_empaque_rel', to='transporte.tteempaque'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ttenegocio',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='negocios_producto_rel', to='transporte.tteproducto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ttenegocio',
            name='servicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='negocios_servicio_rel', to='transporte.tteservicio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tteguia',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
