# Generated by Django 4.2.4 on 2025-08-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0019_ttenegocio_empaque_ttenegocio_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttenegocio',
            name='destinatario_correo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ttenegocio',
            name='destinatario_direccion',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ttenegocio',
            name='destinatario_nombre',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ttenegocio',
            name='destinatario_telefono',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
