# Generated by Django 4.2.4 on 2025-08-29 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0029_gendocumentoguia'),
        ('transporte', '0020_ttenegocio_destinatario_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tteguia',
            name='destinatario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guias_destinatario_rel', to='general.gencontacto'),
        ),
    ]
