# Generated by Django 4.2.4 on 2025-08-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0021_alter_tteguia_destinatario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tteguia',
            name='remitente_nombre',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
