# Generated by Django 4.2.4 on 2025-08-29 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0022_alter_tteguia_remitente_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttenegocio',
            name='operacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='negocios_operacion_ingreso_rel', to='transporte.tteoperacion'),
            preserve_default=False,
        ),
    ]
