# Generated by Django 4.2.4 on 2025-08-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0023_ttenegocio_operacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttedespacho',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
