# Generated by Django 4.2.4 on 2025-08-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0024_alter_ttedespacho_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttenegocio',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
