# Generated by Django 4.2.4 on 2025-09-01 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0025_ttenegocio_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='tteguia',
            name='negocio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guias_negocio_rel', to='transporte.ttenegocio'),
        ),
    ]
