# Generated by Django 4.2.4 on 2025-09-02 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0030_gendocumento_guias_gendocumentoguia_cobro_entrega_and_more'),
        ('transporte', '0026_tteguia_negocio'),
    ]

    operations = [
        migrations.AddField(
            model_name='tteguia',
            name='estado_facturado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tteguia',
            name='factura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guias_factura_rel', to='general.gendocumento'),
        ),
    ]
