# Generated by Django 4.2.4 on 2025-09-03 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0030_gendocumento_guias_gendocumentoguia_cobro_entrega_and_more'),
        ('transporte', '0027_tteguia_estado_facturado_tteguia_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttenegocio',
            name='contacto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='negocios_contacto_rel', to='general.gencontacto'),
        ),
        migrations.AlterField(
            model_name='ttenegocio',
            name='operacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='negocios_operacion_ingreso_rel', to='transporte.tteoperacion'),
        ),
    ]
