# Generated by Django 4.2.4 on 2025-09-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0028_alter_ttenegocio_contacto_alter_ttenegocio_operacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttenegocio',
            name='puntos_entrega',
            field=models.IntegerField(default=0),
        ),
    ]
