# Generated by Django 4.2.4 on 2025-09-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0029_ttenegocio_puntos_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttenegocio',
            name='nombre',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
